{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F0115',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'STG_JDE_PHONE_INCR', 'STG_JDE_PHONE_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' )) AS "PHONE_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WWAN8_FK_WPIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" || '\#' )) AS "WHOISWHO_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' || "EXT_SRC"."WWAN8_FK_WPIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" || '\#' )) AS "LNK_PHONE_WHOISWHO_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" || '\#' )) AS "LNK_PHONE_ACCOUNT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."WPAN8" AS "WPAN8"
		, "EXT_SRC"."WPIDLN" AS "WPIDLN"
		, "EXT_SRC"."WPRCK7" AS "WPRCK7"
		, "EXT_SRC"."WPCNLN" AS "WPCNLN"
		, "EXT_SRC"."WPAN8_BK" AS "WPAN8_BK"
		, "EXT_SRC"."WPIDLN_BK" AS "WPIDLN_BK"
		, "EXT_SRC"."WPCNLN_BK" AS "WPCNLN_BK"
		, "EXT_SRC"."WPRCK7_BK" AS "WPRCK7_BK"
		, "EXT_SRC"."WWAN8_FK_WPIDLN_BK" AS "WWAN8_FK_WPIDLN_BK"
		, "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" AS "WWIDLN_FK_WPIDLN_BK"
		, "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_WPAN8_BK"
		, "EXT_SRC"."WPPHTP" AS "WPPHTP"
		, "EXT_SRC"."WPAR1" AS "WPAR1"
		, "EXT_SRC"."WPPH1" AS "WPPH1"
		, "EXT_SRC"."WPUSER" AS "WPUSER"
		, "EXT_SRC"."WPPID" AS "WPPID"
		, "EXT_SRC"."WPUPMJ" AS "WPUPMJ"
		, "EXT_SRC"."WPJOBN" AS "WPJOBN"
		, "EXT_SRC"."WPUPMT" AS "WPUPMT"
		, "EXT_SRC"."WPCFNO1" AS "WPCFNO1"
		, "EXT_SRC"."WPGEN1" AS "WPGEN1"
		, "EXT_SRC"."WPFALGE" AS "WPFALGE"
		, "EXT_SRC"."WPSYNCS" AS "WPSYNCS"
		, "EXT_SRC"."WPCAAD" AS "WPCAAD"
	FROM {{ ref('JDEDWARDS_EXT_F0115') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' )) AS "PHONE_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WWAN8_FK_WPIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" || '\#' )) AS "WHOISWHO_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' || "EXT_SRC"."WWAN8_FK_WPIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" || '\#' )) AS "LNK_PHONE_WHOISWHO_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WPAN8_BK" || '\#' ||  "EXT_SRC"."WPIDLN_BK" || '\#' ||  "EXT_SRC"."WPCNLN_BK" || 
			'\#' ||  "EXT_SRC"."WPRCK7_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" || '\#' )) AS "LNK_PHONE_ACCOUNT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."WPAN8" AS "WPAN8"
		, "EXT_SRC"."WPIDLN" AS "WPIDLN"
		, "EXT_SRC"."WPRCK7" AS "WPRCK7"
		, "EXT_SRC"."WPCNLN" AS "WPCNLN"
		, "EXT_SRC"."WPAN8_BK" AS "WPAN8_BK"
		, "EXT_SRC"."WPIDLN_BK" AS "WPIDLN_BK"
		, "EXT_SRC"."WPCNLN_BK" AS "WPCNLN_BK"
		, "EXT_SRC"."WPRCK7_BK" AS "WPRCK7_BK"
		, "EXT_SRC"."WWAN8_FK_WPIDLN_BK" AS "WWAN8_FK_WPIDLN_BK"
		, "EXT_SRC"."WWIDLN_FK_WPIDLN_BK" AS "WWIDLN_FK_WPIDLN_BK"
		, "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_WPAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_WPAN8_BK"
		, "EXT_SRC"."WPPHTP" AS "WPPHTP"
		, "EXT_SRC"."WPAR1" AS "WPAR1"
		, "EXT_SRC"."WPPH1" AS "WPPH1"
		, "EXT_SRC"."WPUSER" AS "WPUSER"
		, "EXT_SRC"."WPPID" AS "WPPID"
		, "EXT_SRC"."WPUPMJ" AS "WPUPMJ"
		, "EXT_SRC"."WPJOBN" AS "WPJOBN"
		, "EXT_SRC"."WPUPMT" AS "WPUPMT"
		, "EXT_SRC"."WPCFNO1" AS "WPCFNO1"
		, "EXT_SRC"."WPGEN1" AS "WPGEN1"
		, "EXT_SRC"."WPFALGE" AS "WPFALGE"
		, "EXT_SRC"."WPSYNCS" AS "WPSYNCS"
		, "EXT_SRC"."WPCAAD" AS "WPCAAD"
	FROM {{ ref('JDEDWARDS_EXT_F0115') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'