{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F01151',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'STG_JDE_EMAIL_INCR', 'STG_JDE_EMAIL_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' )) AS "EMAIL_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WWAN8_FK_EAIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" || '\#' )) AS "WHOISWHO_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' || "EXT_SRC"."WWAN8_FK_EAIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" || '\#' )) AS "LNK_EMAIL_WHOISWHO_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" || '\#' )) AS "LNK_EMAIL_ACCOUNT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."EAAN8" AS "EAAN8"
		, "EXT_SRC"."EAIDLN" AS "EAIDLN"
		, "EXT_SRC"."EARCK7" AS "EARCK7"
		, "EXT_SRC"."EAAN8_BK" AS "EAAN8_BK"
		, "EXT_SRC"."EAIDLN_BK" AS "EAIDLN_BK"
		, "EXT_SRC"."EARCK7_BK" AS "EARCK7_BK"
		, "EXT_SRC"."WWAN8_FK_EAIDLN_BK" AS "WWAN8_FK_EAIDLN_BK"
		, "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" AS "WWIDLN_FK_EAIDLN_BK"
		, "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
		, "EXT_SRC"."EAETP" AS "EAETP"
		, "EXT_SRC"."EAEMAL" AS "EAEMAL"
		, "EXT_SRC"."EAUSER" AS "EAUSER"
		, "EXT_SRC"."EAPID" AS "EAPID"
		, "EXT_SRC"."EAUPMJ" AS "EAUPMJ"
		, "EXT_SRC"."EAJOBN" AS "EAJOBN"
		, "EXT_SRC"."EAUPMT" AS "EAUPMT"
		, "EXT_SRC"."EAEHIER" AS "EAEHIER"
		, "EXT_SRC"."EAEFOR" AS "EAEFOR"
		, "EXT_SRC"."EAECLASS" AS "EAECLASS"
		, "EXT_SRC"."EACFNO1" AS "EACFNO1"
		, "EXT_SRC"."EAGEN1" AS "EAGEN1"
		, "EXT_SRC"."EAFALGE" AS "EAFALGE"
		, "EXT_SRC"."EASYNCS" AS "EASYNCS"
		, "EXT_SRC"."EACAAD" AS "EACAAD"
	FROM {{ ref('JDEDWARDS_EXT_F01151') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' )) AS "EMAIL_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."WWAN8_FK_EAIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" || '\#' )) AS "WHOISWHO_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' || "EXT_SRC"."WWAN8_FK_EAIDLN_BK" || '\#' ||  "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" || '\#' )) AS "LNK_EMAIL_WHOISWHO_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."EAAN8_BK" || '\#' ||  "EXT_SRC"."EAIDLN_BK" || '\#' ||  "EXT_SRC"."EARCK7_BK" || 
			'\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" || '\#' )) AS "LNK_EMAIL_ACCOUNT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."EAAN8" AS "EAAN8"
		, "EXT_SRC"."EAIDLN" AS "EAIDLN"
		, "EXT_SRC"."EARCK7" AS "EARCK7"
		, "EXT_SRC"."EAAN8_BK" AS "EAAN8_BK"
		, "EXT_SRC"."EAIDLN_BK" AS "EAIDLN_BK"
		, "EXT_SRC"."EARCK7_BK" AS "EARCK7_BK"
		, "EXT_SRC"."WWAN8_FK_EAIDLN_BK" AS "WWAN8_FK_EAIDLN_BK"
		, "EXT_SRC"."WWIDLN_FK_EAIDLN_BK" AS "WWIDLN_FK_EAIDLN_BK"
		, "EXT_SRC"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
		, "EXT_SRC"."EAETP" AS "EAETP"
		, "EXT_SRC"."EAEMAL" AS "EAEMAL"
		, "EXT_SRC"."EAUSER" AS "EAUSER"
		, "EXT_SRC"."EAPID" AS "EAPID"
		, "EXT_SRC"."EAUPMJ" AS "EAUPMJ"
		, "EXT_SRC"."EAJOBN" AS "EAJOBN"
		, "EXT_SRC"."EAUPMT" AS "EAUPMT"
		, "EXT_SRC"."EAEHIER" AS "EAEHIER"
		, "EXT_SRC"."EAEFOR" AS "EAEFOR"
		, "EXT_SRC"."EAECLASS" AS "EAECLASS"
		, "EXT_SRC"."EACFNO1" AS "EACFNO1"
		, "EXT_SRC"."EAGEN1" AS "EAGEN1"
		, "EXT_SRC"."EAFALGE" AS "EAFALGE"
		, "EXT_SRC"."EASYNCS" AS "EASYNCS"
		, "EXT_SRC"."EACAAD" AS "EACAAD"
	FROM {{ ref('JDEDWARDS_EXT_F01151') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'