{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F4105',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'STG_JDE_ITEMCOST_INCR', 'STG_JDE_ITEMCOST_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' )) AS "ITEMCOST_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" || 
			'\#' )) AS "ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" || '\#' )) AS "BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" || '\#' )) AS "PRODUCT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" || '\#' )) AS "LNK_ITEMCOST_ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" || '\#' )) AS "LNK_ITEMCOST_BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" || '\#' )) AS "LNK_ITEMCOST_PRODUCT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."COITM" AS "COITM"
		, "EXT_SRC"."COMCU" AS "COMCU"
		, "EXT_SRC"."COLOCN" AS "COLOCN"
		, "EXT_SRC"."COLOTN" AS "COLOTN"
		, "EXT_SRC"."COLEDG" AS "COLEDG"
		, "EXT_SRC"."COITM_BK" AS "COITM_BK"
		, "EXT_SRC"."COMCU_BK" AS "COMCU_BK"
		, "EXT_SRC"."COLOCN_BK" AS "COLOCN_BK"
		, "EXT_SRC"."COLOTN_BK" AS "COLOTN_BK"
		, "EXT_SRC"."COLEDG_BK" AS "COLEDG_BK"
		, "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" AS "IBMCU_FK_ITEMBRANCH_COITM_BK"
		, "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" AS "IBITM_FK_ITEMBRANCH_COITM_BK"
		, "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" AS "MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK"
		, "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" AS "IMITM_FK_ITEMMASTER_COITM_BK"
		, "EXT_SRC"."COLITM" AS "COLITM"
		, "EXT_SRC"."COAITM" AS "COAITM"
		, "EXT_SRC"."COLOTG" AS "COLOTG"
		, "EXT_SRC"."COUNCS" AS "COUNCS"
		, "EXT_SRC"."COCSPO" AS "COCSPO"
		, "EXT_SRC"."COCSIN" AS "COCSIN"
		, "EXT_SRC"."COURCD" AS "COURCD"
		, "EXT_SRC"."COURDT" AS "COURDT"
		, "EXT_SRC"."COURAT" AS "COURAT"
		, "EXT_SRC"."COURAB" AS "COURAB"
		, "EXT_SRC"."COURRF" AS "COURRF"
		, "EXT_SRC"."COUSER" AS "COUSER"
		, "EXT_SRC"."COPID" AS "COPID"
		, "EXT_SRC"."COJOBN" AS "COJOBN"
		, "EXT_SRC"."COUPMJ" AS "COUPMJ"
		, "EXT_SRC"."COTDAY" AS "COTDAY"
		, "EXT_SRC"."COCCFL" AS "COCCFL"
		, "EXT_SRC"."COCRCS" AS "COCRCS"
		, "EXT_SRC"."COOSTC" AS "COOSTC"
		, "EXT_SRC"."COSTOC" AS "COSTOC"
	FROM {{ ref('JDEDWARDS_EXT_F4105') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' )) AS "ITEMCOST_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" || 
			'\#' )) AS "ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" || '\#' )) AS "BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" || '\#' )) AS "PRODUCT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" || '\#' )) AS "LNK_ITEMCOST_ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" || '\#' )) AS "LNK_ITEMCOST_BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."COITM_BK" || '\#' ||  "EXT_SRC"."COMCU_BK" || '\#' ||  "EXT_SRC"."COLOCN_BK" || '\#' ||  
			"EXT_SRC"."COLOTN_BK" || '\#' ||  "EXT_SRC"."COLEDG_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" || '\#' )) AS "LNK_ITEMCOST_PRODUCT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."COITM" AS "COITM"
		, "EXT_SRC"."COMCU" AS "COMCU"
		, "EXT_SRC"."COLOCN" AS "COLOCN"
		, "EXT_SRC"."COLOTN" AS "COLOTN"
		, "EXT_SRC"."COLEDG" AS "COLEDG"
		, "EXT_SRC"."COITM_BK" AS "COITM_BK"
		, "EXT_SRC"."COMCU_BK" AS "COMCU_BK"
		, "EXT_SRC"."COLOCN_BK" AS "COLOCN_BK"
		, "EXT_SRC"."COLOTN_BK" AS "COLOTN_BK"
		, "EXT_SRC"."COLEDG_BK" AS "COLEDG_BK"
		, "EXT_SRC"."IBMCU_FK_ITEMBRANCH_COITM_BK" AS "IBMCU_FK_ITEMBRANCH_COITM_BK"
		, "EXT_SRC"."IBITM_FK_ITEMBRANCH_COITM_BK" AS "IBITM_FK_ITEMBRANCH_COITM_BK"
		, "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK" AS "MCMCU_FK_BUSINESSUNITMASTER_COMCU_BK"
		, "EXT_SRC"."IMITM_FK_ITEMMASTER_COITM_BK" AS "IMITM_FK_ITEMMASTER_COITM_BK"
		, "EXT_SRC"."COLITM" AS "COLITM"
		, "EXT_SRC"."COAITM" AS "COAITM"
		, "EXT_SRC"."COLOTG" AS "COLOTG"
		, "EXT_SRC"."COUNCS" AS "COUNCS"
		, "EXT_SRC"."COCSPO" AS "COCSPO"
		, "EXT_SRC"."COCSIN" AS "COCSIN"
		, "EXT_SRC"."COURCD" AS "COURCD"
		, "EXT_SRC"."COURDT" AS "COURDT"
		, "EXT_SRC"."COURAT" AS "COURAT"
		, "EXT_SRC"."COURAB" AS "COURAB"
		, "EXT_SRC"."COURRF" AS "COURRF"
		, "EXT_SRC"."COUSER" AS "COUSER"
		, "EXT_SRC"."COPID" AS "COPID"
		, "EXT_SRC"."COJOBN" AS "COJOBN"
		, "EXT_SRC"."COUPMJ" AS "COUPMJ"
		, "EXT_SRC"."COTDAY" AS "COTDAY"
		, "EXT_SRC"."COCCFL" AS "COCCFL"
		, "EXT_SRC"."COCRCS" AS "COCRCS"
		, "EXT_SRC"."COOSTC" AS "COOSTC"
		, "EXT_SRC"."COSTOC" AS "COSTOC"
	FROM {{ ref('JDEDWARDS_EXT_F4105') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'