{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F4104',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'STG_JDE_ITEMCROSSREFERENCE_INCR', 'STG_JDE_ITEMCROSSREFERENCE_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' )) AS "ITEMCROSSREFERENCE_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" || 
			'\#' )) AS "ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" || '\#' )) AS "BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_IVAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" || '\#' )) AS "PRODUCT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_IVAN8_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_PRODUCT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."IVAN8" AS "IVAN8"
		, "EXT_SRC"."IVXRT" AS "IVXRT"
		, "EXT_SRC"."IVITM" AS "IVITM"
		, "EXT_SRC"."IVEXDJ" AS "IVEXDJ"
		, "EXT_SRC"."IVCITM" AS "IVCITM"
		, "EXT_SRC"."IVCIRV" AS "IVCIRV"
		, "EXT_SRC"."IVMCU" AS "IVMCU"
		, "EXT_SRC"."IVITM_BK" AS "IVITM_BK"
		, "EXT_SRC"."IVXRT_BK" AS "IVXRT_BK"
		, "EXT_SRC"."IVAN8_BK" AS "IVAN8_BK"
		, "EXT_SRC"."IVCITM_BK" AS "IVCITM_BK"
		, "EXT_SRC"."IVEXDJ_BK" AS "IVEXDJ_BK"
		, "EXT_SRC"."IVCIRV_BK" AS "IVCIRV_BK"
		, "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" AS "IBMCU_FK_ITEMBRANCH_IVITM_BK"
		, "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" AS "IBITM_FK_ITEMBRANCH_IVITM_BK"
		, "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" AS "MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK"
		, "EXT_SRC"."ABAN8_FK_IVAN8_BK" AS "ABAN8_FK_IVAN8_BK"
		, "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" AS "IMITM_FK_ITEMMASTER_IVITM_BK"
		, "EXT_SRC"."IVEFTJ" AS "IVEFTJ"
		, "EXT_SRC"."IVDSC1" AS "IVDSC1"
		, "EXT_SRC"."IVDSC2" AS "IVDSC2"
		, "EXT_SRC"."IVALN" AS "IVALN"
		, "EXT_SRC"."IVLITM" AS "IVLITM"
		, "EXT_SRC"."IVAITM" AS "IVAITM"
		, "EXT_SRC"."IVURCD" AS "IVURCD"
		, "EXT_SRC"."IVURDT" AS "IVURDT"
		, "EXT_SRC"."IVURAT" AS "IVURAT"
		, "EXT_SRC"."IVURAB" AS "IVURAB"
		, "EXT_SRC"."IVURRF" AS "IVURRF"
		, "EXT_SRC"."IVUSER" AS "IVUSER"
		, "EXT_SRC"."IVPID" AS "IVPID"
		, "EXT_SRC"."IVJOBN" AS "IVJOBN"
		, "EXT_SRC"."IVUPMJ" AS "IVUPMJ"
		, "EXT_SRC"."IVTDAY" AS "IVTDAY"
		, "EXT_SRC"."IVRATO" AS "IVRATO"
		, "EXT_SRC"."IVAPSP" AS "IVAPSP"
		, "EXT_SRC"."IVIDEM" AS "IVIDEM"
		, "EXT_SRC"."IVAPSS" AS "IVAPSS"
		, "EXT_SRC"."IVADIND" AS "IVADIND"
		, "EXT_SRC"."IVBPIND" AS "IVBPIND"
		, "EXT_SRC"."IVCARDNO" AS "IVCARDNO"
	FROM {{ ref('JDEDWARDS_EXT_F4104') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' )) AS "ITEMCROSSREFERENCE_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" || 
			'\#' )) AS "ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" || '\#' )) AS "BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_IVAN8_BK" || '\#' )) AS "ACCOUNT_HKEY"
		, UPPER(MD5_HEX( 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" || '\#' )) AS "PRODUCT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" || '\#' ||  "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_ITEMBRANCH_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_BUSINESSUNITMASTER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."ABAN8_FK_IVAN8_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_ACCOUNT_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."IVITM_BK" || '\#' ||  "EXT_SRC"."IVXRT_BK" || '\#' ||  "EXT_SRC"."IVAN8_BK" || '\#' ||  
			"EXT_SRC"."IVCITM_BK" || '\#' ||  "EXT_SRC"."IVEXDJ_BK" || '\#' ||  "EXT_SRC"."IVCIRV_BK" || '\#' || 'JDE' || '\#' || "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" || '\#' )) AS "LNK_ITEMCROSSREFERENCE_PRODUCT_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."IVAN8" AS "IVAN8"
		, "EXT_SRC"."IVXRT" AS "IVXRT"
		, "EXT_SRC"."IVITM" AS "IVITM"
		, "EXT_SRC"."IVEXDJ" AS "IVEXDJ"
		, "EXT_SRC"."IVCITM" AS "IVCITM"
		, "EXT_SRC"."IVCIRV" AS "IVCIRV"
		, "EXT_SRC"."IVMCU" AS "IVMCU"
		, "EXT_SRC"."IVITM_BK" AS "IVITM_BK"
		, "EXT_SRC"."IVXRT_BK" AS "IVXRT_BK"
		, "EXT_SRC"."IVAN8_BK" AS "IVAN8_BK"
		, "EXT_SRC"."IVCITM_BK" AS "IVCITM_BK"
		, "EXT_SRC"."IVEXDJ_BK" AS "IVEXDJ_BK"
		, "EXT_SRC"."IVCIRV_BK" AS "IVCIRV_BK"
		, "EXT_SRC"."IBMCU_FK_ITEMBRANCH_IVITM_BK" AS "IBMCU_FK_ITEMBRANCH_IVITM_BK"
		, "EXT_SRC"."IBITM_FK_ITEMBRANCH_IVITM_BK" AS "IBITM_FK_ITEMBRANCH_IVITM_BK"
		, "EXT_SRC"."MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK" AS "MCMCU_FK_BUSINESSUNITMASTER_IVMCU_BK"
		, "EXT_SRC"."ABAN8_FK_IVAN8_BK" AS "ABAN8_FK_IVAN8_BK"
		, "EXT_SRC"."IMITM_FK_ITEMMASTER_IVITM_BK" AS "IMITM_FK_ITEMMASTER_IVITM_BK"
		, "EXT_SRC"."IVEFTJ" AS "IVEFTJ"
		, "EXT_SRC"."IVDSC1" AS "IVDSC1"
		, "EXT_SRC"."IVDSC2" AS "IVDSC2"
		, "EXT_SRC"."IVALN" AS "IVALN"
		, "EXT_SRC"."IVLITM" AS "IVLITM"
		, "EXT_SRC"."IVAITM" AS "IVAITM"
		, "EXT_SRC"."IVURCD" AS "IVURCD"
		, "EXT_SRC"."IVURDT" AS "IVURDT"
		, "EXT_SRC"."IVURAT" AS "IVURAT"
		, "EXT_SRC"."IVURAB" AS "IVURAB"
		, "EXT_SRC"."IVURRF" AS "IVURRF"
		, "EXT_SRC"."IVUSER" AS "IVUSER"
		, "EXT_SRC"."IVPID" AS "IVPID"
		, "EXT_SRC"."IVJOBN" AS "IVJOBN"
		, "EXT_SRC"."IVUPMJ" AS "IVUPMJ"
		, "EXT_SRC"."IVTDAY" AS "IVTDAY"
		, "EXT_SRC"."IVRATO" AS "IVRATO"
		, "EXT_SRC"."IVAPSP" AS "IVAPSP"
		, "EXT_SRC"."IVIDEM" AS "IVIDEM"
		, "EXT_SRC"."IVAPSS" AS "IVAPSS"
		, "EXT_SRC"."IVADIND" AS "IVADIND"
		, "EXT_SRC"."IVBPIND" AS "IVBPIND"
		, "EXT_SRC"."IVCARDNO" AS "IVCARDNO"
	FROM {{ ref('JDEDWARDS_EXT_F4104') }} "EXT_SRC"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'