{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='OPPORTUNITYLINEITEM',
		schema='SALESFORCE_STG',
		tags=['SALESFORCE', 'STG_SALESFORCE_OPPORTUNITYLINEITEM_INCR', 'STG_SALESFORCE_OPPORTUNITYLINEITEM_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "OPPORTUNITYLINEITEM_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_USER_CREATEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "EXT_SRC"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" AS "ID_FK_OPPORTUNITYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."SORTORDER" AS "SORTORDER"
		, "EXT_SRC"."QUANTITY" AS "QUANTITY"
		, "EXT_SRC"."DISCOUNT" AS "DISCOUNT"
		, "EXT_SRC"."TOTALPRICE" AS "TOTALPRICE"
		, "EXT_SRC"."UNITPRICE" AS "UNITPRICE"
		, "EXT_SRC"."SERVICEDATE" AS "SERVICEDATE"
		, "EXT_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
	FROM {{ ref('SALESFORCE_EXT_OPPORTUNITYLINEITEM') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "OPPORTUNITYLINEITEM_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_OPPORTUNITYLINEITEM_USER_CREATEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "EXT_SRC"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" AS "ID_FK_OPPORTUNITYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."SORTORDER" AS "SORTORDER"
		, "EXT_SRC"."QUANTITY" AS "QUANTITY"
		, "EXT_SRC"."DISCOUNT" AS "DISCOUNT"
		, "EXT_SRC"."TOTALPRICE" AS "TOTALPRICE"
		, "EXT_SRC"."UNITPRICE" AS "UNITPRICE"
		, "EXT_SRC"."SERVICEDATE" AS "SERVICEDATE"
		, "EXT_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
	FROM {{ ref('SALESFORCE_EXT_OPPORTUNITYLINEITEM') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'