{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='CUSTOMER__C',
		schema='SALESFORCE_STG',
		tags=['SALESFORCE', 'STG_SALESFORCE_CUSTOMERC_INCR', 'STG_SALESFORCE_CUSTOMERC_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "CUSTOMER__C_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OWNERID_BK" || '\#' )) AS "USER_OWNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OWNERID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_OWNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_LASTMODIFIEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OWNERID" AS "OWNERID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_OWNERID_BK" AS "ID_FK_OWNERID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
		, "EXT_SRC"."NAME" AS "NAME"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
		, "EXT_SRC"."GENDER__C" AS "GENDER__C"
		, "EXT_SRC"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
		, "EXT_SRC"."PARTNER__C" AS "PARTNER__C"
		, "EXT_SRC"."DEPENDENTS__C" AS "DEPENDENTS__C"
		, "EXT_SRC"."TENURE__C" AS "TENURE__C"
		, "EXT_SRC"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
		, "EXT_SRC"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
		, "EXT_SRC"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
		, "EXT_SRC"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
		, "EXT_SRC"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
		, "EXT_SRC"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
		, "EXT_SRC"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
		, "EXT_SRC"."STREAMING_TV__C" AS "STREAMING_TV__C"
		, "EXT_SRC"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
		, "EXT_SRC"."CONTRACT__C" AS "CONTRACT__C"
		, "EXT_SRC"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
		, "EXT_SRC"."CHURN__C" AS "CHURN__C"
		, "EXT_SRC"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
	FROM {{ ref('SALESFORCE_EXT_CUSTOMER__C') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "CUSTOMER__C_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OWNERID_BK" || '\#' )) AS "USER_OWNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OWNERID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_OWNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_CUSTOMERC_USER_LASTMODIFIEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OWNERID" AS "OWNERID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_OWNERID_BK" AS "ID_FK_OWNERID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
		, "EXT_SRC"."NAME" AS "NAME"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
		, "EXT_SRC"."GENDER__C" AS "GENDER__C"
		, "EXT_SRC"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
		, "EXT_SRC"."PARTNER__C" AS "PARTNER__C"
		, "EXT_SRC"."DEPENDENTS__C" AS "DEPENDENTS__C"
		, "EXT_SRC"."TENURE__C" AS "TENURE__C"
		, "EXT_SRC"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
		, "EXT_SRC"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
		, "EXT_SRC"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
		, "EXT_SRC"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
		, "EXT_SRC"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
		, "EXT_SRC"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
		, "EXT_SRC"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
		, "EXT_SRC"."STREAMING_TV__C" AS "STREAMING_TV__C"
		, "EXT_SRC"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
		, "EXT_SRC"."CONTRACT__C" AS "CONTRACT__C"
		, "EXT_SRC"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
		, "EXT_SRC"."CHURN__C" AS "CHURN__C"
		, "EXT_SRC"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
	FROM {{ ref('SALESFORCE_EXT_CUSTOMER__C') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'