{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='ORDERITEM',
		schema='SALESFORCE_STG',
		tags=['SALESFORCE', 'STG_SALESFORCE_ORDERITEM_INCR', 'STG_SALESFORCE_ORDERITEM_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "ORDERITEM_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_ORDERID_BK" || '\#' )) AS "ORDERS_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" || '\#' )) AS "ORDERITEM_ORIGINALORDERITEMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "LNK_ORDERITEM_PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_ORDERID_BK" || '\#' )) AS "LNK_ORDERITEM_ORDERS_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" || '\#' )) AS "LNK_ORDERITEM_ORDERITEM_ORIGINALORDERITEMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_ORDERITEM_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_ORDERITEM_USER_LASTMODIFIEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."ORDERID" AS "ORDERID"
		, "EXT_SRC"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "EXT_SRC"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "EXT_SRC"."ID_FK_ORDERID_BK" AS "ID_FK_ORDERID_BK"
		, "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" AS "ID_FK_ORIGINALORDERITEMID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
		, "EXT_SRC"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
		, "EXT_SRC"."QUANTITY" AS "QUANTITY"
		, "EXT_SRC"."UNITPRICE" AS "UNITPRICE"
		, "EXT_SRC"."LISTPRICE" AS "LISTPRICE"
		, "EXT_SRC"."SERVICEDATE" AS "SERVICEDATE"
		, "EXT_SRC"."ENDDATE" AS "ENDDATE"
		, "EXT_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
	FROM {{ ref('SALESFORCE_EXT_ORDERITEM') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "ORDERITEM_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_ORDERID_BK" || '\#' )) AS "ORDERS_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" || '\#' )) AS "ORDERITEM_ORIGINALORDERITEMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" || '\#' )) AS "LNK_ORDERITEM_PRICEBOOKENTRY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_ORDERID_BK" || '\#' )) AS "LNK_ORDERITEM_ORDERS_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" || '\#' )) AS "LNK_ORDERITEM_ORDERITEM_ORIGINALORDERITEMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_ORDERITEM_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_ORDERITEM_USER_LASTMODIFIEDBYID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."ORDERID" AS "ORDERID"
		, "EXT_SRC"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "EXT_SRC"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "EXT_SRC"."ID_FK_ORDERID_BK" AS "ID_FK_ORDERID_BK"
		, "EXT_SRC"."ID_FK_ORIGINALORDERITEMID_BK" AS "ID_FK_ORIGINALORDERITEMID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
		, "EXT_SRC"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
		, "EXT_SRC"."QUANTITY" AS "QUANTITY"
		, "EXT_SRC"."UNITPRICE" AS "UNITPRICE"
		, "EXT_SRC"."LISTPRICE" AS "LISTPRICE"
		, "EXT_SRC"."SERVICEDATE" AS "SERVICEDATE"
		, "EXT_SRC"."ENDDATE" AS "ENDDATE"
		, "EXT_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
	FROM {{ ref('SALESFORCE_EXT_ORDERITEM') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'