{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='PARTNER',
		schema='SALESFORCE_STG',
		tags=['SALESFORCE', 'STG_SALESFORCE_PARTNER_INCR', 'STG_SALESFORCE_PARTNER_INIT']
	)
}}
select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "PARTNER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" || '\#' )) AS "ACCOUNT_ACCOUNTFROMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" || '\#' )) AS "PARTNER_REVERSEPARTNERID_HKEY"
		, UPPER(MD5_HEX( 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" || '\#' )) AS "ACCOUNT_ACCOUNTTOID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_PARTNER_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" || '\#' )
			) AS "LNK_PARTNER_ACCOUNT_ACCOUNTFROMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "LNK_PARTNER_OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_PARTNER_USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" || '\#' )) AS "LNK_PARTNER_PARTNER_REVERSEPARTNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" || '\#' )
			) AS "LNK_PARTNER_ACCOUNT_ACCOUNTTOID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "EXT_SRC"."ACCOUNTFROMID" AS "ACCOUNTFROMID"
		, "EXT_SRC"."ACCOUNTTOID" AS "ACCOUNTTOID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."REVERSEPARTNERID" AS "REVERSEPARTNERID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" AS "ID_FK_ACCOUNTFROMID_BK"
		, "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" AS "ID_FK_OPPORTUNITYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" AS "ID_FK_REVERSEPARTNERID_BK"
		, "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" AS "ID_FK_ACCOUNTTOID_BK"
		, "EXT_SRC"."ROLE" AS "ROLE"
		, "EXT_SRC"."ISPRIMARY" AS "ISPRIMARY"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
	FROM {{ ref('SALESFORCE_EXT_PARTNER') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	SELECT 
		  UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' )) AS "PARTNER_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" || '\#' )) AS "ACCOUNT_ACCOUNTFROMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" || '\#' )) AS "PARTNER_REVERSEPARTNERID_HKEY"
		, UPPER(MD5_HEX( 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" || '\#' )) AS "ACCOUNT_ACCOUNTTOID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_CREATEDBYID_BK" || '\#' )) AS "LNK_PARTNER_USER_CREATEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" || '\#' )
			) AS "LNK_PARTNER_ACCOUNT_ACCOUNTFROMID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" || '\#' )) AS "LNK_PARTNER_OPPORTUNITY_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" || '\#' )) AS "LNK_PARTNER_USER_LASTMODIFIEDBYID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" || '\#' )) AS "LNK_PARTNER_PARTNER_REVERSEPARTNERID_HKEY"
		, UPPER(MD5_HEX( "EXT_SRC"."ID_BK" || '\#' || 'SALESFORCE' || '\#' || "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" || '\#' )
			) AS "LNK_PARTNER_ACCOUNT_ACCOUNTTOID_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."ID" AS "ID"
		, "EXT_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "EXT_SRC"."ACCOUNTFROMID" AS "ACCOUNTFROMID"
		, "EXT_SRC"."ACCOUNTTOID" AS "ACCOUNTTOID"
		, "EXT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_SRC"."REVERSEPARTNERID" AS "REVERSEPARTNERID"
		, "EXT_SRC"."ID_BK" AS "ID_BK"
		, "EXT_SRC"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_SRC"."ID_FK_ACCOUNTFROMID_BK" AS "ID_FK_ACCOUNTFROMID_BK"
		, "EXT_SRC"."ID_FK_OPPORTUNITYID_BK" AS "ID_FK_OPPORTUNITYID_BK"
		, "EXT_SRC"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_SRC"."ID_FK_REVERSEPARTNERID_BK" AS "ID_FK_REVERSEPARTNERID_BK"
		, "EXT_SRC"."ID_FK_ACCOUNTTOID_BK" AS "ID_FK_ACCOUNTTOID_BK"
		, "EXT_SRC"."ROLE" AS "ROLE"
		, "EXT_SRC"."ISPRIMARY" AS "ISPRIMARY"
		, "EXT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_SRC"."ISDELETED" AS "ISDELETED"
	FROM {{ ref('SALESFORCE_EXT_PARTNER') }} "EXT_SRC"
	INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'