{{
	config(
		materialized='view',
		alias='VW_F01151',
		schema='JDEDWARDS_DFV',
		tags=['view', 'JDEDWARDS', 'SRC_JDE_EMAIL_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('JDEDWARDS_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."EAAN8" AS "EAAN8"
			, "CDC_SRC"."EAIDLN" AS "EAIDLN"
			, "CDC_SRC"."EARCK7" AS "EARCK7"
			, "CDC_SRC"."EAETP" AS "EAETP"
			, "CDC_SRC"."EAEMAL" AS "EAEMAL"
			, "CDC_SRC"."EAUSER" AS "EAUSER"
			, "CDC_SRC"."EAPID" AS "EAPID"
			, "CDC_SRC"."EAUPMJ" AS "EAUPMJ"
			, "CDC_SRC"."EAJOBN" AS "EAJOBN"
			, "CDC_SRC"."EAUPMT" AS "EAUPMT"
			, "CDC_SRC"."EAEHIER" AS "EAEHIER"
			, "CDC_SRC"."EAEFOR" AS "EAEFOR"
			, "CDC_SRC"."EAECLASS" AS "EAECLASS"
			, "CDC_SRC"."EACFNO1" AS "EACFNO1"
			, "CDC_SRC"."EAGEN1" AS "EAGEN1"
			, "CDC_SRC"."EAFALGE" AS "EAFALGE"
			, "CDC_SRC"."EASYNCS" AS "EASYNCS"
			, "CDC_SRC"."EACAAD" AS "EACAAD"
		FROM {{ source('JDEDWARDS_CDC', 'CDC_F01151') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."EAAN8" AS "EAAN8"
			, "DELTA_VIEW_FILTER"."EAIDLN" AS "EAIDLN"
			, "DELTA_VIEW_FILTER"."EARCK7" AS "EARCK7"
			, "DELTA_VIEW_FILTER"."EAETP" AS "EAETP"
			, "DELTA_VIEW_FILTER"."EAEMAL" AS "EAEMAL"
			, "DELTA_VIEW_FILTER"."EAUSER" AS "EAUSER"
			, "DELTA_VIEW_FILTER"."EAPID" AS "EAPID"
			, "DELTA_VIEW_FILTER"."EAUPMJ" AS "EAUPMJ"
			, "DELTA_VIEW_FILTER"."EAJOBN" AS "EAJOBN"
			, "DELTA_VIEW_FILTER"."EAUPMT" AS "EAUPMT"
			, "DELTA_VIEW_FILTER"."EAEHIER" AS "EAEHIER"
			, "DELTA_VIEW_FILTER"."EAEFOR" AS "EAEFOR"
			, "DELTA_VIEW_FILTER"."EAECLASS" AS "EAECLASS"
			, "DELTA_VIEW_FILTER"."EACFNO1" AS "EACFNO1"
			, "DELTA_VIEW_FILTER"."EAGEN1" AS "EAGEN1"
			, "DELTA_VIEW_FILTER"."EAFALGE" AS "EAFALGE"
			, "DELTA_VIEW_FILTER"."EASYNCS" AS "EASYNCS"
			, "DELTA_VIEW_FILTER"."EACAAD" AS "EACAAD"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."EAAN8", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EAAN8"
			, COALESCE("DELTA_VIEW"."EAIDLN", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EAIDLN"
			, COALESCE("DELTA_VIEW"."EARCK7", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EARCK7"
			, "DELTA_VIEW"."EAETP" AS "EAETP"
			, "DELTA_VIEW"."EAEMAL" AS "EAEMAL"
			, "DELTA_VIEW"."EAUSER" AS "EAUSER"
			, "DELTA_VIEW"."EAPID" AS "EAPID"
			, "DELTA_VIEW"."EAUPMJ" AS "EAUPMJ"
			, "DELTA_VIEW"."EAJOBN" AS "EAJOBN"
			, "DELTA_VIEW"."EAUPMT" AS "EAUPMT"
			, "DELTA_VIEW"."EAEHIER" AS "EAEHIER"
			, "DELTA_VIEW"."EAEFOR" AS "EAEFOR"
			, "DELTA_VIEW"."EAECLASS" AS "EAECLASS"
			, "DELTA_VIEW"."EACFNO1" AS "EACFNO1"
			, "DELTA_VIEW"."EAGEN1" AS "EAGEN1"
			, "DELTA_VIEW"."EAFALGE" AS "EAFALGE"
			, "DELTA_VIEW"."EASYNCS" AS "EASYNCS"
			, "DELTA_VIEW"."EACAAD" AS "EACAAD"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."EAAN8" AS "EAAN8"
		, "PREPJOINBK"."EAIDLN" AS "EAIDLN"
		, "PREPJOINBK"."EARCK7" AS "EARCK7"
		, "PREPJOINBK"."EAETP" AS "EAETP"
		, "PREPJOINBK"."EAEMAL" AS "EAEMAL"
		, "PREPJOINBK"."EAUSER" AS "EAUSER"
		, "PREPJOINBK"."EAPID" AS "EAPID"
		, "PREPJOINBK"."EAUPMJ" AS "EAUPMJ"
		, "PREPJOINBK"."EAJOBN" AS "EAJOBN"
		, "PREPJOINBK"."EAUPMT" AS "EAUPMT"
		, "PREPJOINBK"."EAEHIER" AS "EAEHIER"
		, "PREPJOINBK"."EAEFOR" AS "EAEFOR"
		, "PREPJOINBK"."EAECLASS" AS "EAECLASS"
		, "PREPJOINBK"."EACFNO1" AS "EACFNO1"
		, "PREPJOINBK"."EAGEN1" AS "EAGEN1"
		, "PREPJOINBK"."EAFALGE" AS "EAFALGE"
		, "PREPJOINBK"."EASYNCS" AS "EASYNCS"
		, "PREPJOINBK"."EACAAD" AS "EACAAD"
	FROM "PREPJOINBK" "PREPJOINBK"
