{{
	config(
		materialized='view',
		alias='VW_F0115',
		schema='JDEDWARDS_DFV',
		tags=['view', 'JDEDWARDS', 'SRC_JDE_PHONE_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('JDEDWARDS_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."WPAN8" AS "WPAN8"
			, "CDC_SRC"."WPIDLN" AS "WPIDLN"
			, "CDC_SRC"."WPRCK7" AS "WPRCK7"
			, "CDC_SRC"."WPCNLN" AS "WPCNLN"
			, "CDC_SRC"."WPPHTP" AS "WPPHTP"
			, "CDC_SRC"."WPAR1" AS "WPAR1"
			, "CDC_SRC"."WPPH1" AS "WPPH1"
			, "CDC_SRC"."WPUSER" AS "WPUSER"
			, "CDC_SRC"."WPPID" AS "WPPID"
			, "CDC_SRC"."WPUPMJ" AS "WPUPMJ"
			, "CDC_SRC"."WPJOBN" AS "WPJOBN"
			, "CDC_SRC"."WPUPMT" AS "WPUPMT"
			, "CDC_SRC"."WPCFNO1" AS "WPCFNO1"
			, "CDC_SRC"."WPGEN1" AS "WPGEN1"
			, "CDC_SRC"."WPFALGE" AS "WPFALGE"
			, "CDC_SRC"."WPSYNCS" AS "WPSYNCS"
			, "CDC_SRC"."WPCAAD" AS "WPCAAD"
		FROM {{ source('JDEDWARDS_CDC', 'CDC_F0115') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."WPAN8" AS "WPAN8"
			, "DELTA_VIEW_FILTER"."WPIDLN" AS "WPIDLN"
			, "DELTA_VIEW_FILTER"."WPRCK7" AS "WPRCK7"
			, "DELTA_VIEW_FILTER"."WPCNLN" AS "WPCNLN"
			, "DELTA_VIEW_FILTER"."WPPHTP" AS "WPPHTP"
			, "DELTA_VIEW_FILTER"."WPAR1" AS "WPAR1"
			, "DELTA_VIEW_FILTER"."WPPH1" AS "WPPH1"
			, "DELTA_VIEW_FILTER"."WPUSER" AS "WPUSER"
			, "DELTA_VIEW_FILTER"."WPPID" AS "WPPID"
			, "DELTA_VIEW_FILTER"."WPUPMJ" AS "WPUPMJ"
			, "DELTA_VIEW_FILTER"."WPJOBN" AS "WPJOBN"
			, "DELTA_VIEW_FILTER"."WPUPMT" AS "WPUPMT"
			, "DELTA_VIEW_FILTER"."WPCFNO1" AS "WPCFNO1"
			, "DELTA_VIEW_FILTER"."WPGEN1" AS "WPGEN1"
			, "DELTA_VIEW_FILTER"."WPFALGE" AS "WPFALGE"
			, "DELTA_VIEW_FILTER"."WPSYNCS" AS "WPSYNCS"
			, "DELTA_VIEW_FILTER"."WPCAAD" AS "WPCAAD"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."WPAN8", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "WPAN8"
			, COALESCE("DELTA_VIEW"."WPIDLN", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "WPIDLN"
			, COALESCE("DELTA_VIEW"."WPRCK7", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "WPRCK7"
			, COALESCE("DELTA_VIEW"."WPCNLN", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "WPCNLN"
			, "DELTA_VIEW"."WPPHTP" AS "WPPHTP"
			, "DELTA_VIEW"."WPAR1" AS "WPAR1"
			, "DELTA_VIEW"."WPPH1" AS "WPPH1"
			, "DELTA_VIEW"."WPUSER" AS "WPUSER"
			, "DELTA_VIEW"."WPPID" AS "WPPID"
			, "DELTA_VIEW"."WPUPMJ" AS "WPUPMJ"
			, "DELTA_VIEW"."WPJOBN" AS "WPJOBN"
			, "DELTA_VIEW"."WPUPMT" AS "WPUPMT"
			, "DELTA_VIEW"."WPCFNO1" AS "WPCFNO1"
			, "DELTA_VIEW"."WPGEN1" AS "WPGEN1"
			, "DELTA_VIEW"."WPFALGE" AS "WPFALGE"
			, "DELTA_VIEW"."WPSYNCS" AS "WPSYNCS"
			, "DELTA_VIEW"."WPCAAD" AS "WPCAAD"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."WPAN8" AS "WPAN8"
		, "PREPJOINBK"."WPIDLN" AS "WPIDLN"
		, "PREPJOINBK"."WPRCK7" AS "WPRCK7"
		, "PREPJOINBK"."WPCNLN" AS "WPCNLN"
		, "PREPJOINBK"."WPPHTP" AS "WPPHTP"
		, "PREPJOINBK"."WPAR1" AS "WPAR1"
		, "PREPJOINBK"."WPPH1" AS "WPPH1"
		, "PREPJOINBK"."WPUSER" AS "WPUSER"
		, "PREPJOINBK"."WPPID" AS "WPPID"
		, "PREPJOINBK"."WPUPMJ" AS "WPUPMJ"
		, "PREPJOINBK"."WPJOBN" AS "WPJOBN"
		, "PREPJOINBK"."WPUPMT" AS "WPUPMT"
		, "PREPJOINBK"."WPCFNO1" AS "WPCFNO1"
		, "PREPJOINBK"."WPGEN1" AS "WPGEN1"
		, "PREPJOINBK"."WPFALGE" AS "WPFALGE"
		, "PREPJOINBK"."WPSYNCS" AS "WPSYNCS"
		, "PREPJOINBK"."WPCAAD" AS "WPCAAD"
	FROM "PREPJOINBK" "PREPJOINBK"
