{{
	config(
		materialized='view',
		alias='VW_F0116',
		schema='JDEDWARDS_DFV',
		tags=['view', 'JDEDWARDS', 'SRC_JDE_ADDRESS_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('JDEDWARDS_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."ALAN8" AS "ALAN8"
			, "CDC_SRC"."ALEFTB" AS "ALEFTB"
			, "CDC_SRC"."ALEFTF" AS "ALEFTF"
			, "CDC_SRC"."ALADD1" AS "ALADD1"
			, "CDC_SRC"."ALADD2" AS "ALADD2"
			, "CDC_SRC"."ALADD3" AS "ALADD3"
			, "CDC_SRC"."ALADD4" AS "ALADD4"
			, "CDC_SRC"."ALADDZ" AS "ALADDZ"
			, "CDC_SRC"."ALCTY1" AS "ALCTY1"
			, "CDC_SRC"."ALCOUN" AS "ALCOUN"
			, "CDC_SRC"."ALADDS" AS "ALADDS"
			, "CDC_SRC"."ALCRTE" AS "ALCRTE"
			, "CDC_SRC"."ALBKML" AS "ALBKML"
			, "CDC_SRC"."ALCTR" AS "ALCTR"
			, "CDC_SRC"."ALUSER" AS "ALUSER"
			, "CDC_SRC"."ALPID" AS "ALPID"
			, "CDC_SRC"."ALUPMJ" AS "ALUPMJ"
			, "CDC_SRC"."ALJOBN" AS "ALJOBN"
			, "CDC_SRC"."ALUPMT" AS "ALUPMT"
			, "CDC_SRC"."ALSYNCS" AS "ALSYNCS"
			, "CDC_SRC"."ALCAAD" AS "ALCAAD"
		FROM {{ source('JDEDWARDS_CDC', 'CDC_F0116') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."ALAN8" AS "ALAN8"
			, "DELTA_VIEW_FILTER"."ALEFTB" AS "ALEFTB"
			, "DELTA_VIEW_FILTER"."ALEFTF" AS "ALEFTF"
			, "DELTA_VIEW_FILTER"."ALADD1" AS "ALADD1"
			, "DELTA_VIEW_FILTER"."ALADD2" AS "ALADD2"
			, "DELTA_VIEW_FILTER"."ALADD3" AS "ALADD3"
			, "DELTA_VIEW_FILTER"."ALADD4" AS "ALADD4"
			, "DELTA_VIEW_FILTER"."ALADDZ" AS "ALADDZ"
			, "DELTA_VIEW_FILTER"."ALCTY1" AS "ALCTY1"
			, "DELTA_VIEW_FILTER"."ALCOUN" AS "ALCOUN"
			, "DELTA_VIEW_FILTER"."ALADDS" AS "ALADDS"
			, "DELTA_VIEW_FILTER"."ALCRTE" AS "ALCRTE"
			, "DELTA_VIEW_FILTER"."ALBKML" AS "ALBKML"
			, "DELTA_VIEW_FILTER"."ALCTR" AS "ALCTR"
			, "DELTA_VIEW_FILTER"."ALUSER" AS "ALUSER"
			, "DELTA_VIEW_FILTER"."ALPID" AS "ALPID"
			, "DELTA_VIEW_FILTER"."ALUPMJ" AS "ALUPMJ"
			, "DELTA_VIEW_FILTER"."ALJOBN" AS "ALJOBN"
			, "DELTA_VIEW_FILTER"."ALUPMT" AS "ALUPMT"
			, "DELTA_VIEW_FILTER"."ALSYNCS" AS "ALSYNCS"
			, "DELTA_VIEW_FILTER"."ALCAAD" AS "ALCAAD"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."ALAN8", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "ALAN8"
			, COALESCE("DELTA_VIEW"."ALEFTB", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "ALEFTB"
			, "DELTA_VIEW"."ALEFTF" AS "ALEFTF"
			, "DELTA_VIEW"."ALADD1" AS "ALADD1"
			, "DELTA_VIEW"."ALADD2" AS "ALADD2"
			, "DELTA_VIEW"."ALADD3" AS "ALADD3"
			, "DELTA_VIEW"."ALADD4" AS "ALADD4"
			, "DELTA_VIEW"."ALADDZ" AS "ALADDZ"
			, "DELTA_VIEW"."ALCTY1" AS "ALCTY1"
			, "DELTA_VIEW"."ALCOUN" AS "ALCOUN"
			, "DELTA_VIEW"."ALADDS" AS "ALADDS"
			, "DELTA_VIEW"."ALCRTE" AS "ALCRTE"
			, "DELTA_VIEW"."ALBKML" AS "ALBKML"
			, "DELTA_VIEW"."ALCTR" AS "ALCTR"
			, "DELTA_VIEW"."ALUSER" AS "ALUSER"
			, "DELTA_VIEW"."ALPID" AS "ALPID"
			, "DELTA_VIEW"."ALUPMJ" AS "ALUPMJ"
			, "DELTA_VIEW"."ALJOBN" AS "ALJOBN"
			, "DELTA_VIEW"."ALUPMT" AS "ALUPMT"
			, "DELTA_VIEW"."ALSYNCS" AS "ALSYNCS"
			, "DELTA_VIEW"."ALCAAD" AS "ALCAAD"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."ALAN8" AS "ALAN8"
		, "PREPJOINBK"."ALEFTB" AS "ALEFTB"
		, "PREPJOINBK"."ALEFTF" AS "ALEFTF"
		, "PREPJOINBK"."ALADD1" AS "ALADD1"
		, "PREPJOINBK"."ALADD2" AS "ALADD2"
		, "PREPJOINBK"."ALADD3" AS "ALADD3"
		, "PREPJOINBK"."ALADD4" AS "ALADD4"
		, "PREPJOINBK"."ALADDZ" AS "ALADDZ"
		, "PREPJOINBK"."ALCTY1" AS "ALCTY1"
		, "PREPJOINBK"."ALCOUN" AS "ALCOUN"
		, "PREPJOINBK"."ALADDS" AS "ALADDS"
		, "PREPJOINBK"."ALCRTE" AS "ALCRTE"
		, "PREPJOINBK"."ALBKML" AS "ALBKML"
		, "PREPJOINBK"."ALCTR" AS "ALCTR"
		, "PREPJOINBK"."ALUSER" AS "ALUSER"
		, "PREPJOINBK"."ALPID" AS "ALPID"
		, "PREPJOINBK"."ALUPMJ" AS "ALUPMJ"
		, "PREPJOINBK"."ALJOBN" AS "ALJOBN"
		, "PREPJOINBK"."ALUPMT" AS "ALUPMT"
		, "PREPJOINBK"."ALSYNCS" AS "ALSYNCS"
		, "PREPJOINBK"."ALCAAD" AS "ALCAAD"
	FROM "PREPJOINBK" "PREPJOINBK"
