{{
	config(
		materialized='view',
		alias='VW_F800010',
		schema='JDEDWARDS_DFV',
		tags=['view', 'JDEDWARDS', 'SRC_JDE_TIME_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('JDEDWARDS_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."TDJDATE" AS "TDJDATE"
			, "CDC_SRC"."TDYRMNDY" AS "TDYRMNDY"
			, "CDC_SRC"."TDDAYNMBR" AS "TDDAYNMBR"
			, "CDC_SRC"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "CDC_SRC"."TDCALQTR" AS "TDCALQTR"
			, "CDC_SRC"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "CDC_SRC"."TDYEARNMBR" AS "TDYEARNMBR"
			, "CDC_SRC"."TDWKNMBR" AS "TDWKNMBR"
			, "CDC_SRC"."TDDAYTEXT" AS "TDDAYTEXT"
			, "CDC_SRC"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "CDC_SRC"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "CDC_SRC"."TDFISPER" AS "TDFISPER"
			, "CDC_SRC"."TDFISQTR" AS "TDFISQTR"
			, "CDC_SRC"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "CDC_SRC"."TDFISYEAR" AS "TDFISYEAR"
			, "CDC_SRC"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "CDC_SRC"."TDLSTDAYFP" AS "TDLSTDAYFP"
		FROM {{ source('JDEDWARDS_CDC', 'CDC_F800010') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."TDJDATE" AS "TDJDATE"
			, "DELTA_VIEW_FILTER"."TDYRMNDY" AS "TDYRMNDY"
			, "DELTA_VIEW_FILTER"."TDDAYNMBR" AS "TDDAYNMBR"
			, "DELTA_VIEW_FILTER"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "DELTA_VIEW_FILTER"."TDCALQTR" AS "TDCALQTR"
			, "DELTA_VIEW_FILTER"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "DELTA_VIEW_FILTER"."TDYEARNMBR" AS "TDYEARNMBR"
			, "DELTA_VIEW_FILTER"."TDWKNMBR" AS "TDWKNMBR"
			, "DELTA_VIEW_FILTER"."TDDAYTEXT" AS "TDDAYTEXT"
			, "DELTA_VIEW_FILTER"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "DELTA_VIEW_FILTER"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "DELTA_VIEW_FILTER"."TDFISPER" AS "TDFISPER"
			, "DELTA_VIEW_FILTER"."TDFISQTR" AS "TDFISQTR"
			, "DELTA_VIEW_FILTER"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "DELTA_VIEW_FILTER"."TDFISYEAR" AS "TDFISYEAR"
			, "DELTA_VIEW_FILTER"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "DELTA_VIEW_FILTER"."TDLSTDAYFP" AS "TDLSTDAYFP"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."TDJDATE", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "TDJDATE"
			, "DELTA_VIEW"."TDYRMNDY" AS "TDYRMNDY"
			, "DELTA_VIEW"."TDDAYNMBR" AS "TDDAYNMBR"
			, "DELTA_VIEW"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "DELTA_VIEW"."TDCALQTR" AS "TDCALQTR"
			, "DELTA_VIEW"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "DELTA_VIEW"."TDYEARNMBR" AS "TDYEARNMBR"
			, "DELTA_VIEW"."TDWKNMBR" AS "TDWKNMBR"
			, "DELTA_VIEW"."TDDAYTEXT" AS "TDDAYTEXT"
			, "DELTA_VIEW"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "DELTA_VIEW"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "DELTA_VIEW"."TDFISPER" AS "TDFISPER"
			, "DELTA_VIEW"."TDFISQTR" AS "TDFISQTR"
			, "DELTA_VIEW"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "DELTA_VIEW"."TDFISYEAR" AS "TDFISYEAR"
			, "DELTA_VIEW"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "DELTA_VIEW"."TDLSTDAYFP" AS "TDLSTDAYFP"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."TDJDATE" AS "TDJDATE"
		, "PREPJOINBK"."TDYRMNDY" AS "TDYRMNDY"
		, "PREPJOINBK"."TDDAYNMBR" AS "TDDAYNMBR"
		, "PREPJOINBK"."TDMNTHNMBR" AS "TDMNTHNMBR"
		, "PREPJOINBK"."TDCALQTR" AS "TDCALQTR"
		, "PREPJOINBK"."TDCQTRNMBR" AS "TDCQTRNMBR"
		, "PREPJOINBK"."TDYEARNMBR" AS "TDYEARNMBR"
		, "PREPJOINBK"."TDWKNMBR" AS "TDWKNMBR"
		, "PREPJOINBK"."TDDAYTEXT" AS "TDDAYTEXT"
		, "PREPJOINBK"."TDMNTHTEXT" AS "TDMNTHTEXT"
		, "PREPJOINBK"."TDLSTDAYMN" AS "TDLSTDAYMN"
		, "PREPJOINBK"."TDFISPER" AS "TDFISPER"
		, "PREPJOINBK"."TDFISQTR" AS "TDFISQTR"
		, "PREPJOINBK"."TDFQTRNMBR" AS "TDFQTRNMBR"
		, "PREPJOINBK"."TDFISYEAR" AS "TDFISYEAR"
		, "PREPJOINBK"."TDFSPRTEXT" AS "TDFSPRTEXT"
		, "PREPJOINBK"."TDLSTDAYFP" AS "TDLSTDAYFP"
	FROM "PREPJOINBK" "PREPJOINBK"
