{{
	config(
		materialized='view',
		alias='VW_PARTNER',
		schema='SALESFORCE_DFV',
		tags=['view', 'SALESFORCE', 'SRC_SALESFORCE_PARTNER_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('SALESFORCE_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."ID" AS "ID"
			, "CDC_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
			, "CDC_SRC"."ACCOUNTFROMID" AS "ACCOUNTFROMID"
			, "CDC_SRC"."ACCOUNTTOID" AS "ACCOUNTTOID"
			, "CDC_SRC"."CREATEDBYID" AS "CREATEDBYID"
			, "CDC_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "CDC_SRC"."REVERSEPARTNERID" AS "REVERSEPARTNERID"
			, "CDC_SRC"."ROLE" AS "ROLE"
			, "CDC_SRC"."ISPRIMARY" AS "ISPRIMARY"
			, "CDC_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "CDC_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "CDC_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "CDC_SRC"."ISDELETED" AS "ISDELETED"
		FROM {{ source('SALESFORCE_CDC', 'CDC_PARTNER') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."ID" AS "ID"
			, "DELTA_VIEW_FILTER"."OPPORTUNITYID" AS "OPPORTUNITYID"
			, "DELTA_VIEW_FILTER"."ACCOUNTFROMID" AS "ACCOUNTFROMID"
			, "DELTA_VIEW_FILTER"."ACCOUNTTOID" AS "ACCOUNTTOID"
			, "DELTA_VIEW_FILTER"."CREATEDBYID" AS "CREATEDBYID"
			, "DELTA_VIEW_FILTER"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "DELTA_VIEW_FILTER"."REVERSEPARTNERID" AS "REVERSEPARTNERID"
			, "DELTA_VIEW_FILTER"."ROLE" AS "ROLE"
			, "DELTA_VIEW_FILTER"."ISPRIMARY" AS "ISPRIMARY"
			, "DELTA_VIEW_FILTER"."CREATEDDATE" AS "CREATEDDATE"
			, "DELTA_VIEW_FILTER"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "DELTA_VIEW_FILTER"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "DELTA_VIEW_FILTER"."ISDELETED" AS "ISDELETED"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."ID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ID"
			, COALESCE("DELTA_VIEW"."CREATEDBYID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "CREATEDBYID"
			, COALESCE("DELTA_VIEW"."ACCOUNTFROMID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ACCOUNTFROMID"
			, COALESCE("DELTA_VIEW"."OPPORTUNITYID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "OPPORTUNITYID"
			, COALESCE("DELTA_VIEW"."LASTMODIFIEDBYID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "LASTMODIFIEDBYID"
			, COALESCE("DELTA_VIEW"."REVERSEPARTNERID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "REVERSEPARTNERID"
			, COALESCE("DELTA_VIEW"."ACCOUNTTOID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ACCOUNTTOID"
			, "DELTA_VIEW"."ROLE" AS "ROLE"
			, "DELTA_VIEW"."ISPRIMARY" AS "ISPRIMARY"
			, "DELTA_VIEW"."CREATEDDATE" AS "CREATEDDATE"
			, "DELTA_VIEW"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "DELTA_VIEW"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "DELTA_VIEW"."ISDELETED" AS "ISDELETED"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."ID" AS "ID"
		, "PREPJOINBK"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "PREPJOINBK"."ACCOUNTFROMID" AS "ACCOUNTFROMID"
		, "PREPJOINBK"."ACCOUNTTOID" AS "ACCOUNTTOID"
		, "PREPJOINBK"."CREATEDBYID" AS "CREATEDBYID"
		, "PREPJOINBK"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "PREPJOINBK"."REVERSEPARTNERID" AS "REVERSEPARTNERID"
		, "PREPJOINBK"."ROLE" AS "ROLE"
		, "PREPJOINBK"."ISPRIMARY" AS "ISPRIMARY"
		, "PREPJOINBK"."CREATEDDATE" AS "CREATEDDATE"
		, "PREPJOINBK"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "PREPJOINBK"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "PREPJOINBK"."ISDELETED" AS "ISDELETED"
	FROM "PREPJOINBK" "PREPJOINBK"
