{{
	config(
		materialized='view',
		alias='VW_PRODUCT2',
		schema='SALESFORCE_DFV',
		tags=['view', 'SALESFORCE', 'SRC_SALESFORCE_PRODUCT2_TDFV_INCR']
	)
}}
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM {{ source('SALESFORCE_MTD', 'FMC_LOADING_WINDOW_TABLE') }} "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CDC_SRC"."JRN_FLAG" AS "JRN_FLAG"
			, TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."ID" AS "ID"
			, "CDC_SRC"."CREATEDBYID" AS "CREATEDBYID"
			, "CDC_SRC"."NAME" AS "NAME"
			, "CDC_SRC"."PRODUCTCODE" AS "PRODUCTCODE"
			, "CDC_SRC"."DESCRIPTION" AS "DESCRIPTION"
			, "CDC_SRC"."ISACTIVE" AS "ISACTIVE"
			, "CDC_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "CDC_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "CDC_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "CDC_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "CDC_SRC"."FAMILY" AS "FAMILY"
			, "CDC_SRC"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "CDC_SRC"."EXTERNALID" AS "EXTERNALID"
			, "CDC_SRC"."DISPLAYURL" AS "DISPLAYURL"
			, "CDC_SRC"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "CDC_SRC"."ISDELETED" AS "ISDELETED"
			, "CDC_SRC"."ISARCHIVED" AS "ISARCHIVED"
			, "CDC_SRC"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		FROM {{ source('SALESFORCE_CDC', 'CDC_PRODUCT2') }} "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."ID" AS "ID"
			, "DELTA_VIEW_FILTER"."CREATEDBYID" AS "CREATEDBYID"
			, "DELTA_VIEW_FILTER"."NAME" AS "NAME"
			, "DELTA_VIEW_FILTER"."PRODUCTCODE" AS "PRODUCTCODE"
			, "DELTA_VIEW_FILTER"."DESCRIPTION" AS "DESCRIPTION"
			, "DELTA_VIEW_FILTER"."ISACTIVE" AS "ISACTIVE"
			, "DELTA_VIEW_FILTER"."CREATEDDATE" AS "CREATEDDATE"
			, "DELTA_VIEW_FILTER"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "DELTA_VIEW_FILTER"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "DELTA_VIEW_FILTER"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "DELTA_VIEW_FILTER"."FAMILY" AS "FAMILY"
			, "DELTA_VIEW_FILTER"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "DELTA_VIEW_FILTER"."EXTERNALID" AS "EXTERNALID"
			, "DELTA_VIEW_FILTER"."DISPLAYURL" AS "DISPLAYURL"
			, "DELTA_VIEW_FILTER"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "DELTA_VIEW_FILTER"."ISDELETED" AS "ISDELETED"
			, "DELTA_VIEW_FILTER"."ISARCHIVED" AS "ISARCHIVED"
			, "DELTA_VIEW_FILTER"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."JRN_FLAG" AS "JRN_FLAG"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."ID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ID"
			, COALESCE("DELTA_VIEW"."CREATEDBYID","MEX_BK_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "CREATEDBYID"
			, "DELTA_VIEW"."NAME" AS "NAME"
			, "DELTA_VIEW"."PRODUCTCODE" AS "PRODUCTCODE"
			, "DELTA_VIEW"."DESCRIPTION" AS "DESCRIPTION"
			, "DELTA_VIEW"."ISACTIVE" AS "ISACTIVE"
			, "DELTA_VIEW"."CREATEDDATE" AS "CREATEDDATE"
			, "DELTA_VIEW"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "DELTA_VIEW"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "DELTA_VIEW"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "DELTA_VIEW"."FAMILY" AS "FAMILY"
			, "DELTA_VIEW"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "DELTA_VIEW"."EXTERNALID" AS "EXTERNALID"
			, "DELTA_VIEW"."DISPLAYURL" AS "DISPLAYURL"
			, "DELTA_VIEW"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "DELTA_VIEW"."ISDELETED" AS "ISDELETED"
			, "DELTA_VIEW"."ISARCHIVED" AS "ISARCHIVED"
			, "DELTA_VIEW"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."JRN_FLAG" AS "JRN_FLAG"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."ID" AS "ID"
		, "PREPJOINBK"."CREATEDBYID" AS "CREATEDBYID"
		, "PREPJOINBK"."NAME" AS "NAME"
		, "PREPJOINBK"."PRODUCTCODE" AS "PRODUCTCODE"
		, "PREPJOINBK"."DESCRIPTION" AS "DESCRIPTION"
		, "PREPJOINBK"."ISACTIVE" AS "ISACTIVE"
		, "PREPJOINBK"."CREATEDDATE" AS "CREATEDDATE"
		, "PREPJOINBK"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "PREPJOINBK"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "PREPJOINBK"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "PREPJOINBK"."FAMILY" AS "FAMILY"
		, "PREPJOINBK"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
		, "PREPJOINBK"."EXTERNALID" AS "EXTERNALID"
		, "PREPJOINBK"."DISPLAYURL" AS "DISPLAYURL"
		, "PREPJOINBK"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
		, "PREPJOINBK"."ISDELETED" AS "ISDELETED"
		, "PREPJOINBK"."ISARCHIVED" AS "ISARCHIVED"
		, "PREPJOINBK"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
	FROM "PREPJOINBK" "PREPJOINBK"
