{{
	config(
		materialized='view',
		alias='SAT_JDE_EMAIL',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_EMAIL_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."EMAIL_HKEY" AS "EMAIL_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."EAAN8" AS "EAAN8"
		, "DVT_SRC"."EAIDLN" AS "EAIDLN"
		, "DVT_SRC"."EARCK7" AS "EARCK7"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."EAETP" AS "EAETP"
		, "DVT_SRC"."EAEMAL" AS "EAEMAL"
		, "DVT_SRC"."EAUSER" AS "EAUSER"
		, "DVT_SRC"."EAPID" AS "EAPID"
		, "DVT_SRC"."EAUPMJ" AS "EAUPMJ"
		, "DVT_SRC"."EAJOBN" AS "EAJOBN"
		, "DVT_SRC"."EAUPMT" AS "EAUPMT"
		, "DVT_SRC"."EAEHIER" AS "EAEHIER"
		, "DVT_SRC"."EAEFOR" AS "EAEFOR"
		, "DVT_SRC"."EAECLASS" AS "EAECLASS"
		, "DVT_SRC"."EACFNO1" AS "EACFNO1"
		, "DVT_SRC"."EAGEN1" AS "EAGEN1"
		, "DVT_SRC"."EAFALGE" AS "EAFALGE"
		, "DVT_SRC"."EASYNCS" AS "EASYNCS"
		, "DVT_SRC"."EACAAD" AS "EACAAD"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_EMAIL') }} "DVT_SRC"
