{{
	config(
		materialized='view',
		alias='SAT_SALESFORCE_OPPORTUNITYCOMPETITOR',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_SALESFORCE_OPPORTUNITYCOMPETITOR_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."OPPORTUNITYCOMPETITOR_HKEY" AS "OPPORTUNITYCOMPETITOR_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ID" AS "ID"
		, "DVT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "DVT_SRC"."OPPORTUNITYID" AS "OPPORTUNITYID"
		, "DVT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."COMPETITORNAME" AS "COMPETITORNAME"
		, "DVT_SRC"."STRENGTHS" AS "STRENGTHS"
		, "DVT_SRC"."WEAKNESSES" AS "WEAKNESSES"
		, "DVT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "DVT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "DVT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "DVT_SRC"."ISDELETED" AS "ISDELETED"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_SALESFORCE_OPPORTUNITYCOMPETITOR') }} "DVT_SRC"
