{{
	config(
		materialized='view',
		alias='LNK_SODETAILHIST_COMPANY',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_SODETAILHIST_COMPANY_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."SALESORDERDETAILHISTORY_HKEY" AS "SALESORDERDETAILHISTORY_HKEY"
		, "DVT_SRC"."LNK_SODETAILHIST_COMPANY_HKEY" AS "LNK_SODETAILHIST_COMPANY_HKEY"
		, "DVT_SRC"."COMPANY_HKEY" AS "COMPANY_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_SODETAILHIST_COMPANY') }} "DVT_SRC"
