{{
	config(
		materialized='view',
		alias='LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."OPPORTUNITYLINEITEM_HKEY" AS "OPPORTUNITYLINEITEM_HKEY"
		, "DVT_SRC"."LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY_HKEY" AS "LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY_HKEY"
		, "DVT_SRC"."PRICEBOOKENTRY_HKEY" AS "PRICEBOOKENTRY_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_OPPORTUNITYLINEITEM_PRICEBOOKENTRY') }} "DVT_SRC"
