{{
	config(
		materialized='view',
		alias='LNK_OPPORTUNITYCONTACTROLE_CONTACT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_OPPORTUNITYCONTACTROLE_CONTACT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."OPPORTUNITYCONTACTROLE_HKEY" AS "OPPORTUNITYCONTACTROLE_HKEY"
		, "DVT_SRC"."LNK_OPPORTUNITYCONTACTROLE_CONTACT_HKEY" AS "LNK_OPPORTUNITYCONTACTROLE_CONTACT_HKEY"
		, "DVT_SRC"."CONTACT_HKEY" AS "CONTACT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_OPPORTUNITYCONTACTROLE_CONTACT') }} "DVT_SRC"
