{{
	config(
		materialized='view',
		alias='LNK_ORDERS_CONTACT_BILLTOCONTACTID',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_ORDERS_CONTACT_BILLTOCONTACTID_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ORDERS_HKEY" AS "ORDERS_HKEY"
		, "DVT_SRC"."LNK_ORDERS_CONTACT_BILLTOCONTACTID_HKEY" AS "LNK_ORDERS_CONTACT_BILLTOCONTACTID_HKEY"
		, "DVT_SRC"."CONTACT_BILLTOCONTACTID_HKEY" AS "CONTACT_BILLTOCONTACTID_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_ORDERS_CONTACT_BILLTOCONTACTID') }} "DVT_SRC"
