{{
	config(
		materialized='view',
		alias='LNK_EMAIL_WHOISWHO',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_EMAIL_WHOISWHO_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."EMAIL_HKEY" AS "EMAIL_HKEY"
		, "DVT_SRC"."LNK_EMAIL_WHOISWHO_HKEY" AS "LNK_EMAIL_WHOISWHO_HKEY"
		, "DVT_SRC"."WHOISWHO_HKEY" AS "WHOISWHO_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_EMAIL_WHOISWHO') }} "DVT_SRC"
