{{
	config(
		materialized='view',
		alias='HUB_ITEMCROSSREFERENCE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_ITEMCROSSREFERENCE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."IVITM_BK" AS "IVITM_BK"
		, "DVT_SRC"."IVXRT_BK" AS "IVXRT_BK"
		, "DVT_SRC"."IVAN8_BK" AS "IVAN8_BK"
		, "DVT_SRC"."IVCITM_BK" AS "IVCITM_BK"
		, "DVT_SRC"."IVEXDJ_BK" AS "IVEXDJ_BK"
		, "DVT_SRC"."IVCIRV_BK" AS "IVCIRV_BK"
	FROM {{ ref('DEMO_FL_HUB_ITEMCROSSREFERENCE') }} "DVT_SRC"
