{{
	config(
		materialized='view',
		alias='SAT_JDE_ITEMCOST',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_ITEMCOST_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."COITM" AS "COITM"
		, "DVT_SRC"."COMCU" AS "COMCU"
		, "DVT_SRC"."COLOCN" AS "COLOCN"
		, "DVT_SRC"."COLOTN" AS "COLOTN"
		, "DVT_SRC"."COLEDG" AS "COLEDG"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."COLITM" AS "COLITM"
		, "DVT_SRC"."COAITM" AS "COAITM"
		, "DVT_SRC"."COLOTG" AS "COLOTG"
		, "DVT_SRC"."COUNCS" AS "COUNCS"
		, "DVT_SRC"."COCSPO" AS "COCSPO"
		, "DVT_SRC"."COCSIN" AS "COCSIN"
		, "DVT_SRC"."COURCD" AS "COURCD"
		, "DVT_SRC"."COURDT" AS "COURDT"
		, "DVT_SRC"."COURAT" AS "COURAT"
		, "DVT_SRC"."COURAB" AS "COURAB"
		, "DVT_SRC"."COURRF" AS "COURRF"
		, "DVT_SRC"."COUSER" AS "COUSER"
		, "DVT_SRC"."COPID" AS "COPID"
		, "DVT_SRC"."COJOBN" AS "COJOBN"
		, "DVT_SRC"."COUPMJ" AS "COUPMJ"
		, "DVT_SRC"."COTDAY" AS "COTDAY"
		, "DVT_SRC"."COCCFL" AS "COCCFL"
		, "DVT_SRC"."COCRCS" AS "COCRCS"
		, "DVT_SRC"."COOSTC" AS "COOSTC"
		, "DVT_SRC"."COSTOC" AS "COSTOC"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_ITEMCOST') }} "DVT_SRC"
