{{
	config(
		materialized='view',
		alias='LKS_JDE_ITEMCOST_PRODUCT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LKS_JDE_ITEMCOST_PRODUCT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LNK_ITEMCOST_PRODUCT_HKEY" AS "LNK_ITEMCOST_PRODUCT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."COLEDG" AS "COLEDG"
		, "DVT_SRC"."COLOTN" AS "COLOTN"
		, "DVT_SRC"."COLOCN" AS "COLOCN"
		, "DVT_SRC"."COMCU" AS "COMCU"
		, "DVT_SRC"."COITM" AS "COITM"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_LKS_JDE_ITEMCOST_PRODUCT') }} "DVT_SRC"
