{{
	config(
		materialized='view',
		alias='LNK_ITEMBRANCH_PRODUCT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_ITEMBRANCH_PRODUCT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMBRANCH_HKEY" AS "ITEMBRANCH_HKEY"
		, "DVT_SRC"."LNK_ITEMBRANCH_PRODUCT_HKEY" AS "LNK_ITEMBRANCH_PRODUCT_HKEY"
		, "DVT_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_ITEMBRANCH_PRODUCT') }} "DVT_SRC"
