{{
	config(
		materialized='view',
		alias='HUB_CONTRACTCONTACTROLE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_CONTRACTCONTACTROLE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."CONTRACTCONTACTROLE_HKEY" AS "CONTRACTCONTACTROLE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ID_BK" AS "ID_BK"
	FROM {{ ref('DEMO_FL_HUB_CONTRACTCONTACTROLE') }} "DVT_SRC"
