{{
	config(
		materialized='view',
		alias='REF_JDE_TIME',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_REF_JDE_TIME_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."TDJDATE" AS "TDJDATE"
		, "DVT_SRC"."TDYRMNDY" AS "TDYRMNDY"
		, "DVT_SRC"."TDDAYNMBR" AS "TDDAYNMBR"
		, "DVT_SRC"."TDMNTHNMBR" AS "TDMNTHNMBR"
		, "DVT_SRC"."TDCALQTR" AS "TDCALQTR"
		, "DVT_SRC"."TDCQTRNMBR" AS "TDCQTRNMBR"
		, "DVT_SRC"."TDYEARNMBR" AS "TDYEARNMBR"
		, "DVT_SRC"."TDWKNMBR" AS "TDWKNMBR"
		, "DVT_SRC"."TDDAYTEXT" AS "TDDAYTEXT"
		, "DVT_SRC"."TDMNTHTEXT" AS "TDMNTHTEXT"
		, "DVT_SRC"."TDLSTDAYMN" AS "TDLSTDAYMN"
		, "DVT_SRC"."TDFISPER" AS "TDFISPER"
		, "DVT_SRC"."TDFISQTR" AS "TDFISQTR"
		, "DVT_SRC"."TDFQTRNMBR" AS "TDFQTRNMBR"
		, "DVT_SRC"."TDFISYEAR" AS "TDFISYEAR"
		, "DVT_SRC"."TDFSPRTEXT" AS "TDFSPRTEXT"
		, "DVT_SRC"."TDLSTDAYFP" AS "TDLSTDAYFP"
	FROM {{ ref('DEMO_FL_REF_JDE_TIME') }} "DVT_SRC"
