{{
	config(
		materialized='view',
		alias='LNK_PARTNER_ACCOUNT_ACCOUNTFROMID',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_PARTNER_ACCOUNT_ACCOUNTFROMID_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PARTNER_HKEY" AS "PARTNER_HKEY"
		, "DVT_SRC"."LNK_PARTNER_ACCOUNT_ACCOUNTFROMID_HKEY" AS "LNK_PARTNER_ACCOUNT_ACCOUNTFROMID_HKEY"
		, "DVT_SRC"."ACCOUNT_ACCOUNTFROMID_HKEY" AS "ACCOUNT_ACCOUNTFROMID_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_PARTNER_ACCOUNT_ACCOUNTFROMID') }} "DVT_SRC"
