{{
	config(
		materialized='view',
		alias='HUB_OPPORTUNITYCONTACTROLE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_OPPORTUNITYCONTACTROLE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."OPPORTUNITYCONTACTROLE_HKEY" AS "OPPORTUNITYCONTACTROLE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ID_BK" AS "ID_BK"
	FROM {{ ref('DEMO_FL_HUB_OPPORTUNITYCONTACTROLE') }} "DVT_SRC"
