{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='BRIDGE_SALESORDER',
		schema='DEMO_BV',
		unique_key = ['"BRIDGE_SALESORDER_HKEY"'],
		merge_update_columns = [],
		tags=['BV', 'BV_BRIDGE_SALESORDER_BRIDGE_INCR', 'BV_BRIDGE_SALESORDER_BRIDGE_INIT']
	)
}}
select * from (
	WITH "MIV" AS 
	( 
		SELECT 
			  UPPER(MD5_HEX(  TO_CHAR("DVO_SRC1"."ADDRESS_HKEY") || '\#' || TO_CHAR("DVO_SRC3"."ACCOUNT_HKEY") || '\#' || TO_CHAR("DVO_SRC5"."SALESORDERDETAIL_HKEY")
				|| '\#' || TO_CHAR("DVO_SRC7"."PRODUCT_HKEY") || '\#'  )) AS "BRIDGE_SALESORDER_HKEY"
			, "BVLCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "BVLCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "DVO_SRC1"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
			, "DVO_SRC3"."ACCOUNT_HKEY" AS "ACCOUNT_HKEY"
			, "DVO_SRC5"."SALESORDERDETAIL_HKEY" AS "SALESORDERDETAIL_HKEY"
			, "DVO_SRC7"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "DVO_SRC2"."LNK_ADDRESS_ACCOUNT_HKEY" AS "LNK_ADDRESS_ACCOUNT_HKEY"
			, "DVO_SRC4"."LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY" AS "LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY"
			, "DVO_SRC6"."LNK_SODETAIL_PRODUCT_HKEY" AS "LNK_SODETAIL_PRODUCT_HKEY"
			, "DVO_SRC1"."ALAN8_BK" AS "ALAN8_BK"
			, "DVO_SRC1"."ALEFTB_BK" AS "ALEFTB_BK"
			, "DVO_SRC5"."SDKCOO_BK" AS "SDKCOO_BK"
			, "DVO_SRC5"."SDDOCO_BK" AS "SDDOCO_BK"
			, "DVO_SRC5"."SDDCTO_BK" AS "SDDCTO_BK"
			, "DVO_SRC5"."SDLNID_BK" AS "SDLNID_BK"
			, "DVO_SRC3"."ACCOUNT_BK" AS "ACCOUNT_BK"
			, "DVO_SRC7"."PRODUCT_BK" AS "PRODUCT_BK"
		FROM {{ source('DEMO_FMC', 'LOAD_CYCLE_INFO') }} "BVLCI_SRC"
		INNER JOIN {{ ref('DEMO_FL_HUB_ADDRESS') }} "DVO_SRC1" ON 1 = 1
		INNER JOIN {{ ref('DEMO_FL_LNK_ADDRESS_ACCOUNT') }} "DVO_SRC2" ON "DVO_SRC2"."ADDRESS_HKEY" = "DVO_SRC1"."ADDRESS_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_ACCOUNT') }} "DVO_SRC3" ON "DVO_SRC3"."ACCOUNT_HKEY" = "DVO_SRC2"."ACCOUNT_HKEY"
		INNER JOIN {{ ref('DEMO_FL_LNK_SODETAIL_ACCOUNT_SDSHAN') }} "DVO_SRC4" ON "DVO_SRC4"."ACCOUNT_SDSHAN_HKEY" = "DVO_SRC3"."ACCOUNT_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_SALESORDERDETAIL') }} "DVO_SRC5" ON "DVO_SRC5"."SALESORDERDETAIL_HKEY" = "DVO_SRC4"."SALESORDERDETAIL_HKEY"
		INNER JOIN {{ ref('DEMO_FL_LNK_SODETAIL_PRODUCT') }} "DVO_SRC6" ON "DVO_SRC6"."SALESORDERDETAIL_HKEY" = "DVO_SRC5"."SALESORDERDETAIL_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_PRODUCT') }} "DVO_SRC7" ON "DVO_SRC7"."PRODUCT_HKEY" = "DVO_SRC6"."PRODUCT_HKEY"
	)
	SELECT 
		  "MIV"."BRIDGE_SALESORDER_HKEY"
		, "MIV"."LOAD_DATE"
		, "MIV"."LOAD_CYCLE_ID"
		, "MIV"."PRODUCT_HKEY"
		, "MIV"."ACCOUNT_HKEY"
		, "MIV"."SALESORDERDETAIL_HKEY"
		, "MIV"."ADDRESS_HKEY"
		, "MIV"."LNK_SODETAIL_PRODUCT_HKEY"
		, "MIV"."LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY"
		, "MIV"."LNK_ADDRESS_ACCOUNT_HKEY"
		, "MIV"."SDKCOO_BK"
		, "MIV"."SDDOCO_BK"
		, "MIV"."SDDCTO_BK"
		, "MIV"."SDLNID_BK"
		, "MIV"."ALAN8_BK"
		, "MIV"."ALEFTB_BK"
		, "MIV"."PRODUCT_BK"
		, "MIV"."ACCOUNT_BK"
	FROM "MIV"

) final 
where '{{ var("load_type") }}' = 'INCR'

UNION ALL

select * from (
	WITH "MIV" AS 
	( 
		SELECT 
			  UPPER(MD5_HEX(  TO_CHAR("DVO_SRC1"."ADDRESS_HKEY") || '\#' || TO_CHAR("DVO_SRC3"."ACCOUNT_HKEY") || '\#' || TO_CHAR("DVO_SRC5"."SALESORDERDETAIL_HKEY")
				|| '\#' || TO_CHAR("DVO_SRC7"."PRODUCT_HKEY") || '\#'  )) AS "BRIDGE_SALESORDER_HKEY"
			, "BVLCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "BVLCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "DVO_SRC1"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
			, "DVO_SRC3"."ACCOUNT_HKEY" AS "ACCOUNT_HKEY"
			, "DVO_SRC5"."SALESORDERDETAIL_HKEY" AS "SALESORDERDETAIL_HKEY"
			, "DVO_SRC7"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "DVO_SRC2"."LNK_ADDRESS_ACCOUNT_HKEY" AS "LNK_ADDRESS_ACCOUNT_HKEY"
			, "DVO_SRC4"."LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY" AS "LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY"
			, "DVO_SRC6"."LNK_SODETAIL_PRODUCT_HKEY" AS "LNK_SODETAIL_PRODUCT_HKEY"
			, "DVO_SRC1"."ALAN8_BK" AS "ALAN8_BK"
			, "DVO_SRC1"."ALEFTB_BK" AS "ALEFTB_BK"
			, "DVO_SRC5"."SDKCOO_BK" AS "SDKCOO_BK"
			, "DVO_SRC5"."SDDOCO_BK" AS "SDDOCO_BK"
			, "DVO_SRC5"."SDDCTO_BK" AS "SDDCTO_BK"
			, "DVO_SRC5"."SDLNID_BK" AS "SDLNID_BK"
			, "DVO_SRC3"."ACCOUNT_BK" AS "ACCOUNT_BK"
			, "DVO_SRC7"."PRODUCT_BK" AS "PRODUCT_BK"
		FROM {{ source('DEMO_FMC', 'LOAD_CYCLE_INFO') }} "BVLCI_SRC"
		INNER JOIN {{ ref('DEMO_FL_HUB_ADDRESS') }} "DVO_SRC1" ON 1 = 1
		INNER JOIN {{ ref('DEMO_FL_LNK_ADDRESS_ACCOUNT') }} "DVO_SRC2" ON "DVO_SRC2"."ADDRESS_HKEY" = "DVO_SRC1"."ADDRESS_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_ACCOUNT') }} "DVO_SRC3" ON "DVO_SRC3"."ACCOUNT_HKEY" = "DVO_SRC2"."ACCOUNT_HKEY"
		INNER JOIN {{ ref('DEMO_FL_LNK_SODETAIL_ACCOUNT_SDSHAN') }} "DVO_SRC4" ON "DVO_SRC4"."ACCOUNT_SDSHAN_HKEY" = "DVO_SRC3"."ACCOUNT_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_SALESORDERDETAIL') }} "DVO_SRC5" ON "DVO_SRC5"."SALESORDERDETAIL_HKEY" = "DVO_SRC4"."SALESORDERDETAIL_HKEY"
		INNER JOIN {{ ref('DEMO_FL_LNK_SODETAIL_PRODUCT') }} "DVO_SRC6" ON "DVO_SRC6"."SALESORDERDETAIL_HKEY" = "DVO_SRC5"."SALESORDERDETAIL_HKEY"
		INNER JOIN {{ ref('DEMO_FL_HUB_PRODUCT') }} "DVO_SRC7" ON "DVO_SRC7"."PRODUCT_HKEY" = "DVO_SRC6"."PRODUCT_HKEY"
	)
	SELECT 
		  "MIV"."BRIDGE_SALESORDER_HKEY" AS "BRIDGE_SALESORDER_HKEY"
		, "MIV"."LOAD_DATE" AS "LOAD_DATE"
		, "MIV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIV"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "MIV"."ACCOUNT_HKEY" AS "ACCOUNT_HKEY"
		, "MIV"."SALESORDERDETAIL_HKEY" AS "SALESORDERDETAIL_HKEY"
		, "MIV"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
		, "MIV"."LNK_SODETAIL_PRODUCT_HKEY" AS "LNK_SODETAIL_PRODUCT_HKEY"
		, "MIV"."LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY" AS "LNK_SODETAIL_ACCOUNT_SDSHAN_HKEY"
		, "MIV"."LNK_ADDRESS_ACCOUNT_HKEY" AS "LNK_ADDRESS_ACCOUNT_HKEY"
		, "MIV"."SDKCOO_BK" AS "SDKCOO_BK"
		, "MIV"."SDDOCO_BK" AS "SDDOCO_BK"
		, "MIV"."SDDCTO_BK" AS "SDDCTO_BK"
		, "MIV"."SDLNID_BK" AS "SDLNID_BK"
		, "MIV"."ALAN8_BK" AS "ALAN8_BK"
		, "MIV"."ALEFTB_BK" AS "ALEFTB_BK"
		, "MIV"."PRODUCT_BK" AS "PRODUCT_BK"
		, "MIV"."ACCOUNT_BK" AS "ACCOUNT_BK"
	FROM "MIV" "MIV"

) final 
where '{{ var("load_type") }}' = 'INIT'