{{
	config(
		materialized='view',
		alias='SAT_SALESFORCE_PRODUCT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_SALESFORCE_PRODUCT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ID" AS "ID"
		, "DVT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."NAME" AS "NAME"
		, "DVT_SRC"."PRODUCTCODE" AS "PRODUCTCODE"
		, "DVT_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "DVT_SRC"."ISACTIVE" AS "ISACTIVE"
		, "DVT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "DVT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "DVT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "DVT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "DVT_SRC"."FAMILY" AS "FAMILY"
		, "DVT_SRC"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
		, "DVT_SRC"."EXTERNALID" AS "EXTERNALID"
		, "DVT_SRC"."DISPLAYURL" AS "DISPLAYURL"
		, "DVT_SRC"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
		, "DVT_SRC"."ISDELETED" AS "ISDELETED"
		, "DVT_SRC"."ISARCHIVED" AS "ISARCHIVED"
		, "DVT_SRC"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_SALESFORCE_PRODUCT') }} "DVT_SRC"
