{{
	config(
		materialized='view',
		alias='HUB_SALESORDERHEADER',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_SALESORDERHEADER_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."SALESORDERHEADER_HKEY" AS "SALESORDERHEADER_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."SHDOCO_BK" AS "SHDOCO_BK"
		, "DVT_SRC"."SHDCTO_BK" AS "SHDCTO_BK"
		, "DVT_SRC"."SHKCOO_BK" AS "SHKCOO_BK"
	FROM {{ ref('DEMO_FL_HUB_SALESORDERHEADER') }} "DVT_SRC"
