{{
	config(
		materialized='view',
		alias='SAT_JDE_ITEMPRICE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_ITEMPRICE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."BPITM" AS "BPITM"
		, "DVT_SRC"."BPMCU" AS "BPMCU"
		, "DVT_SRC"."BPLOCN" AS "BPLOCN"
		, "DVT_SRC"."BPLOTN" AS "BPLOTN"
		, "DVT_SRC"."BPAN8" AS "BPAN8"
		, "DVT_SRC"."BPIGID" AS "BPIGID"
		, "DVT_SRC"."BPCGID" AS "BPCGID"
		, "DVT_SRC"."BPLOTG" AS "BPLOTG"
		, "DVT_SRC"."BPFRMP" AS "BPFRMP"
		, "DVT_SRC"."BPCRCD" AS "BPCRCD"
		, "DVT_SRC"."BPUOM" AS "BPUOM"
		, "DVT_SRC"."BPEXDJ" AS "BPEXDJ"
		, "DVT_SRC"."BPUPMJ" AS "BPUPMJ"
		, "DVT_SRC"."BPTDAY" AS "BPTDAY"
		, "DVT_SRC"."BPLEDG" AS "BPLEDG"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."BPLITM" AS "BPLITM"
		, "DVT_SRC"."BPAITM" AS "BPAITM"
		, "DVT_SRC"."BPEFTJ" AS "BPEFTJ"
		, "DVT_SRC"."BPUPRC" AS "BPUPRC"
		, "DVT_SRC"."BPACRD" AS "BPACRD"
		, "DVT_SRC"."BPBSCD" AS "BPBSCD"
		, "DVT_SRC"."BPFVTR" AS "BPFVTR"
		, "DVT_SRC"."BPFRMN" AS "BPFRMN"
		, "DVT_SRC"."BPURCD" AS "BPURCD"
		, "DVT_SRC"."BPURDT" AS "BPURDT"
		, "DVT_SRC"."BPURAT" AS "BPURAT"
		, "DVT_SRC"."BPURAB" AS "BPURAB"
		, "DVT_SRC"."BPURRF" AS "BPURRF"
		, "DVT_SRC"."BPAPRS" AS "BPAPRS"
		, "DVT_SRC"."BPUSER" AS "BPUSER"
		, "DVT_SRC"."BPPID" AS "BPPID"
		, "DVT_SRC"."BPJOBN" AS "BPJOBN"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_ITEMPRICE') }} "DVT_SRC"
