{{
	config(
		materialized='view',
		alias='LNK_CAMPAIGNMEMBER_CAMPAIGN',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_CAMPAIGNMEMBER_CAMPAIGN_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."CAMPAIGNMEMBER_HKEY" AS "CAMPAIGNMEMBER_HKEY"
		, "DVT_SRC"."LNK_CAMPAIGNMEMBER_CAMPAIGN_HKEY" AS "LNK_CAMPAIGNMEMBER_CAMPAIGN_HKEY"
		, "DVT_SRC"."CAMPAIGN_HKEY" AS "CAMPAIGN_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_CAMPAIGNMEMBER_CAMPAIGN') }} "DVT_SRC"
