{{
	config(
		materialized='view',
		alias='SAT_JDE_ITEMCROSSREFERENCE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_ITEMCROSSREFERENCE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."IVAN8" AS "IVAN8"
		, "DVT_SRC"."IVXRT" AS "IVXRT"
		, "DVT_SRC"."IVITM" AS "IVITM"
		, "DVT_SRC"."IVEXDJ" AS "IVEXDJ"
		, "DVT_SRC"."IVCITM" AS "IVCITM"
		, "DVT_SRC"."IVCIRV" AS "IVCIRV"
		, "DVT_SRC"."IVMCU" AS "IVMCU"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."IVEFTJ" AS "IVEFTJ"
		, "DVT_SRC"."IVDSC1" AS "IVDSC1"
		, "DVT_SRC"."IVDSC2" AS "IVDSC2"
		, "DVT_SRC"."IVALN" AS "IVALN"
		, "DVT_SRC"."IVLITM" AS "IVLITM"
		, "DVT_SRC"."IVAITM" AS "IVAITM"
		, "DVT_SRC"."IVURCD" AS "IVURCD"
		, "DVT_SRC"."IVURDT" AS "IVURDT"
		, "DVT_SRC"."IVURAT" AS "IVURAT"
		, "DVT_SRC"."IVURAB" AS "IVURAB"
		, "DVT_SRC"."IVURRF" AS "IVURRF"
		, "DVT_SRC"."IVUSER" AS "IVUSER"
		, "DVT_SRC"."IVPID" AS "IVPID"
		, "DVT_SRC"."IVJOBN" AS "IVJOBN"
		, "DVT_SRC"."IVUPMJ" AS "IVUPMJ"
		, "DVT_SRC"."IVTDAY" AS "IVTDAY"
		, "DVT_SRC"."IVRATO" AS "IVRATO"
		, "DVT_SRC"."IVAPSP" AS "IVAPSP"
		, "DVT_SRC"."IVIDEM" AS "IVIDEM"
		, "DVT_SRC"."IVAPSS" AS "IVAPSS"
		, "DVT_SRC"."IVADIND" AS "IVADIND"
		, "DVT_SRC"."IVBPIND" AS "IVBPIND"
		, "DVT_SRC"."IVCARDNO" AS "IVCARDNO"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_ITEMCROSSREFERENCE') }} "DVT_SRC"
