{{
	config(
		materialized='view',
		alias='LNK_OPPORTUNITY_CAMPAIGN',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_OPPORTUNITY_CAMPAIGN_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."OPPORTUNITY_HKEY" AS "OPPORTUNITY_HKEY"
		, "DVT_SRC"."LNK_OPPORTUNITY_CAMPAIGN_HKEY" AS "LNK_OPPORTUNITY_CAMPAIGN_HKEY"
		, "DVT_SRC"."CAMPAIGN_HKEY" AS "CAMPAIGN_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_OPPORTUNITY_CAMPAIGN') }} "DVT_SRC"
