{{
	config(
		materialized='view',
		alias='LKS_JDE_ITEMCROSSREFERENCE_BUSINESSUNITMASTER',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LKS_JDE_ITEMCROSSREFERENCE_BUSINESSUNITMASTER_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LNK_ITEMCROSSREFERENCE_BUSINESSUNITMASTER_HKEY" AS "LNK_ITEMCROSSREFERENCE_BUSINESSUNITMASTER_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."IVCIRV" AS "IVCIRV"
		, "DVT_SRC"."IVEXDJ" AS "IVEXDJ"
		, "DVT_SRC"."IVCITM" AS "IVCITM"
		, "DVT_SRC"."IVAN8" AS "IVAN8"
		, "DVT_SRC"."IVXRT" AS "IVXRT"
		, "DVT_SRC"."IVITM" AS "IVITM"
		, "DVT_SRC"."IVMCU" AS "IVMCU"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_LKS_JDE_ITEMCROSSREFERENCE_BUSINESSUNITMASTER') }} "DVT_SRC"
