{{
	config(
		materialized='view',
		alias='LNK_CONTRACT_USER_ACTIVATEDBYID',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_CONTRACT_USER_ACTIVATEDBYID_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."CONTRACT_HKEY" AS "CONTRACT_HKEY"
		, "DVT_SRC"."LNK_CONTRACT_USER_ACTIVATEDBYID_HKEY" AS "LNK_CONTRACT_USER_ACTIVATEDBYID_HKEY"
		, "DVT_SRC"."USER_ACTIVATEDBYID_HKEY" AS "USER_ACTIVATEDBYID_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_CONTRACT_USER_ACTIVATEDBYID') }} "DVT_SRC"
