{{
	config(
		materialized='view',
		alias='HUB_ITEMPRICE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_ITEMPRICE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."BPITM_BK" AS "BPITM_BK"
		, "DVT_SRC"."BPMCU_BK" AS "BPMCU_BK"
		, "DVT_SRC"."BPLOCN_BK" AS "BPLOCN_BK"
		, "DVT_SRC"."BPLOTN_BK" AS "BPLOTN_BK"
		, "DVT_SRC"."BPAN8_BK" AS "BPAN8_BK"
		, "DVT_SRC"."BPIGID_BK" AS "BPIGID_BK"
		, "DVT_SRC"."BPCGID_BK" AS "BPCGID_BK"
		, "DVT_SRC"."BPLOTG_BK" AS "BPLOTG_BK"
		, "DVT_SRC"."BPFRMP_BK" AS "BPFRMP_BK"
		, "DVT_SRC"."BPCRCD_BK" AS "BPCRCD_BK"
		, "DVT_SRC"."BPUOM_BK" AS "BPUOM_BK"
		, "DVT_SRC"."BPEXDJ_BK" AS "BPEXDJ_BK"
		, "DVT_SRC"."BPUPMJ_BK" AS "BPUPMJ_BK"
		, "DVT_SRC"."BPTDAY_BK" AS "BPTDAY_BK"
	FROM {{ ref('DEMO_FL_HUB_ITEMPRICE') }} "DVT_SRC"
