{{
	config(
		materialized='view',
		alias='LNK_LEAD_CONTACT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_LEAD_CONTACT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LEAD_HKEY" AS "LEAD_HKEY"
		, "DVT_SRC"."LNK_LEAD_CONTACT_HKEY" AS "LNK_LEAD_CONTACT_HKEY"
		, "DVT_SRC"."CONTACT_HKEY" AS "CONTACT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_LEAD_CONTACT') }} "DVT_SRC"
