{{
	config(
		materialized='view',
		alias='LNK_PRICEBOOKENTRY_PRICEBOOK2',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_PRICEBOOKENTRY_PRICEBOOK2_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PRICEBOOKENTRY_HKEY" AS "PRICEBOOKENTRY_HKEY"
		, "DVT_SRC"."LNK_PRICEBOOKENTRY_PRICEBOOK2_HKEY" AS "LNK_PRICEBOOKENTRY_PRICEBOOK2_HKEY"
		, "DVT_SRC"."PRICEBOOK2_HKEY" AS "PRICEBOOK2_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_PRICEBOOKENTRY_PRICEBOOK2') }} "DVT_SRC"
