{{
	config(
		materialized='view',
		alias='HUB_SALESORDERDETAIL',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_HUB_SALESORDERDETAIL_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."SALESORDERDETAIL_HKEY" AS "SALESORDERDETAIL_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."SDKCOO_BK" AS "SDKCOO_BK"
		, "DVT_SRC"."SDDOCO_BK" AS "SDDOCO_BK"
		, "DVT_SRC"."SDDCTO_BK" AS "SDDCTO_BK"
		, "DVT_SRC"."SDLNID_BK" AS "SDLNID_BK"
	FROM {{ ref('DEMO_FL_HUB_SALESORDERDETAIL') }} "DVT_SRC"
