{{
	config(
		materialized='view',
		alias='SAT_JDE_PHONE',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_PHONE_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PHONE_HKEY" AS "PHONE_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."WPAN8" AS "WPAN8"
		, "DVT_SRC"."WPIDLN" AS "WPIDLN"
		, "DVT_SRC"."WPRCK7" AS "WPRCK7"
		, "DVT_SRC"."WPCNLN" AS "WPCNLN"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."WPPHTP" AS "WPPHTP"
		, "DVT_SRC"."WPAR1" AS "WPAR1"
		, "DVT_SRC"."WPPH1" AS "WPPH1"
		, "DVT_SRC"."WPUSER" AS "WPUSER"
		, "DVT_SRC"."WPPID" AS "WPPID"
		, "DVT_SRC"."WPUPMJ" AS "WPUPMJ"
		, "DVT_SRC"."WPJOBN" AS "WPJOBN"
		, "DVT_SRC"."WPUPMT" AS "WPUPMT"
		, "DVT_SRC"."WPCFNO1" AS "WPCFNO1"
		, "DVT_SRC"."WPGEN1" AS "WPGEN1"
		, "DVT_SRC"."WPFALGE" AS "WPFALGE"
		, "DVT_SRC"."WPSYNCS" AS "WPSYNCS"
		, "DVT_SRC"."WPCAAD" AS "WPCAAD"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_PHONE') }} "DVT_SRC"
