{{
	config(
		materialized='view',
		alias='LNK_ITEMCOST_ITEMBRANCH',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_ITEMCOST_ITEMBRANCH_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
		, "DVT_SRC"."LNK_ITEMCOST_ITEMBRANCH_HKEY" AS "LNK_ITEMCOST_ITEMBRANCH_HKEY"
		, "DVT_SRC"."ITEMBRANCH_HKEY" AS "ITEMBRANCH_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_ITEMCOST_ITEMBRANCH') }} "DVT_SRC"
