{{
	config(
		materialized='view',
		alias='LKS_JDE_COMPANY_ACCOUNT',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LKS_JDE_COMPANY_ACCOUNT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LNK_COMPANY_ACCOUNT_HKEY" AS "LNK_COMPANY_ACCOUNT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."CCCO" AS "CCCO"
		, "DVT_SRC"."CCAN8" AS "CCAN8"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_LKS_JDE_COMPANY_ACCOUNT') }} "DVT_SRC"
