{{
	config(
		materialized='view',
		alias='LNK_PRODUCT2_USER',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_PRODUCT_USER_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "DVT_SRC"."LNK_PRODUCT_USER_HKEY" AS "LNK_PRODUCT_USER_HKEY"
		, "DVT_SRC"."USER_HKEY" AS "USER_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_PRODUCT_USER') }} "DVT_SRC"
