{{
	config(
		materialized='view',
		alias='LKS_JDE_BUSINESSUNITMASTER_COMPANY',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LKS_JDE_BUSINESSUNITMASTER_COMPANY_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."LNK_BUSINESSUNITMASTER_COMPANY_HKEY" AS "LNK_BUSINESSUNITMASTER_COMPANY_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."MCMCU" AS "MCMCU"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_LKS_JDE_BUSINESSUNITMASTER_COMPANY') }} "DVT_SRC"
