{{
	config(
		materialized='view',
		alias='SAT_SALESFORCE_CAMPAIGNMEMBER',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_SALESFORCE_CAMPAIGNMEMBER_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."CAMPAIGNMEMBER_HKEY" AS "CAMPAIGNMEMBER_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ID" AS "ID"
		, "DVT_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "DVT_SRC"."CONTACTID" AS "CONTACTID"
		, "DVT_SRC"."LEADID" AS "LEADID"
		, "DVT_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "DVT_SRC"."CAMPAIGNID" AS "CAMPAIGNID"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."ISDELETED" AS "ISDELETED"
		, "DVT_SRC"."STATUS" AS "STATUS"
		, "DVT_SRC"."HASRESPONDED" AS "HASRESPONDED"
		, "DVT_SRC"."ISPRIMARY" AS "ISPRIMARY"
		, "DVT_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "DVT_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "DVT_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "DVT_SRC"."FIRSTRESPONDEDDATE" AS "FIRSTRESPONDEDDATE"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_SALESFORCE_CAMPAIGNMEMBER') }} "DVT_SRC"
