{{
	config(
		materialized='view',
		alias='LNK_PRICEBOOKENTRY_PRODUCT2',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_PRICEBOOKENTRY_PRODUCT_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."PRICEBOOKENTRY_HKEY" AS "PRICEBOOKENTRY_HKEY"
		, "DVT_SRC"."LNK_PRICEBOOKENTRY_PRODUCT_HKEY" AS "LNK_PRICEBOOKENTRY_PRODUCT_HKEY"
		, "DVT_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_PRICEBOOKENTRY_PRODUCT') }} "DVT_SRC"
