{{
	config(
		materialized='view',
		alias='LNK_SODETAIL_COMPANY',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_LNK_SODETAIL_COMPANY_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."SALESORDERDETAIL_HKEY" AS "SALESORDERDETAIL_HKEY"
		, "DVT_SRC"."LNK_SODETAIL_COMPANY_HKEY" AS "LNK_SODETAIL_COMPANY_HKEY"
		, "DVT_SRC"."COMPANY_HKEY" AS "COMPANY_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	FROM {{ ref('DEMO_FL_LNK_SODETAIL_COMPANY') }} "DVT_SRC"
