{{
	config(
		materialized='view',
		alias='SAT_JDE_ADDRESS',
		schema='DEMO_BV',
		tags=['view', 'BV', 'BV_SAT_JDE_ADDRESS_BUSINESS_VIEW']
	)
}}
	SELECT 
		  "DVT_SRC"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
		, "DVT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "DVT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "DVT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "DVT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "DVT_SRC"."ALAN8" AS "ALAN8"
		, "DVT_SRC"."ALEFTB" AS "ALEFTB"
		, "DVT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "DVT_SRC"."ALEFTF" AS "ALEFTF"
		, "DVT_SRC"."ALADD1" AS "ALADD1"
		, "DVT_SRC"."ALADD2" AS "ALADD2"
		, "DVT_SRC"."ALADD3" AS "ALADD3"
		, "DVT_SRC"."ALADD4" AS "ALADD4"
		, "DVT_SRC"."ALADDZ" AS "ALADDZ"
		, "DVT_SRC"."ALCTY1" AS "ALCTY1"
		, "DVT_SRC"."ALCOUN" AS "ALCOUN"
		, "DVT_SRC"."ALADDS" AS "ALADDS"
		, "DVT_SRC"."ALCRTE" AS "ALCRTE"
		, "DVT_SRC"."ALBKML" AS "ALBKML"
		, "DVT_SRC"."ALCTR" AS "ALCTR"
		, "DVT_SRC"."ALUSER" AS "ALUSER"
		, "DVT_SRC"."ALPID" AS "ALPID"
		, "DVT_SRC"."ALUPMJ" AS "ALUPMJ"
		, "DVT_SRC"."ALJOBN" AS "ALJOBN"
		, "DVT_SRC"."ALUPMT" AS "ALUPMT"
		, "DVT_SRC"."ALSYNCS" AS "ALSYNCS"
		, "DVT_SRC"."ALCAAD" AS "ALCAAD"
		, "DVT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
	FROM {{ ref('DEMO_FL_SAT_JDE_ADDRESS') }} "DVT_SRC"
