{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='HUB_PHONE',
		schema='DEMO_FL',
		unique_key = ['"PHONE_HKEY"'],
		merge_update_columns = [],
		tags=['JDEDWARDS', 'HUB_JDE_PHONE_INCR', 'HUB_JDE_PHONE_INIT']
	)
}}
select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."PHONE_HKEY" AS "PHONE_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."WPAN8_BK" AS "WPAN8_BK"
			, "STG_SRC1"."WPIDLN_BK" AS "WPIDLN_BK"
			, "STG_SRC1"."WPCNLN_BK" AS "WPCNLN_BK"
			, "STG_SRC1"."WPRCK7_BK" AS "WPRCK7_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F0115') }} "STG_SRC1"
		WHERE  "STG_SRC1"."RECORD_TYPE" = 'S'
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."PHONE_HKEY" AS "PHONE_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."WPAN8_BK" AS "WPAN8_BK"
			, "CHANGE_SET"."WPIDLN_BK" AS "WPIDLN_BK"
			, "CHANGE_SET"."WPCNLN_BK" AS "WPCNLN_BK"
			, "CHANGE_SET"."WPRCK7_BK" AS "WPRCK7_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."PHONE_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER","CHANGE_SET"."LOAD_DATE",
				"CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	, "MIV" AS 
	( 
		SELECT 
			  "MIN_LOAD_TIME"."PHONE_HKEY" AS "PHONE_HKEY"
			, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
			, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "MIN_LOAD_TIME"."WPAN8_BK" AS "WPAN8_BK"
			, "MIN_LOAD_TIME"."WPIDLN_BK" AS "WPIDLN_BK"
			, "MIN_LOAD_TIME"."WPCNLN_BK" AS "WPCNLN_BK"
			, "MIN_LOAD_TIME"."WPRCK7_BK" AS "WPRCK7_BK"
		FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
		WHERE  "MIN_LOAD_TIME"."DUMMY" = 1
	)
	SELECT 
		  "MIV"."PHONE_HKEY"
		, "MIV"."LOAD_DATE"
		, "MIV"."LOAD_CYCLE_ID"
		, "MIV"."WPAN8_BK"
		, "MIV"."WPIDLN_BK"
		, "MIV"."WPCNLN_BK"
		, "MIV"."WPRCK7_BK"
	FROM "MIV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."PHONE_HKEY" AS "PHONE_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."WPAN8_BK" AS "WPAN8_BK"
			, "STG_SRC1"."WPIDLN_BK" AS "WPIDLN_BK"
			, "STG_SRC1"."WPCNLN_BK" AS "WPCNLN_BK"
			, "STG_SRC1"."WPRCK7_BK" AS "WPRCK7_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F0115') }} "STG_SRC1"
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."PHONE_HKEY" AS "PHONE_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."WPAN8_BK" AS "WPAN8_BK"
			, "CHANGE_SET"."WPIDLN_BK" AS "WPIDLN_BK"
			, "CHANGE_SET"."WPCNLN_BK" AS "WPCNLN_BK"
			, "CHANGE_SET"."WPRCK7_BK" AS "WPRCK7_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."PHONE_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER","CHANGE_SET"."LOAD_DATE",
				"CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	SELECT 
		  "MIN_LOAD_TIME"."PHONE_HKEY" AS "PHONE_HKEY"
		, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
		, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIN_LOAD_TIME"."WPAN8_BK" AS "WPAN8_BK"
		, "MIN_LOAD_TIME"."WPIDLN_BK" AS "WPIDLN_BK"
		, "MIN_LOAD_TIME"."WPCNLN_BK" AS "WPCNLN_BK"
		, "MIN_LOAD_TIME"."WPRCK7_BK" AS "WPRCK7_BK"
	FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
	WHERE  "MIN_LOAD_TIME"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'