{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_ITEMCROSSREFERENCE',
		schema='DEMO_FL',
		unique_key = ['"ITEMCROSSREFERENCE_HKEY"', '"LOAD_DATE"'],
		merge_update_columns = ['"LOAD_END_DATE"', '"DELETE_FLAG"', '"CDC_TIMESTAMP"'],
		tags=['JDEDWARDS', 'SAT_JDE_ITEMCROSSREFERENCE_INCR', 'SAT_JDE_ITEMCROSSREFERENCE_INIT']
	)
}}
select * from (
	WITH "END_DATING" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_DK"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "SAT_TEMP_SRC_DK"."LOAD_DATE" AS "LOAD_DATE"
			, CASE WHEN LEAD( "SAT_TEMP_SRC_DK"."DELETE_FLAG" || "SAT_TEMP_SRC_DK"."SOURCE",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."ITEMCROSSREFERENCE_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE",
				"SAT_TEMP_SRC_DK"."LOAD_CYCLE_ID")= 'Y' || 'STG' THEN CAST('Y' AS VARCHAR) ELSE "SAT_TEMP_SRC_DK"."DELETE_FLAG" END AS "DELETE_FLAG"
			, LEAD("SAT_TEMP_SRC_DK"."CDC_TIMESTAMP",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."ITEMCROSSREFERENCE_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE") AS "CDC_TIMESTAMP"
		FROM {{ ref('JDEDWARDS_STG_SAT_JDE_ITEMCROSSREFERENCE_TMP') }} "SAT_TEMP_SRC_DK"
		WHERE  "SAT_TEMP_SRC_DK"."EQUAL" = 0
	)
	, "CALC_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_US"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "SAT_TEMP_SRC_US"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_TEMP_SRC_US"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, COALESCE(LEAD("SAT_TEMP_SRC_US"."LOAD_DATE",1)OVER(PARTITION BY "SAT_TEMP_SRC_US"."ITEMCROSSREFERENCE_HKEY" ORDER BY "SAT_TEMP_SRC_US"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "END_DATING"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_TEMP_SRC_US"."SOURCE" AS "SOURCE"
			, "SAT_TEMP_SRC_US"."HASH_DIFF" AS "HASH_DIFF"
			, CASE WHEN "END_DATING"."DELETE_FLAG" = CAST('Y' AS VARCHAR) THEN "END_DATING"."CDC_TIMESTAMP" ELSE "SAT_TEMP_SRC_US"."CDC_TIMESTAMP" END AS "CDC_TIMESTAMP"
			, "SAT_TEMP_SRC_US"."IVAN8" AS "IVAN8"
			, "SAT_TEMP_SRC_US"."IVXRT" AS "IVXRT"
			, "SAT_TEMP_SRC_US"."IVITM" AS "IVITM"
			, "SAT_TEMP_SRC_US"."IVEXDJ" AS "IVEXDJ"
			, "SAT_TEMP_SRC_US"."IVCITM" AS "IVCITM"
			, "SAT_TEMP_SRC_US"."IVCIRV" AS "IVCIRV"
			, "SAT_TEMP_SRC_US"."IVMCU" AS "IVMCU"
			, "SAT_TEMP_SRC_US"."IVEFTJ" AS "IVEFTJ"
			, "SAT_TEMP_SRC_US"."IVDSC1" AS "IVDSC1"
			, "SAT_TEMP_SRC_US"."IVDSC2" AS "IVDSC2"
			, "SAT_TEMP_SRC_US"."IVALN" AS "IVALN"
			, "SAT_TEMP_SRC_US"."IVLITM" AS "IVLITM"
			, "SAT_TEMP_SRC_US"."IVAITM" AS "IVAITM"
			, "SAT_TEMP_SRC_US"."IVURCD" AS "IVURCD"
			, "SAT_TEMP_SRC_US"."IVURDT" AS "IVURDT"
			, "SAT_TEMP_SRC_US"."IVURAT" AS "IVURAT"
			, "SAT_TEMP_SRC_US"."IVURAB" AS "IVURAB"
			, "SAT_TEMP_SRC_US"."IVURRF" AS "IVURRF"
			, "SAT_TEMP_SRC_US"."IVUSER" AS "IVUSER"
			, "SAT_TEMP_SRC_US"."IVPID" AS "IVPID"
			, "SAT_TEMP_SRC_US"."IVJOBN" AS "IVJOBN"
			, "SAT_TEMP_SRC_US"."IVUPMJ" AS "IVUPMJ"
			, "SAT_TEMP_SRC_US"."IVTDAY" AS "IVTDAY"
			, "SAT_TEMP_SRC_US"."IVRATO" AS "IVRATO"
			, "SAT_TEMP_SRC_US"."IVAPSP" AS "IVAPSP"
			, "SAT_TEMP_SRC_US"."IVIDEM" AS "IVIDEM"
			, "SAT_TEMP_SRC_US"."IVAPSS" AS "IVAPSS"
			, "SAT_TEMP_SRC_US"."IVADIND" AS "IVADIND"
			, "SAT_TEMP_SRC_US"."IVBPIND" AS "IVBPIND"
			, "SAT_TEMP_SRC_US"."IVCARDNO" AS "IVCARDNO"
		FROM {{ ref('JDEDWARDS_STG_SAT_JDE_ITEMCROSSREFERENCE_TMP') }} "SAT_TEMP_SRC_US"
		INNER JOIN "END_DATING" "END_DATING" ON  "SAT_TEMP_SRC_US"."ITEMCROSSREFERENCE_HKEY" = "END_DATING"."ITEMCROSSREFERENCE_HKEY" AND "SAT_TEMP_SRC_US"."LOAD_DATE" =
			 "END_DATING"."LOAD_DATE"
		WHERE  "SAT_TEMP_SRC_US"."EQUAL" = 0 AND NOT("SAT_TEMP_SRC_US"."DELETE_FLAG" = CAST('Y' AS VARCHAR) AND "SAT_TEMP_SRC_US"."SOURCE" = 'STG')
	)
	, "FILTER_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "CALC_LOAD_END_DATE"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "CALC_LOAD_END_DATE"."LOAD_DATE" AS "LOAD_DATE"
			, "CALC_LOAD_END_DATE"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALC_LOAD_END_DATE"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, "CALC_LOAD_END_DATE"."DELETE_FLAG" AS "DELETE_FLAG"
			, "CALC_LOAD_END_DATE"."HASH_DIFF" AS "HASH_DIFF"
			, "CALC_LOAD_END_DATE"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALC_LOAD_END_DATE"."IVAN8" AS "IVAN8"
			, "CALC_LOAD_END_DATE"."IVXRT" AS "IVXRT"
			, "CALC_LOAD_END_DATE"."IVITM" AS "IVITM"
			, "CALC_LOAD_END_DATE"."IVEXDJ" AS "IVEXDJ"
			, "CALC_LOAD_END_DATE"."IVCITM" AS "IVCITM"
			, "CALC_LOAD_END_DATE"."IVCIRV" AS "IVCIRV"
			, "CALC_LOAD_END_DATE"."IVMCU" AS "IVMCU"
			, "CALC_LOAD_END_DATE"."IVEFTJ" AS "IVEFTJ"
			, "CALC_LOAD_END_DATE"."IVDSC1" AS "IVDSC1"
			, "CALC_LOAD_END_DATE"."IVDSC2" AS "IVDSC2"
			, "CALC_LOAD_END_DATE"."IVALN" AS "IVALN"
			, "CALC_LOAD_END_DATE"."IVLITM" AS "IVLITM"
			, "CALC_LOAD_END_DATE"."IVAITM" AS "IVAITM"
			, "CALC_LOAD_END_DATE"."IVURCD" AS "IVURCD"
			, "CALC_LOAD_END_DATE"."IVURDT" AS "IVURDT"
			, "CALC_LOAD_END_DATE"."IVURAT" AS "IVURAT"
			, "CALC_LOAD_END_DATE"."IVURAB" AS "IVURAB"
			, "CALC_LOAD_END_DATE"."IVURRF" AS "IVURRF"
			, "CALC_LOAD_END_DATE"."IVUSER" AS "IVUSER"
			, "CALC_LOAD_END_DATE"."IVPID" AS "IVPID"
			, "CALC_LOAD_END_DATE"."IVJOBN" AS "IVJOBN"
			, "CALC_LOAD_END_DATE"."IVUPMJ" AS "IVUPMJ"
			, "CALC_LOAD_END_DATE"."IVTDAY" AS "IVTDAY"
			, "CALC_LOAD_END_DATE"."IVRATO" AS "IVRATO"
			, "CALC_LOAD_END_DATE"."IVAPSP" AS "IVAPSP"
			, "CALC_LOAD_END_DATE"."IVIDEM" AS "IVIDEM"
			, "CALC_LOAD_END_DATE"."IVAPSS" AS "IVAPSS"
			, "CALC_LOAD_END_DATE"."IVADIND" AS "IVADIND"
			, "CALC_LOAD_END_DATE"."IVBPIND" AS "IVBPIND"
			, "CALC_LOAD_END_DATE"."IVCARDNO" AS "IVCARDNO"
		FROM "CALC_LOAD_END_DATE" "CALC_LOAD_END_DATE"
		WHERE  "CALC_LOAD_END_DATE"."DELETE_FLAG" = CAST('Y' AS VARCHAR) OR "CALC_LOAD_END_DATE"."SOURCE" = 'STG' OR("CALC_LOAD_END_DATE"."SOURCE" = 'SAT' AND "CALC_LOAD_END_DATE"."LOAD_END_DATE" != TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS'))
	)
	SELECT 
		  "FILTER_LOAD_END_DATE"."ITEMCROSSREFERENCE_HKEY"
		, "FILTER_LOAD_END_DATE"."LOAD_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_END_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_CYCLE_ID"
		, "FILTER_LOAD_END_DATE"."HASH_DIFF"
		, "FILTER_LOAD_END_DATE"."DELETE_FLAG"
		, "FILTER_LOAD_END_DATE"."CDC_TIMESTAMP"
		, "FILTER_LOAD_END_DATE"."IVAN8"
		, "FILTER_LOAD_END_DATE"."IVXRT"
		, "FILTER_LOAD_END_DATE"."IVITM"
		, "FILTER_LOAD_END_DATE"."IVEXDJ"
		, "FILTER_LOAD_END_DATE"."IVCITM"
		, "FILTER_LOAD_END_DATE"."IVCIRV"
		, "FILTER_LOAD_END_DATE"."IVMCU"
		, "FILTER_LOAD_END_DATE"."IVEFTJ"
		, "FILTER_LOAD_END_DATE"."IVDSC1"
		, "FILTER_LOAD_END_DATE"."IVDSC2"
		, "FILTER_LOAD_END_DATE"."IVALN"
		, "FILTER_LOAD_END_DATE"."IVLITM"
		, "FILTER_LOAD_END_DATE"."IVAITM"
		, "FILTER_LOAD_END_DATE"."IVURCD"
		, "FILTER_LOAD_END_DATE"."IVURDT"
		, "FILTER_LOAD_END_DATE"."IVURAT"
		, "FILTER_LOAD_END_DATE"."IVURAB"
		, "FILTER_LOAD_END_DATE"."IVURRF"
		, "FILTER_LOAD_END_DATE"."IVUSER"
		, "FILTER_LOAD_END_DATE"."IVPID"
		, "FILTER_LOAD_END_DATE"."IVJOBN"
		, "FILTER_LOAD_END_DATE"."IVUPMJ"
		, "FILTER_LOAD_END_DATE"."IVTDAY"
		, "FILTER_LOAD_END_DATE"."IVRATO"
		, "FILTER_LOAD_END_DATE"."IVAPSP"
		, "FILTER_LOAD_END_DATE"."IVIDEM"
		, "FILTER_LOAD_END_DATE"."IVAPSS"
		, "FILTER_LOAD_END_DATE"."IVADIND"
		, "FILTER_LOAD_END_DATE"."IVBPIND"
		, "FILTER_LOAD_END_DATE"."IVCARDNO"
	FROM "FILTER_LOAD_END_DATE"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "STG_SRC" AS 
	( 
		SELECT 
			  "STG_INR_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "STG_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVEFTJ")),'~'),'\#','\\' || 
				'\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVDSC1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVDSC2"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVALN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVLITM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVAITM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVURCD"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVURDT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVURAT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVURAB")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVURRF"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVTDAY")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVRATO")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."IVAPSP")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVIDEM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVAPSS"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVADIND"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVBPIND"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."IVCARDNO"),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_INR_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_INR_SRC"."IVAN8" AS "IVAN8"
			, "STG_INR_SRC"."IVXRT" AS "IVXRT"
			, "STG_INR_SRC"."IVITM" AS "IVITM"
			, "STG_INR_SRC"."IVEXDJ" AS "IVEXDJ"
			, "STG_INR_SRC"."IVCITM" AS "IVCITM"
			, "STG_INR_SRC"."IVCIRV" AS "IVCIRV"
			, "STG_INR_SRC"."IVMCU" AS "IVMCU"
			, "STG_INR_SRC"."IVEFTJ" AS "IVEFTJ"
			, "STG_INR_SRC"."IVDSC1" AS "IVDSC1"
			, "STG_INR_SRC"."IVDSC2" AS "IVDSC2"
			, "STG_INR_SRC"."IVALN" AS "IVALN"
			, "STG_INR_SRC"."IVLITM" AS "IVLITM"
			, "STG_INR_SRC"."IVAITM" AS "IVAITM"
			, "STG_INR_SRC"."IVURCD" AS "IVURCD"
			, "STG_INR_SRC"."IVURDT" AS "IVURDT"
			, "STG_INR_SRC"."IVURAT" AS "IVURAT"
			, "STG_INR_SRC"."IVURAB" AS "IVURAB"
			, "STG_INR_SRC"."IVURRF" AS "IVURRF"
			, "STG_INR_SRC"."IVUSER" AS "IVUSER"
			, "STG_INR_SRC"."IVPID" AS "IVPID"
			, "STG_INR_SRC"."IVJOBN" AS "IVJOBN"
			, "STG_INR_SRC"."IVUPMJ" AS "IVUPMJ"
			, "STG_INR_SRC"."IVTDAY" AS "IVTDAY"
			, "STG_INR_SRC"."IVRATO" AS "IVRATO"
			, "STG_INR_SRC"."IVAPSP" AS "IVAPSP"
			, "STG_INR_SRC"."IVIDEM" AS "IVIDEM"
			, "STG_INR_SRC"."IVAPSS" AS "IVAPSS"
			, "STG_INR_SRC"."IVADIND" AS "IVADIND"
			, "STG_INR_SRC"."IVBPIND" AS "IVBPIND"
			, "STG_INR_SRC"."IVCARDNO" AS "IVCARDNO"
			, ROW_NUMBER()OVER(PARTITION BY "STG_INR_SRC"."ITEMCROSSREFERENCE_HKEY" ORDER BY "STG_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('JDEDWARDS_STG_F4104') }} "STG_INR_SRC"
	)
	SELECT 
		  "STG_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
		, "STG_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "STG_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "STG_SRC"."IVAN8" AS "IVAN8"
		, "STG_SRC"."IVXRT" AS "IVXRT"
		, "STG_SRC"."IVITM" AS "IVITM"
		, "STG_SRC"."IVEXDJ" AS "IVEXDJ"
		, "STG_SRC"."IVCITM" AS "IVCITM"
		, "STG_SRC"."IVCIRV" AS "IVCIRV"
		, "STG_SRC"."IVMCU" AS "IVMCU"
		, "STG_SRC"."IVEFTJ" AS "IVEFTJ"
		, "STG_SRC"."IVDSC1" AS "IVDSC1"
		, "STG_SRC"."IVDSC2" AS "IVDSC2"
		, "STG_SRC"."IVALN" AS "IVALN"
		, "STG_SRC"."IVLITM" AS "IVLITM"
		, "STG_SRC"."IVAITM" AS "IVAITM"
		, "STG_SRC"."IVURCD" AS "IVURCD"
		, "STG_SRC"."IVURDT" AS "IVURDT"
		, "STG_SRC"."IVURAT" AS "IVURAT"
		, "STG_SRC"."IVURAB" AS "IVURAB"
		, "STG_SRC"."IVURRF" AS "IVURRF"
		, "STG_SRC"."IVUSER" AS "IVUSER"
		, "STG_SRC"."IVPID" AS "IVPID"
		, "STG_SRC"."IVJOBN" AS "IVJOBN"
		, "STG_SRC"."IVUPMJ" AS "IVUPMJ"
		, "STG_SRC"."IVTDAY" AS "IVTDAY"
		, "STG_SRC"."IVRATO" AS "IVRATO"
		, "STG_SRC"."IVAPSP" AS "IVAPSP"
		, "STG_SRC"."IVIDEM" AS "IVIDEM"
		, "STG_SRC"."IVAPSS" AS "IVAPSS"
		, "STG_SRC"."IVADIND" AS "IVADIND"
		, "STG_SRC"."IVBPIND" AS "IVBPIND"
		, "STG_SRC"."IVCARDNO" AS "IVCARDNO"
	FROM "STG_SRC" "STG_SRC"
	WHERE  "STG_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'