{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='HUB_ITEMCOST',
		schema='DEMO_FL',
		unique_key = ['"ITEMCOST_HKEY"'],
		merge_update_columns = [],
		tags=['JDEDWARDS', 'HUB_JDE_ITEMCOST_INCR', 'HUB_JDE_ITEMCOST_INIT']
	)
}}
select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."COITM_BK" AS "COITM_BK"
			, "STG_SRC1"."COMCU_BK" AS "COMCU_BK"
			, "STG_SRC1"."COLOCN_BK" AS "COLOCN_BK"
			, "STG_SRC1"."COLOTN_BK" AS "COLOTN_BK"
			, "STG_SRC1"."COLEDG_BK" AS "COLEDG_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F4105') }} "STG_SRC1"
		WHERE  "STG_SRC1"."RECORD_TYPE" = 'S'
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."COITM_BK" AS "COITM_BK"
			, "CHANGE_SET"."COMCU_BK" AS "COMCU_BK"
			, "CHANGE_SET"."COLOCN_BK" AS "COLOCN_BK"
			, "CHANGE_SET"."COLOTN_BK" AS "COLOTN_BK"
			, "CHANGE_SET"."COLEDG_BK" AS "COLEDG_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."ITEMCOST_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	, "MIV" AS 
	( 
		SELECT 
			  "MIN_LOAD_TIME"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
			, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "MIN_LOAD_TIME"."COITM_BK" AS "COITM_BK"
			, "MIN_LOAD_TIME"."COMCU_BK" AS "COMCU_BK"
			, "MIN_LOAD_TIME"."COLOCN_BK" AS "COLOCN_BK"
			, "MIN_LOAD_TIME"."COLOTN_BK" AS "COLOTN_BK"
			, "MIN_LOAD_TIME"."COLEDG_BK" AS "COLEDG_BK"
		FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
		WHERE  "MIN_LOAD_TIME"."DUMMY" = 1
	)
	SELECT 
		  "MIV"."ITEMCOST_HKEY"
		, "MIV"."LOAD_DATE"
		, "MIV"."LOAD_CYCLE_ID"
		, "MIV"."COITM_BK"
		, "MIV"."COMCU_BK"
		, "MIV"."COLOCN_BK"
		, "MIV"."COLOTN_BK"
		, "MIV"."COLEDG_BK"
	FROM "MIV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."COITM_BK" AS "COITM_BK"
			, "STG_SRC1"."COMCU_BK" AS "COMCU_BK"
			, "STG_SRC1"."COLOCN_BK" AS "COLOCN_BK"
			, "STG_SRC1"."COLOTN_BK" AS "COLOTN_BK"
			, "STG_SRC1"."COLEDG_BK" AS "COLEDG_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F4105') }} "STG_SRC1"
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."COITM_BK" AS "COITM_BK"
			, "CHANGE_SET"."COMCU_BK" AS "COMCU_BK"
			, "CHANGE_SET"."COLOCN_BK" AS "COLOCN_BK"
			, "CHANGE_SET"."COLOTN_BK" AS "COLOTN_BK"
			, "CHANGE_SET"."COLEDG_BK" AS "COLEDG_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."ITEMCOST_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	SELECT 
		  "MIN_LOAD_TIME"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
		, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
		, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIN_LOAD_TIME"."COITM_BK" AS "COITM_BK"
		, "MIN_LOAD_TIME"."COMCU_BK" AS "COMCU_BK"
		, "MIN_LOAD_TIME"."COLOCN_BK" AS "COLOCN_BK"
		, "MIN_LOAD_TIME"."COLOTN_BK" AS "COLOTN_BK"
		, "MIN_LOAD_TIME"."COLEDG_BK" AS "COLEDG_BK"
	FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
	WHERE  "MIN_LOAD_TIME"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'