{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_SALESFORCE_PRODUCT',
		schema='DEMO_FL',
		unique_key = ['"PRODUCT_HKEY"', '"LOAD_DATE"'],
		merge_update_columns = ['"LOAD_END_DATE"', '"DELETE_FLAG"', '"CDC_TIMESTAMP"'],
		tags=['SALESFORCE', 'SAT_SALESFORCE_PRODUCT_INCR', 'SAT_SALESFORCE_PRODUCT_INIT']
	)
}}
select * from (
	WITH "END_DATING" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_DK"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "SAT_TEMP_SRC_DK"."LOAD_DATE" AS "LOAD_DATE"
			, CASE WHEN LEAD( "SAT_TEMP_SRC_DK"."DELETE_FLAG" || "SAT_TEMP_SRC_DK"."SOURCE",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."PRODUCT_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE",
				"SAT_TEMP_SRC_DK"."LOAD_CYCLE_ID")= 'Y' || 'STG' THEN CAST('Y' AS VARCHAR) ELSE "SAT_TEMP_SRC_DK"."DELETE_FLAG" END AS "DELETE_FLAG"
			, LEAD("SAT_TEMP_SRC_DK"."CDC_TIMESTAMP",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."PRODUCT_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE") AS "CDC_TIMESTAMP"
		FROM {{ ref('SALESFORCE_STG_SAT_SALESFORCE_PRODUCT_TMP') }} "SAT_TEMP_SRC_DK"
		WHERE  "SAT_TEMP_SRC_DK"."EQUAL" = 0
	)
	, "CALC_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_US"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "SAT_TEMP_SRC_US"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_TEMP_SRC_US"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, COALESCE(LEAD("SAT_TEMP_SRC_US"."LOAD_DATE",1)OVER(PARTITION BY "SAT_TEMP_SRC_US"."PRODUCT_HKEY" ORDER BY "SAT_TEMP_SRC_US"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "END_DATING"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_TEMP_SRC_US"."SOURCE" AS "SOURCE"
			, "SAT_TEMP_SRC_US"."HASH_DIFF" AS "HASH_DIFF"
			, CASE WHEN "END_DATING"."DELETE_FLAG" = CAST('Y' AS VARCHAR) THEN "END_DATING"."CDC_TIMESTAMP" ELSE "SAT_TEMP_SRC_US"."CDC_TIMESTAMP" END AS "CDC_TIMESTAMP"
			, "SAT_TEMP_SRC_US"."ID" AS "ID"
			, "SAT_TEMP_SRC_US"."CREATEDBYID" AS "CREATEDBYID"
			, "SAT_TEMP_SRC_US"."NAME" AS "NAME"
			, "SAT_TEMP_SRC_US"."PRODUCTCODE" AS "PRODUCTCODE"
			, "SAT_TEMP_SRC_US"."DESCRIPTION" AS "DESCRIPTION"
			, "SAT_TEMP_SRC_US"."ISACTIVE" AS "ISACTIVE"
			, "SAT_TEMP_SRC_US"."CREATEDDATE" AS "CREATEDDATE"
			, "SAT_TEMP_SRC_US"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "SAT_TEMP_SRC_US"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "SAT_TEMP_SRC_US"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "SAT_TEMP_SRC_US"."FAMILY" AS "FAMILY"
			, "SAT_TEMP_SRC_US"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "SAT_TEMP_SRC_US"."EXTERNALID" AS "EXTERNALID"
			, "SAT_TEMP_SRC_US"."DISPLAYURL" AS "DISPLAYURL"
			, "SAT_TEMP_SRC_US"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "SAT_TEMP_SRC_US"."ISDELETED" AS "ISDELETED"
			, "SAT_TEMP_SRC_US"."ISARCHIVED" AS "ISARCHIVED"
			, "SAT_TEMP_SRC_US"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		FROM {{ ref('SALESFORCE_STG_SAT_SALESFORCE_PRODUCT_TMP') }} "SAT_TEMP_SRC_US"
		INNER JOIN "END_DATING" "END_DATING" ON  "SAT_TEMP_SRC_US"."PRODUCT_HKEY" = "END_DATING"."PRODUCT_HKEY" AND "SAT_TEMP_SRC_US"."LOAD_DATE" = 
			"END_DATING"."LOAD_DATE"
		WHERE  "SAT_TEMP_SRC_US"."EQUAL" = 0 AND NOT("SAT_TEMP_SRC_US"."DELETE_FLAG" = CAST('Y' AS VARCHAR) AND "SAT_TEMP_SRC_US"."SOURCE" = 'STG')
	)
	, "FILTER_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "CALC_LOAD_END_DATE"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "CALC_LOAD_END_DATE"."LOAD_DATE" AS "LOAD_DATE"
			, "CALC_LOAD_END_DATE"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALC_LOAD_END_DATE"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, "CALC_LOAD_END_DATE"."DELETE_FLAG" AS "DELETE_FLAG"
			, "CALC_LOAD_END_DATE"."HASH_DIFF" AS "HASH_DIFF"
			, "CALC_LOAD_END_DATE"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALC_LOAD_END_DATE"."ID" AS "ID"
			, "CALC_LOAD_END_DATE"."CREATEDBYID" AS "CREATEDBYID"
			, "CALC_LOAD_END_DATE"."NAME" AS "NAME"
			, "CALC_LOAD_END_DATE"."PRODUCTCODE" AS "PRODUCTCODE"
			, "CALC_LOAD_END_DATE"."DESCRIPTION" AS "DESCRIPTION"
			, "CALC_LOAD_END_DATE"."ISACTIVE" AS "ISACTIVE"
			, "CALC_LOAD_END_DATE"."CREATEDDATE" AS "CREATEDDATE"
			, "CALC_LOAD_END_DATE"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "CALC_LOAD_END_DATE"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "CALC_LOAD_END_DATE"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "CALC_LOAD_END_DATE"."FAMILY" AS "FAMILY"
			, "CALC_LOAD_END_DATE"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "CALC_LOAD_END_DATE"."EXTERNALID" AS "EXTERNALID"
			, "CALC_LOAD_END_DATE"."DISPLAYURL" AS "DISPLAYURL"
			, "CALC_LOAD_END_DATE"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "CALC_LOAD_END_DATE"."ISDELETED" AS "ISDELETED"
			, "CALC_LOAD_END_DATE"."ISARCHIVED" AS "ISARCHIVED"
			, "CALC_LOAD_END_DATE"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
		FROM "CALC_LOAD_END_DATE" "CALC_LOAD_END_DATE"
		WHERE  "CALC_LOAD_END_DATE"."DELETE_FLAG" = CAST('Y' AS VARCHAR) OR "CALC_LOAD_END_DATE"."SOURCE" = 'STG' OR("CALC_LOAD_END_DATE"."SOURCE" = 'SAT' AND "CALC_LOAD_END_DATE"."LOAD_END_DATE" != TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS'))
	)
	SELECT 
		  "FILTER_LOAD_END_DATE"."PRODUCT_HKEY"
		, "FILTER_LOAD_END_DATE"."LOAD_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_END_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_CYCLE_ID"
		, "FILTER_LOAD_END_DATE"."HASH_DIFF"
		, "FILTER_LOAD_END_DATE"."DELETE_FLAG"
		, "FILTER_LOAD_END_DATE"."CDC_TIMESTAMP"
		, "FILTER_LOAD_END_DATE"."ID"
		, "FILTER_LOAD_END_DATE"."CREATEDBYID"
		, "FILTER_LOAD_END_DATE"."NAME"
		, "FILTER_LOAD_END_DATE"."PRODUCTCODE"
		, "FILTER_LOAD_END_DATE"."DESCRIPTION"
		, "FILTER_LOAD_END_DATE"."ISACTIVE"
		, "FILTER_LOAD_END_DATE"."CREATEDDATE"
		, "FILTER_LOAD_END_DATE"."LASTMODIFIEDDATE"
		, "FILTER_LOAD_END_DATE"."LASTMODIFIEDBYID"
		, "FILTER_LOAD_END_DATE"."SYSTEMMODSTAMP"
		, "FILTER_LOAD_END_DATE"."FAMILY"
		, "FILTER_LOAD_END_DATE"."EXTERNALDATASOURCEID"
		, "FILTER_LOAD_END_DATE"."EXTERNALID"
		, "FILTER_LOAD_END_DATE"."DISPLAYURL"
		, "FILTER_LOAD_END_DATE"."QUANTITYUNITOFMEASURE"
		, "FILTER_LOAD_END_DATE"."ISDELETED"
		, "FILTER_LOAD_END_DATE"."ISARCHIVED"
		, "FILTER_LOAD_END_DATE"."STOCKKEEPINGUNIT"
	FROM "FILTER_LOAD_END_DATE"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	WITH "STG_SRC" AS 
	( 
		SELECT 
			  "STG_INR_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "STG_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."NAME"),'~'),'\#','\\' || '\#'))|| 
				'\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."PRODUCTCODE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."DESCRIPTION"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."ISACTIVE")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."CREATEDDATE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."LASTMODIFIEDDATE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."LASTMODIFIEDBYID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."SYSTEMMODSTAMP"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."FAMILY"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EXTERNALDATASOURCEID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EXTERNALID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."DISPLAYURL"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."QUANTITYUNITOFMEASURE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."ISDELETED")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."ISARCHIVED")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."STOCKKEEPINGUNIT"),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_INR_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_INR_SRC"."ID" AS "ID"
			, "STG_INR_SRC"."CREATEDBYID" AS "CREATEDBYID"
			, "STG_INR_SRC"."NAME" AS "NAME"
			, "STG_INR_SRC"."PRODUCTCODE" AS "PRODUCTCODE"
			, "STG_INR_SRC"."DESCRIPTION" AS "DESCRIPTION"
			, "STG_INR_SRC"."ISACTIVE" AS "ISACTIVE"
			, "STG_INR_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "STG_INR_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "STG_INR_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "STG_INR_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "STG_INR_SRC"."FAMILY" AS "FAMILY"
			, "STG_INR_SRC"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
			, "STG_INR_SRC"."EXTERNALID" AS "EXTERNALID"
			, "STG_INR_SRC"."DISPLAYURL" AS "DISPLAYURL"
			, "STG_INR_SRC"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
			, "STG_INR_SRC"."ISDELETED" AS "ISDELETED"
			, "STG_INR_SRC"."ISARCHIVED" AS "ISARCHIVED"
			, "STG_INR_SRC"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
			, ROW_NUMBER()OVER(PARTITION BY "STG_INR_SRC"."PRODUCT_HKEY" ORDER BY "STG_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('SALESFORCE_STG_PRODUCT2') }} "STG_INR_SRC"
	)
	SELECT 
		  "STG_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "STG_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "STG_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "STG_SRC"."ID" AS "ID"
		, "STG_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "STG_SRC"."NAME" AS "NAME"
		, "STG_SRC"."PRODUCTCODE" AS "PRODUCTCODE"
		, "STG_SRC"."DESCRIPTION" AS "DESCRIPTION"
		, "STG_SRC"."ISACTIVE" AS "ISACTIVE"
		, "STG_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "STG_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "STG_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "STG_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "STG_SRC"."FAMILY" AS "FAMILY"
		, "STG_SRC"."EXTERNALDATASOURCEID" AS "EXTERNALDATASOURCEID"
		, "STG_SRC"."EXTERNALID" AS "EXTERNALID"
		, "STG_SRC"."DISPLAYURL" AS "DISPLAYURL"
		, "STG_SRC"."QUANTITYUNITOFMEASURE" AS "QUANTITYUNITOFMEASURE"
		, "STG_SRC"."ISDELETED" AS "ISDELETED"
		, "STG_SRC"."ISARCHIVED" AS "ISARCHIVED"
		, "STG_SRC"."STOCKKEEPINGUNIT" AS "STOCKKEEPINGUNIT"
	FROM "STG_SRC" "STG_SRC"
	WHERE  "STG_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'