{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_SALESFORCE_CUSTOMER__C',
		schema='DEMO_FL',
		unique_key = ['"CUSTOMER__C_HKEY"', '"LOAD_DATE"'],
		merge_update_columns = ['"LOAD_END_DATE"', '"DELETE_FLAG"', '"CDC_TIMESTAMP"'],
		tags=['SALESFORCE', 'SAT_SALESFORCE_CUSTOMERC_INCR', 'SAT_SALESFORCE_CUSTOMERC_INIT']
	)
}}
select * from (
	WITH "END_DATING" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_DK"."CUSTOMER__C_HKEY" AS "CUSTOMER__C_HKEY"
			, "SAT_TEMP_SRC_DK"."LOAD_DATE" AS "LOAD_DATE"
			, CASE WHEN LEAD( "SAT_TEMP_SRC_DK"."DELETE_FLAG" || "SAT_TEMP_SRC_DK"."SOURCE",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."CUSTOMER__C_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE",
				"SAT_TEMP_SRC_DK"."LOAD_CYCLE_ID")= 'Y' || 'STG' THEN CAST('Y' AS VARCHAR) ELSE "SAT_TEMP_SRC_DK"."DELETE_FLAG" END AS "DELETE_FLAG"
			, LEAD("SAT_TEMP_SRC_DK"."CDC_TIMESTAMP",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."CUSTOMER__C_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE") AS "CDC_TIMESTAMP"
		FROM {{ ref('SALESFORCE_STG_SAT_SALESFORCE_CUSTOMER__C_TMP') }} "SAT_TEMP_SRC_DK"
		WHERE  "SAT_TEMP_SRC_DK"."EQUAL" = 0
	)
	, "CALC_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_US"."CUSTOMER__C_HKEY" AS "CUSTOMER__C_HKEY"
			, "SAT_TEMP_SRC_US"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_TEMP_SRC_US"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, COALESCE(LEAD("SAT_TEMP_SRC_US"."LOAD_DATE",1)OVER(PARTITION BY "SAT_TEMP_SRC_US"."CUSTOMER__C_HKEY" ORDER BY "SAT_TEMP_SRC_US"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "END_DATING"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_TEMP_SRC_US"."SOURCE" AS "SOURCE"
			, "SAT_TEMP_SRC_US"."HASH_DIFF" AS "HASH_DIFF"
			, CASE WHEN "END_DATING"."DELETE_FLAG" = CAST('Y' AS VARCHAR) THEN "END_DATING"."CDC_TIMESTAMP" ELSE "SAT_TEMP_SRC_US"."CDC_TIMESTAMP" END AS "CDC_TIMESTAMP"
			, "SAT_TEMP_SRC_US"."ID" AS "ID"
			, "SAT_TEMP_SRC_US"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "SAT_TEMP_SRC_US"."OWNERID" AS "OWNERID"
			, "SAT_TEMP_SRC_US"."CREATEDBYID" AS "CREATEDBYID"
			, "SAT_TEMP_SRC_US"."ISDELETED" AS "ISDELETED"
			, "SAT_TEMP_SRC_US"."NAME" AS "NAME"
			, "SAT_TEMP_SRC_US"."CREATEDDATE" AS "CREATEDDATE"
			, "SAT_TEMP_SRC_US"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "SAT_TEMP_SRC_US"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "SAT_TEMP_SRC_US"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
			, "SAT_TEMP_SRC_US"."GENDER__C" AS "GENDER__C"
			, "SAT_TEMP_SRC_US"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
			, "SAT_TEMP_SRC_US"."PARTNER__C" AS "PARTNER__C"
			, "SAT_TEMP_SRC_US"."DEPENDENTS__C" AS "DEPENDENTS__C"
			, "SAT_TEMP_SRC_US"."TENURE__C" AS "TENURE__C"
			, "SAT_TEMP_SRC_US"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
			, "SAT_TEMP_SRC_US"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
			, "SAT_TEMP_SRC_US"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
			, "SAT_TEMP_SRC_US"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
			, "SAT_TEMP_SRC_US"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
			, "SAT_TEMP_SRC_US"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
			, "SAT_TEMP_SRC_US"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
			, "SAT_TEMP_SRC_US"."STREAMING_TV__C" AS "STREAMING_TV__C"
			, "SAT_TEMP_SRC_US"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
			, "SAT_TEMP_SRC_US"."CONTRACT__C" AS "CONTRACT__C"
			, "SAT_TEMP_SRC_US"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
			, "SAT_TEMP_SRC_US"."CHURN__C" AS "CHURN__C"
			, "SAT_TEMP_SRC_US"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
		FROM {{ ref('SALESFORCE_STG_SAT_SALESFORCE_CUSTOMER__C_TMP') }} "SAT_TEMP_SRC_US"
		INNER JOIN "END_DATING" "END_DATING" ON  "SAT_TEMP_SRC_US"."CUSTOMER__C_HKEY" = "END_DATING"."CUSTOMER__C_HKEY" AND "SAT_TEMP_SRC_US"."LOAD_DATE" = 
			"END_DATING"."LOAD_DATE"
		WHERE  "SAT_TEMP_SRC_US"."EQUAL" = 0 AND NOT("SAT_TEMP_SRC_US"."DELETE_FLAG" = CAST('Y' AS VARCHAR) AND "SAT_TEMP_SRC_US"."SOURCE" = 'STG')
	)
	, "FILTER_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "CALC_LOAD_END_DATE"."CUSTOMER__C_HKEY" AS "CUSTOMER__C_HKEY"
			, "CALC_LOAD_END_DATE"."LOAD_DATE" AS "LOAD_DATE"
			, "CALC_LOAD_END_DATE"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALC_LOAD_END_DATE"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, "CALC_LOAD_END_DATE"."DELETE_FLAG" AS "DELETE_FLAG"
			, "CALC_LOAD_END_DATE"."HASH_DIFF" AS "HASH_DIFF"
			, "CALC_LOAD_END_DATE"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALC_LOAD_END_DATE"."ID" AS "ID"
			, "CALC_LOAD_END_DATE"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "CALC_LOAD_END_DATE"."OWNERID" AS "OWNERID"
			, "CALC_LOAD_END_DATE"."CREATEDBYID" AS "CREATEDBYID"
			, "CALC_LOAD_END_DATE"."ISDELETED" AS "ISDELETED"
			, "CALC_LOAD_END_DATE"."NAME" AS "NAME"
			, "CALC_LOAD_END_DATE"."CREATEDDATE" AS "CREATEDDATE"
			, "CALC_LOAD_END_DATE"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "CALC_LOAD_END_DATE"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "CALC_LOAD_END_DATE"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
			, "CALC_LOAD_END_DATE"."GENDER__C" AS "GENDER__C"
			, "CALC_LOAD_END_DATE"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
			, "CALC_LOAD_END_DATE"."PARTNER__C" AS "PARTNER__C"
			, "CALC_LOAD_END_DATE"."DEPENDENTS__C" AS "DEPENDENTS__C"
			, "CALC_LOAD_END_DATE"."TENURE__C" AS "TENURE__C"
			, "CALC_LOAD_END_DATE"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
			, "CALC_LOAD_END_DATE"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
			, "CALC_LOAD_END_DATE"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
			, "CALC_LOAD_END_DATE"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
			, "CALC_LOAD_END_DATE"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
			, "CALC_LOAD_END_DATE"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
			, "CALC_LOAD_END_DATE"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
			, "CALC_LOAD_END_DATE"."STREAMING_TV__C" AS "STREAMING_TV__C"
			, "CALC_LOAD_END_DATE"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
			, "CALC_LOAD_END_DATE"."CONTRACT__C" AS "CONTRACT__C"
			, "CALC_LOAD_END_DATE"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
			, "CALC_LOAD_END_DATE"."CHURN__C" AS "CHURN__C"
			, "CALC_LOAD_END_DATE"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
		FROM "CALC_LOAD_END_DATE" "CALC_LOAD_END_DATE"
		WHERE  "CALC_LOAD_END_DATE"."DELETE_FLAG" = CAST('Y' AS VARCHAR) OR "CALC_LOAD_END_DATE"."SOURCE" = 'STG' OR("CALC_LOAD_END_DATE"."SOURCE" = 'SAT' AND "CALC_LOAD_END_DATE"."LOAD_END_DATE" != TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS'))
	)
	SELECT 
		  "FILTER_LOAD_END_DATE"."CUSTOMER__C_HKEY"
		, "FILTER_LOAD_END_DATE"."LOAD_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_END_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_CYCLE_ID"
		, "FILTER_LOAD_END_DATE"."HASH_DIFF"
		, "FILTER_LOAD_END_DATE"."DELETE_FLAG"
		, "FILTER_LOAD_END_DATE"."CDC_TIMESTAMP"
		, "FILTER_LOAD_END_DATE"."ID"
		, "FILTER_LOAD_END_DATE"."LASTMODIFIEDBYID"
		, "FILTER_LOAD_END_DATE"."OWNERID"
		, "FILTER_LOAD_END_DATE"."CREATEDBYID"
		, "FILTER_LOAD_END_DATE"."ISDELETED"
		, "FILTER_LOAD_END_DATE"."NAME"
		, "FILTER_LOAD_END_DATE"."CREATEDDATE"
		, "FILTER_LOAD_END_DATE"."LASTMODIFIEDDATE"
		, "FILTER_LOAD_END_DATE"."SYSTEMMODSTAMP"
		, "FILTER_LOAD_END_DATE"."CUSTOMER_ID__C"
		, "FILTER_LOAD_END_DATE"."GENDER__C"
		, "FILTER_LOAD_END_DATE"."SENIOR_CITIZEN__C"
		, "FILTER_LOAD_END_DATE"."PARTNER__C"
		, "FILTER_LOAD_END_DATE"."DEPENDENTS__C"
		, "FILTER_LOAD_END_DATE"."TENURE__C"
		, "FILTER_LOAD_END_DATE"."PHONE_SERVICE__C"
		, "FILTER_LOAD_END_DATE"."MULTIPLE_LINES__C"
		, "FILTER_LOAD_END_DATE"."INTERNET_SERVICE__C"
		, "FILTER_LOAD_END_DATE"."ONLINE_SECURITY__C"
		, "FILTER_LOAD_END_DATE"."ONLINE_BACKUP__C"
		, "FILTER_LOAD_END_DATE"."DEVICE_PROTECTION__C"
		, "FILTER_LOAD_END_DATE"."TECH_SUPPORT__C"
		, "FILTER_LOAD_END_DATE"."STREAMING_TV__C"
		, "FILTER_LOAD_END_DATE"."STREAMING_MOVIES__C"
		, "FILTER_LOAD_END_DATE"."CONTRACT__C"
		, "FILTER_LOAD_END_DATE"."PAPERLESS_BILLING__C"
		, "FILTER_LOAD_END_DATE"."CHURN__C"
		, "FILTER_LOAD_END_DATE"."PAYMENT_METHOD__C"
	FROM "FILTER_LOAD_END_DATE"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	WITH "STG_SRC" AS 
	( 
		SELECT 
			  "STG_INR_SRC"."CUSTOMER__C_HKEY" AS "CUSTOMER__C_HKEY"
			, "STG_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."ISDELETED")),'~'),'\#',
				'\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."NAME"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."CREATEDDATE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."LASTMODIFIEDDATE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."SYSTEMMODSTAMP"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."CUSTOMER_ID__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."GENDER__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."SENIOR_CITIZEN__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."PARTNER__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."DEPENDENTS__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."TENURE__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."PHONE_SERVICE__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."MULTIPLE_LINES__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."INTERNET_SERVICE__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."ONLINE_SECURITY__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."ONLINE_BACKUP__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."DEVICE_PROTECTION__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."TECH_SUPPORT__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."STREAMING_TV__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."STREAMING_MOVIES__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."CONTRACT__C"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."PAPERLESS_BILLING__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."CHURN__C")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."PAYMENT_METHOD__C"),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_INR_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_INR_SRC"."ID" AS "ID"
			, "STG_INR_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "STG_INR_SRC"."OWNERID" AS "OWNERID"
			, "STG_INR_SRC"."CREATEDBYID" AS "CREATEDBYID"
			, "STG_INR_SRC"."ISDELETED" AS "ISDELETED"
			, "STG_INR_SRC"."NAME" AS "NAME"
			, "STG_INR_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "STG_INR_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "STG_INR_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "STG_INR_SRC"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
			, "STG_INR_SRC"."GENDER__C" AS "GENDER__C"
			, "STG_INR_SRC"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
			, "STG_INR_SRC"."PARTNER__C" AS "PARTNER__C"
			, "STG_INR_SRC"."DEPENDENTS__C" AS "DEPENDENTS__C"
			, "STG_INR_SRC"."TENURE__C" AS "TENURE__C"
			, "STG_INR_SRC"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
			, "STG_INR_SRC"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
			, "STG_INR_SRC"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
			, "STG_INR_SRC"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
			, "STG_INR_SRC"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
			, "STG_INR_SRC"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
			, "STG_INR_SRC"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
			, "STG_INR_SRC"."STREAMING_TV__C" AS "STREAMING_TV__C"
			, "STG_INR_SRC"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
			, "STG_INR_SRC"."CONTRACT__C" AS "CONTRACT__C"
			, "STG_INR_SRC"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
			, "STG_INR_SRC"."CHURN__C" AS "CHURN__C"
			, "STG_INR_SRC"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
			, ROW_NUMBER()OVER(PARTITION BY "STG_INR_SRC"."CUSTOMER__C_HKEY" ORDER BY "STG_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('SALESFORCE_STG_CUSTOMER__C') }} "STG_INR_SRC"
	)
	SELECT 
		  "STG_SRC"."CUSTOMER__C_HKEY" AS "CUSTOMER__C_HKEY"
		, "STG_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "STG_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "STG_SRC"."ID" AS "ID"
		, "STG_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "STG_SRC"."OWNERID" AS "OWNERID"
		, "STG_SRC"."CREATEDBYID" AS "CREATEDBYID"
		, "STG_SRC"."ISDELETED" AS "ISDELETED"
		, "STG_SRC"."NAME" AS "NAME"
		, "STG_SRC"."CREATEDDATE" AS "CREATEDDATE"
		, "STG_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "STG_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "STG_SRC"."CUSTOMER_ID__C" AS "CUSTOMER_ID__C"
		, "STG_SRC"."GENDER__C" AS "GENDER__C"
		, "STG_SRC"."SENIOR_CITIZEN__C" AS "SENIOR_CITIZEN__C"
		, "STG_SRC"."PARTNER__C" AS "PARTNER__C"
		, "STG_SRC"."DEPENDENTS__C" AS "DEPENDENTS__C"
		, "STG_SRC"."TENURE__C" AS "TENURE__C"
		, "STG_SRC"."PHONE_SERVICE__C" AS "PHONE_SERVICE__C"
		, "STG_SRC"."MULTIPLE_LINES__C" AS "MULTIPLE_LINES__C"
		, "STG_SRC"."INTERNET_SERVICE__C" AS "INTERNET_SERVICE__C"
		, "STG_SRC"."ONLINE_SECURITY__C" AS "ONLINE_SECURITY__C"
		, "STG_SRC"."ONLINE_BACKUP__C" AS "ONLINE_BACKUP__C"
		, "STG_SRC"."DEVICE_PROTECTION__C" AS "DEVICE_PROTECTION__C"
		, "STG_SRC"."TECH_SUPPORT__C" AS "TECH_SUPPORT__C"
		, "STG_SRC"."STREAMING_TV__C" AS "STREAMING_TV__C"
		, "STG_SRC"."STREAMING_MOVIES__C" AS "STREAMING_MOVIES__C"
		, "STG_SRC"."CONTRACT__C" AS "CONTRACT__C"
		, "STG_SRC"."PAPERLESS_BILLING__C" AS "PAPERLESS_BILLING__C"
		, "STG_SRC"."CHURN__C" AS "CHURN__C"
		, "STG_SRC"."PAYMENT_METHOD__C" AS "PAYMENT_METHOD__C"
	FROM "STG_SRC" "STG_SRC"
	WHERE  "STG_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'