{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='REF_JDE_TIME',
		schema='DEMO_FL',
		unique_key = ['"TDJDATE"'],
		merge_update_columns = ['"TDYRMNDY"', '"TDDAYNMBR"', '"TDMNTHNMBR"', '"TDCALQTR"', '"TDCQTRNMBR"', '"TDYEARNMBR"', '"TDWKNMBR"', '"TDDAYTEXT"', '"TDMNTHTEXT"', '"TDLSTDAYMN"', '"TDFISPER"', '"TDFISQTR"', '"TDFQTRNMBR"', '"TDFISYEAR"', '"TDFSPRTEXT"', '"TDLSTDAYFP"', '"LOAD_CYCLE_ID"', '"LOAD_DATE"'],
		tags=['JDEDWARDS', 'REF_JDE_TIME_INCR', 'REF_JDE_TIME_INIT']
	)
}}
select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "TDFV_MIV_SRC"."TDYRMNDY" AS "TDYRMNDY"
			, "TDFV_MIV_SRC"."TDDAYNMBR" AS "TDDAYNMBR"
			, "TDFV_MIV_SRC"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "TDFV_MIV_SRC"."TDCALQTR" AS "TDCALQTR"
			, "TDFV_MIV_SRC"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "TDFV_MIV_SRC"."TDYEARNMBR" AS "TDYEARNMBR"
			, "TDFV_MIV_SRC"."TDWKNMBR" AS "TDWKNMBR"
			, "TDFV_MIV_SRC"."TDDAYTEXT" AS "TDDAYTEXT"
			, "TDFV_MIV_SRC"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "TDFV_MIV_SRC"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "TDFV_MIV_SRC"."TDFISPER" AS "TDFISPER"
			, "TDFV_MIV_SRC"."TDFISQTR" AS "TDFISQTR"
			, "TDFV_MIV_SRC"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "TDFV_MIV_SRC"."TDFISYEAR" AS "TDFISYEAR"
			, "TDFV_MIV_SRC"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "TDFV_MIV_SRC"."TDLSTDAYFP" AS "TDLSTDAYFP"
			, "TDFV_MIV_SRC"."TDJDATE" AS "TDJDATE"
			, "TDFV_MIV_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, ROW_NUMBER()OVER(PARTITION BY "TDFV_MIV_SRC"."TDJDATE" ORDER BY "TDFV_MIV_SRC"."CDC_TIMESTAMP" DESC) AS "DUMMY"
		FROM {{ ref('JDEDWARDS_DFV_VW_F800010') }} "TDFV_MIV_SRC"
	)
	, "MIV" AS 
	( 
		SELECT 
			  "CHANGE_SET"."TDYRMNDY" AS "TDYRMNDY"
			, "CHANGE_SET"."TDDAYNMBR" AS "TDDAYNMBR"
			, "CHANGE_SET"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "CHANGE_SET"."TDCALQTR" AS "TDCALQTR"
			, "CHANGE_SET"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "CHANGE_SET"."TDYEARNMBR" AS "TDYEARNMBR"
			, "CHANGE_SET"."TDWKNMBR" AS "TDWKNMBR"
			, "CHANGE_SET"."TDDAYTEXT" AS "TDDAYTEXT"
			, "CHANGE_SET"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "CHANGE_SET"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "CHANGE_SET"."TDFISPER" AS "TDFISPER"
			, "CHANGE_SET"."TDFISQTR" AS "TDFISQTR"
			, "CHANGE_SET"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "CHANGE_SET"."TDFISYEAR" AS "TDFISYEAR"
			, "CHANGE_SET"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "CHANGE_SET"."TDLSTDAYFP" AS "TDLSTDAYFP"
			, "CHANGE_SET"."TDJDATE" AS "TDJDATE"
			, "LCI_MIV_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."CDC_TIMESTAMP" AS "LOAD_DATE"
		FROM "CHANGE_SET" "CHANGE_SET"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_MIV_SRC" ON  1 = 1
		WHERE  "CHANGE_SET"."DUMMY" = 1
	)
	SELECT 
		  "MIV"."TDJDATE"
		, "MIV"."LOAD_CYCLE_ID"
		, "MIV"."LOAD_DATE"
		, "MIV"."TDYRMNDY"
		, "MIV"."TDDAYNMBR"
		, "MIV"."TDMNTHNMBR"
		, "MIV"."TDCALQTR"
		, "MIV"."TDCQTRNMBR"
		, "MIV"."TDYEARNMBR"
		, "MIV"."TDWKNMBR"
		, "MIV"."TDDAYTEXT"
		, "MIV"."TDMNTHTEXT"
		, "MIV"."TDLSTDAYMN"
		, "MIV"."TDFISPER"
		, "MIV"."TDFISQTR"
		, "MIV"."TDFQTRNMBR"
		, "MIV"."TDFISYEAR"
		, "MIV"."TDFSPRTEXT"
		, "MIV"."TDLSTDAYFP"
	FROM "MIV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "PREP_EXCEP" AS 
	( 
		SELECT 
			  "INI_SRC"."TDJDATE" AS "TDJDATE"
			, NULL ::integer AS "LOAD_CYCLE_ID"
			, "INI_SRC"."TDYRMNDY" AS "TDYRMNDY"
			, "INI_SRC"."TDDAYNMBR" AS "TDDAYNMBR"
			, "INI_SRC"."TDMNTHNMBR" AS "TDMNTHNMBR"
			, "INI_SRC"."TDCALQTR" AS "TDCALQTR"
			, "INI_SRC"."TDCQTRNMBR" AS "TDCQTRNMBR"
			, "INI_SRC"."TDYEARNMBR" AS "TDYEARNMBR"
			, "INI_SRC"."TDWKNMBR" AS "TDWKNMBR"
			, "INI_SRC"."TDDAYTEXT" AS "TDDAYTEXT"
			, "INI_SRC"."TDMNTHTEXT" AS "TDMNTHTEXT"
			, "INI_SRC"."TDLSTDAYMN" AS "TDLSTDAYMN"
			, "INI_SRC"."TDFISPER" AS "TDFISPER"
			, "INI_SRC"."TDFISQTR" AS "TDFISQTR"
			, "INI_SRC"."TDFQTRNMBR" AS "TDFQTRNMBR"
			, "INI_SRC"."TDFISYEAR" AS "TDFISYEAR"
			, "INI_SRC"."TDFSPRTEXT" AS "TDFSPRTEXT"
			, "INI_SRC"."TDLSTDAYFP" AS "TDLSTDAYFP"
		FROM {{ source('JDEDWARDS_INI', 'F800010') }} "INI_SRC"
		UNION 
		SELECT 
			  CAST("MEX_EX_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT) AS "TDJDATE"
			, "MEX_EX_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDYRMNDY"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDDAYNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDMNTHNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDCALQTR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDCQTRNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDYEARNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDWKNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDDAYTEXT"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDMNTHTEXT"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDLSTDAYMN"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDFISPER"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDFISQTR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDFQTRNMBR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "TDFISYEAR"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDFSPRTEXT"
			, CAST("MEX_EX_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "TDLSTDAYFP"
		FROM {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EX_SRC"
	)
	SELECT 
		  "PREP_EXCEP"."TDJDATE" AS "TDJDATE"
		, COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
		, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "PREP_EXCEP"."TDYRMNDY" AS "TDYRMNDY"
		, "PREP_EXCEP"."TDDAYNMBR" AS "TDDAYNMBR"
		, "PREP_EXCEP"."TDMNTHNMBR" AS "TDMNTHNMBR"
		, "PREP_EXCEP"."TDCALQTR" AS "TDCALQTR"
		, "PREP_EXCEP"."TDCQTRNMBR" AS "TDCQTRNMBR"
		, "PREP_EXCEP"."TDYEARNMBR" AS "TDYEARNMBR"
		, "PREP_EXCEP"."TDWKNMBR" AS "TDWKNMBR"
		, "PREP_EXCEP"."TDDAYTEXT" AS "TDDAYTEXT"
		, "PREP_EXCEP"."TDMNTHTEXT" AS "TDMNTHTEXT"
		, "PREP_EXCEP"."TDLSTDAYMN" AS "TDLSTDAYMN"
		, "PREP_EXCEP"."TDFISPER" AS "TDFISPER"
		, "PREP_EXCEP"."TDFISQTR" AS "TDFISQTR"
		, "PREP_EXCEP"."TDFQTRNMBR" AS "TDFQTRNMBR"
		, "PREP_EXCEP"."TDFISYEAR" AS "TDFISYEAR"
		, "PREP_EXCEP"."TDFSPRTEXT" AS "TDFSPRTEXT"
		, "PREP_EXCEP"."TDLSTDAYFP" AS "TDLSTDAYFP"
	FROM "PREP_EXCEP" "PREP_EXCEP"
	INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'