{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='HUB_ITEMCROSSREFERENCE',
		schema='DEMO_FL',
		unique_key = ['"ITEMCROSSREFERENCE_HKEY"'],
		merge_update_columns = [],
		tags=['JDEDWARDS', 'HUB_JDE_ITEMCROSSREFERENCE_INCR', 'HUB_JDE_ITEMCROSSREFERENCE_INIT']
	)
}}
select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."IVITM_BK" AS "IVITM_BK"
			, "STG_SRC1"."IVXRT_BK" AS "IVXRT_BK"
			, "STG_SRC1"."IVAN8_BK" AS "IVAN8_BK"
			, "STG_SRC1"."IVCITM_BK" AS "IVCITM_BK"
			, "STG_SRC1"."IVEXDJ_BK" AS "IVEXDJ_BK"
			, "STG_SRC1"."IVCIRV_BK" AS "IVCIRV_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F4104') }} "STG_SRC1"
		WHERE  "STG_SRC1"."RECORD_TYPE" = 'S'
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."IVITM_BK" AS "IVITM_BK"
			, "CHANGE_SET"."IVXRT_BK" AS "IVXRT_BK"
			, "CHANGE_SET"."IVAN8_BK" AS "IVAN8_BK"
			, "CHANGE_SET"."IVCITM_BK" AS "IVCITM_BK"
			, "CHANGE_SET"."IVEXDJ_BK" AS "IVEXDJ_BK"
			, "CHANGE_SET"."IVCIRV_BK" AS "IVCIRV_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."ITEMCROSSREFERENCE_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	, "MIV" AS 
	( 
		SELECT 
			  "MIN_LOAD_TIME"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
			, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "MIN_LOAD_TIME"."IVITM_BK" AS "IVITM_BK"
			, "MIN_LOAD_TIME"."IVXRT_BK" AS "IVXRT_BK"
			, "MIN_LOAD_TIME"."IVAN8_BK" AS "IVAN8_BK"
			, "MIN_LOAD_TIME"."IVCITM_BK" AS "IVCITM_BK"
			, "MIN_LOAD_TIME"."IVEXDJ_BK" AS "IVEXDJ_BK"
			, "MIN_LOAD_TIME"."IVCIRV_BK" AS "IVCIRV_BK"
		FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
		WHERE  "MIN_LOAD_TIME"."DUMMY" = 1
	)
	SELECT 
		  "MIV"."ITEMCROSSREFERENCE_HKEY"
		, "MIV"."LOAD_DATE"
		, "MIV"."LOAD_CYCLE_ID"
		, "MIV"."IVITM_BK"
		, "MIV"."IVXRT_BK"
		, "MIV"."IVAN8_BK"
		, "MIV"."IVCITM_BK"
		, "MIV"."IVEXDJ_BK"
		, "MIV"."IVCIRV_BK"
	FROM "MIV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."IVITM_BK" AS "IVITM_BK"
			, "STG_SRC1"."IVXRT_BK" AS "IVXRT_BK"
			, "STG_SRC1"."IVAN8_BK" AS "IVAN8_BK"
			, "STG_SRC1"."IVCITM_BK" AS "IVCITM_BK"
			, "STG_SRC1"."IVEXDJ_BK" AS "IVEXDJ_BK"
			, "STG_SRC1"."IVCIRV_BK" AS "IVCIRV_BK"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('JDEDWARDS_STG_F4104') }} "STG_SRC1"
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."IVITM_BK" AS "IVITM_BK"
			, "CHANGE_SET"."IVXRT_BK" AS "IVXRT_BK"
			, "CHANGE_SET"."IVAN8_BK" AS "IVAN8_BK"
			, "CHANGE_SET"."IVCITM_BK" AS "IVCITM_BK"
			, "CHANGE_SET"."IVEXDJ_BK" AS "IVEXDJ_BK"
			, "CHANGE_SET"."IVCIRV_BK" AS "IVCIRV_BK"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."ITEMCROSSREFERENCE_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	SELECT 
		  "MIN_LOAD_TIME"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
		, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
		, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIN_LOAD_TIME"."IVITM_BK" AS "IVITM_BK"
		, "MIN_LOAD_TIME"."IVXRT_BK" AS "IVXRT_BK"
		, "MIN_LOAD_TIME"."IVAN8_BK" AS "IVAN8_BK"
		, "MIN_LOAD_TIME"."IVCITM_BK" AS "IVCITM_BK"
		, "MIN_LOAD_TIME"."IVEXDJ_BK" AS "IVEXDJ_BK"
		, "MIN_LOAD_TIME"."IVCIRV_BK" AS "IVCIRV_BK"
	FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
	WHERE  "MIN_LOAD_TIME"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'