{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_EMAIL',
		schema='DEMO_FL',
		unique_key = ['"EMAIL_HKEY"', '"LOAD_DATE"'],
		merge_update_columns = ['"LOAD_END_DATE"', '"DELETE_FLAG"', '"CDC_TIMESTAMP"'],
		tags=['JDEDWARDS', 'SAT_JDE_EMAIL_INCR', 'SAT_JDE_EMAIL_INIT']
	)
}}
select * from (
	WITH "END_DATING" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_DK"."EMAIL_HKEY" AS "EMAIL_HKEY"
			, "SAT_TEMP_SRC_DK"."LOAD_DATE" AS "LOAD_DATE"
			, CASE WHEN LEAD( "SAT_TEMP_SRC_DK"."DELETE_FLAG" || "SAT_TEMP_SRC_DK"."SOURCE",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."EMAIL_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE",
				"SAT_TEMP_SRC_DK"."LOAD_CYCLE_ID")= 'Y' || 'STG' THEN CAST('Y' AS VARCHAR) ELSE "SAT_TEMP_SRC_DK"."DELETE_FLAG" END AS "DELETE_FLAG"
			, LEAD("SAT_TEMP_SRC_DK"."CDC_TIMESTAMP",1)OVER(PARTITION BY "SAT_TEMP_SRC_DK"."EMAIL_HKEY" ORDER BY "SAT_TEMP_SRC_DK"."LOAD_DATE") AS "CDC_TIMESTAMP"
		FROM {{ ref('JDEDWARDS_STG_SAT_JDE_EMAIL_TMP') }} "SAT_TEMP_SRC_DK"
		WHERE  "SAT_TEMP_SRC_DK"."EQUAL" = 0
	)
	, "CALC_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "SAT_TEMP_SRC_US"."EMAIL_HKEY" AS "EMAIL_HKEY"
			, "SAT_TEMP_SRC_US"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_TEMP_SRC_US"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, COALESCE(LEAD("SAT_TEMP_SRC_US"."LOAD_DATE",1)OVER(PARTITION BY "SAT_TEMP_SRC_US"."EMAIL_HKEY" ORDER BY "SAT_TEMP_SRC_US"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "END_DATING"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_TEMP_SRC_US"."SOURCE" AS "SOURCE"
			, "SAT_TEMP_SRC_US"."HASH_DIFF" AS "HASH_DIFF"
			, CASE WHEN "END_DATING"."DELETE_FLAG" = CAST('Y' AS VARCHAR) THEN "END_DATING"."CDC_TIMESTAMP" ELSE "SAT_TEMP_SRC_US"."CDC_TIMESTAMP" END AS "CDC_TIMESTAMP"
			, "SAT_TEMP_SRC_US"."EAAN8" AS "EAAN8"
			, "SAT_TEMP_SRC_US"."EAIDLN" AS "EAIDLN"
			, "SAT_TEMP_SRC_US"."EARCK7" AS "EARCK7"
			, "SAT_TEMP_SRC_US"."EAETP" AS "EAETP"
			, "SAT_TEMP_SRC_US"."EAEMAL" AS "EAEMAL"
			, "SAT_TEMP_SRC_US"."EAUSER" AS "EAUSER"
			, "SAT_TEMP_SRC_US"."EAPID" AS "EAPID"
			, "SAT_TEMP_SRC_US"."EAUPMJ" AS "EAUPMJ"
			, "SAT_TEMP_SRC_US"."EAJOBN" AS "EAJOBN"
			, "SAT_TEMP_SRC_US"."EAUPMT" AS "EAUPMT"
			, "SAT_TEMP_SRC_US"."EAEHIER" AS "EAEHIER"
			, "SAT_TEMP_SRC_US"."EAEFOR" AS "EAEFOR"
			, "SAT_TEMP_SRC_US"."EAECLASS" AS "EAECLASS"
			, "SAT_TEMP_SRC_US"."EACFNO1" AS "EACFNO1"
			, "SAT_TEMP_SRC_US"."EAGEN1" AS "EAGEN1"
			, "SAT_TEMP_SRC_US"."EAFALGE" AS "EAFALGE"
			, "SAT_TEMP_SRC_US"."EASYNCS" AS "EASYNCS"
			, "SAT_TEMP_SRC_US"."EACAAD" AS "EACAAD"
		FROM {{ ref('JDEDWARDS_STG_SAT_JDE_EMAIL_TMP') }} "SAT_TEMP_SRC_US"
		INNER JOIN "END_DATING" "END_DATING" ON  "SAT_TEMP_SRC_US"."EMAIL_HKEY" = "END_DATING"."EMAIL_HKEY" AND "SAT_TEMP_SRC_US"."LOAD_DATE" = "END_DATING"."LOAD_DATE"
		WHERE  "SAT_TEMP_SRC_US"."EQUAL" = 0 AND NOT("SAT_TEMP_SRC_US"."DELETE_FLAG" = CAST('Y' AS VARCHAR) AND "SAT_TEMP_SRC_US"."SOURCE" = 'STG')
	)
	, "FILTER_LOAD_END_DATE" AS 
	( 
		SELECT 
			  "CALC_LOAD_END_DATE"."EMAIL_HKEY" AS "EMAIL_HKEY"
			, "CALC_LOAD_END_DATE"."LOAD_DATE" AS "LOAD_DATE"
			, "CALC_LOAD_END_DATE"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALC_LOAD_END_DATE"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, "CALC_LOAD_END_DATE"."DELETE_FLAG" AS "DELETE_FLAG"
			, "CALC_LOAD_END_DATE"."HASH_DIFF" AS "HASH_DIFF"
			, "CALC_LOAD_END_DATE"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALC_LOAD_END_DATE"."EAAN8" AS "EAAN8"
			, "CALC_LOAD_END_DATE"."EAIDLN" AS "EAIDLN"
			, "CALC_LOAD_END_DATE"."EARCK7" AS "EARCK7"
			, "CALC_LOAD_END_DATE"."EAETP" AS "EAETP"
			, "CALC_LOAD_END_DATE"."EAEMAL" AS "EAEMAL"
			, "CALC_LOAD_END_DATE"."EAUSER" AS "EAUSER"
			, "CALC_LOAD_END_DATE"."EAPID" AS "EAPID"
			, "CALC_LOAD_END_DATE"."EAUPMJ" AS "EAUPMJ"
			, "CALC_LOAD_END_DATE"."EAJOBN" AS "EAJOBN"
			, "CALC_LOAD_END_DATE"."EAUPMT" AS "EAUPMT"
			, "CALC_LOAD_END_DATE"."EAEHIER" AS "EAEHIER"
			, "CALC_LOAD_END_DATE"."EAEFOR" AS "EAEFOR"
			, "CALC_LOAD_END_DATE"."EAECLASS" AS "EAECLASS"
			, "CALC_LOAD_END_DATE"."EACFNO1" AS "EACFNO1"
			, "CALC_LOAD_END_DATE"."EAGEN1" AS "EAGEN1"
			, "CALC_LOAD_END_DATE"."EAFALGE" AS "EAFALGE"
			, "CALC_LOAD_END_DATE"."EASYNCS" AS "EASYNCS"
			, "CALC_LOAD_END_DATE"."EACAAD" AS "EACAAD"
		FROM "CALC_LOAD_END_DATE" "CALC_LOAD_END_DATE"
		WHERE  "CALC_LOAD_END_DATE"."DELETE_FLAG" = CAST('Y' AS VARCHAR) OR "CALC_LOAD_END_DATE"."SOURCE" = 'STG' OR("CALC_LOAD_END_DATE"."SOURCE" = 'SAT' AND "CALC_LOAD_END_DATE"."LOAD_END_DATE" != TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS'))
	)
	SELECT 
		  "FILTER_LOAD_END_DATE"."EMAIL_HKEY"
		, "FILTER_LOAD_END_DATE"."LOAD_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_END_DATE"
		, "FILTER_LOAD_END_DATE"."LOAD_CYCLE_ID"
		, "FILTER_LOAD_END_DATE"."HASH_DIFF"
		, "FILTER_LOAD_END_DATE"."DELETE_FLAG"
		, "FILTER_LOAD_END_DATE"."CDC_TIMESTAMP"
		, "FILTER_LOAD_END_DATE"."EAAN8"
		, "FILTER_LOAD_END_DATE"."EAIDLN"
		, "FILTER_LOAD_END_DATE"."EARCK7"
		, "FILTER_LOAD_END_DATE"."EAETP"
		, "FILTER_LOAD_END_DATE"."EAEMAL"
		, "FILTER_LOAD_END_DATE"."EAUSER"
		, "FILTER_LOAD_END_DATE"."EAPID"
		, "FILTER_LOAD_END_DATE"."EAUPMJ"
		, "FILTER_LOAD_END_DATE"."EAJOBN"
		, "FILTER_LOAD_END_DATE"."EAUPMT"
		, "FILTER_LOAD_END_DATE"."EAEHIER"
		, "FILTER_LOAD_END_DATE"."EAEFOR"
		, "FILTER_LOAD_END_DATE"."EAECLASS"
		, "FILTER_LOAD_END_DATE"."EACFNO1"
		, "FILTER_LOAD_END_DATE"."EAGEN1"
		, "FILTER_LOAD_END_DATE"."EAFALGE"
		, "FILTER_LOAD_END_DATE"."EASYNCS"
		, "FILTER_LOAD_END_DATE"."EACAAD"
	FROM "FILTER_LOAD_END_DATE"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "STG_SRC" AS 
	( 
		SELECT 
			  "STG_INR_SRC"."EMAIL_HKEY" AS "EMAIL_HKEY"
			, "STG_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAETP"),'~'),'\#','\\' || '\#'))
				|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAEMAL"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EAUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EAUPMT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EAEHIER")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAEFOR"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAECLASS"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EACFNO1")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAGEN1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_INR_SRC"."EAFALGE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EASYNCS")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."EACAAD")),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_INR_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_INR_SRC"."EAAN8" AS "EAAN8"
			, "STG_INR_SRC"."EAIDLN" AS "EAIDLN"
			, "STG_INR_SRC"."EARCK7" AS "EARCK7"
			, "STG_INR_SRC"."EAETP" AS "EAETP"
			, "STG_INR_SRC"."EAEMAL" AS "EAEMAL"
			, "STG_INR_SRC"."EAUSER" AS "EAUSER"
			, "STG_INR_SRC"."EAPID" AS "EAPID"
			, "STG_INR_SRC"."EAUPMJ" AS "EAUPMJ"
			, "STG_INR_SRC"."EAJOBN" AS "EAJOBN"
			, "STG_INR_SRC"."EAUPMT" AS "EAUPMT"
			, "STG_INR_SRC"."EAEHIER" AS "EAEHIER"
			, "STG_INR_SRC"."EAEFOR" AS "EAEFOR"
			, "STG_INR_SRC"."EAECLASS" AS "EAECLASS"
			, "STG_INR_SRC"."EACFNO1" AS "EACFNO1"
			, "STG_INR_SRC"."EAGEN1" AS "EAGEN1"
			, "STG_INR_SRC"."EAFALGE" AS "EAFALGE"
			, "STG_INR_SRC"."EASYNCS" AS "EASYNCS"
			, "STG_INR_SRC"."EACAAD" AS "EACAAD"
			, ROW_NUMBER()OVER(PARTITION BY "STG_INR_SRC"."EMAIL_HKEY" ORDER BY "STG_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('JDEDWARDS_STG_F01151') }} "STG_INR_SRC"
	)
	SELECT 
		  "STG_SRC"."EMAIL_HKEY" AS "EMAIL_HKEY"
		, "STG_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "STG_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "STG_SRC"."EAAN8" AS "EAAN8"
		, "STG_SRC"."EAIDLN" AS "EAIDLN"
		, "STG_SRC"."EARCK7" AS "EARCK7"
		, "STG_SRC"."EAETP" AS "EAETP"
		, "STG_SRC"."EAEMAL" AS "EAEMAL"
		, "STG_SRC"."EAUSER" AS "EAUSER"
		, "STG_SRC"."EAPID" AS "EAPID"
		, "STG_SRC"."EAUPMJ" AS "EAUPMJ"
		, "STG_SRC"."EAJOBN" AS "EAJOBN"
		, "STG_SRC"."EAUPMT" AS "EAUPMT"
		, "STG_SRC"."EAEHIER" AS "EAEHIER"
		, "STG_SRC"."EAEFOR" AS "EAEFOR"
		, "STG_SRC"."EAECLASS" AS "EAECLASS"
		, "STG_SRC"."EACFNO1" AS "EACFNO1"
		, "STG_SRC"."EAGEN1" AS "EAGEN1"
		, "STG_SRC"."EAFALGE" AS "EAFALGE"
		, "STG_SRC"."EASYNCS" AS "EASYNCS"
		, "STG_SRC"."EACAAD" AS "EACAAD"
	FROM "STG_SRC" "STG_SRC"
	WHERE  "STG_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'