{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_ITEMCOST_TMP',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'SAT_JDE_ITEMCOST_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM {{ ref('JDEDWARDS_STG_F4105') }} "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COLITM"),'~'),'\#','\\' || '\#'))
				|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COAITM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COLOTG"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COUNCS")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COCSPO"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COCSIN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COURCD"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COURDT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COURAT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COURAB")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COURRF"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COTDAY")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."COCCFL"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COCRCS")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COOSTC")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."COSTOC")),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."COITM" AS "COITM"
			, "STG_TEMP_SRC"."COMCU" AS "COMCU"
			, "STG_TEMP_SRC"."COLOCN" AS "COLOCN"
			, "STG_TEMP_SRC"."COLOTN" AS "COLOTN"
			, "STG_TEMP_SRC"."COLEDG" AS "COLEDG"
			, "STG_TEMP_SRC"."COLITM" AS "COLITM"
			, "STG_TEMP_SRC"."COAITM" AS "COAITM"
			, "STG_TEMP_SRC"."COLOTG" AS "COLOTG"
			, "STG_TEMP_SRC"."COUNCS" AS "COUNCS"
			, "STG_TEMP_SRC"."COCSPO" AS "COCSPO"
			, "STG_TEMP_SRC"."COCSIN" AS "COCSIN"
			, "STG_TEMP_SRC"."COURCD" AS "COURCD"
			, "STG_TEMP_SRC"."COURDT" AS "COURDT"
			, "STG_TEMP_SRC"."COURAT" AS "COURAT"
			, "STG_TEMP_SRC"."COURAB" AS "COURAB"
			, "STG_TEMP_SRC"."COURRF" AS "COURRF"
			, "STG_TEMP_SRC"."COUSER" AS "COUSER"
			, "STG_TEMP_SRC"."COPID" AS "COPID"
			, "STG_TEMP_SRC"."COJOBN" AS "COJOBN"
			, "STG_TEMP_SRC"."COUPMJ" AS "COUPMJ"
			, "STG_TEMP_SRC"."COTDAY" AS "COTDAY"
			, "STG_TEMP_SRC"."COCCFL" AS "COCCFL"
			, "STG_TEMP_SRC"."COCRCS" AS "COCRCS"
			, "STG_TEMP_SRC"."COOSTC" AS "COOSTC"
			, "STG_TEMP_SRC"."COSTOC" AS "COSTOC"
		FROM {{ ref('JDEDWARDS_STG_F4105') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."COITM" AS "COITM"
			, "SAT_SRC"."COMCU" AS "COMCU"
			, "SAT_SRC"."COLOCN" AS "COLOCN"
			, "SAT_SRC"."COLOTN" AS "COLOTN"
			, "SAT_SRC"."COLEDG" AS "COLEDG"
			, "SAT_SRC"."COLITM" AS "COLITM"
			, "SAT_SRC"."COAITM" AS "COAITM"
			, "SAT_SRC"."COLOTG" AS "COLOTG"
			, "SAT_SRC"."COUNCS" AS "COUNCS"
			, "SAT_SRC"."COCSPO" AS "COCSPO"
			, "SAT_SRC"."COCSIN" AS "COCSIN"
			, "SAT_SRC"."COURCD" AS "COURCD"
			, "SAT_SRC"."COURDT" AS "COURDT"
			, "SAT_SRC"."COURAT" AS "COURAT"
			, "SAT_SRC"."COURAB" AS "COURAB"
			, "SAT_SRC"."COURRF" AS "COURRF"
			, "SAT_SRC"."COUSER" AS "COUSER"
			, "SAT_SRC"."COPID" AS "COPID"
			, "SAT_SRC"."COJOBN" AS "COJOBN"
			, "SAT_SRC"."COUPMJ" AS "COUPMJ"
			, "SAT_SRC"."COTDAY" AS "COTDAY"
			, "SAT_SRC"."COCCFL" AS "COCCFL"
			, "SAT_SRC"."COCRCS" AS "COCRCS"
			, "SAT_SRC"."COOSTC" AS "COOSTC"
			, "SAT_SRC"."COSTOC" AS "COSTOC"
		FROM {{ source('DEMO_FL', 'SAT_JDE_ITEMCOST') }} "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."ITEMCOST_HKEY" = "DIST_STG"."ITEMCOST_HKEY"
		WHERE  "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
	)
	SELECT 
		  "TEMP_TABLE_SET"."ITEMCOST_HKEY" AS "ITEMCOST_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."ITEMCOST_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."COITM" AS "COITM"
		, "TEMP_TABLE_SET"."COMCU" AS "COMCU"
		, "TEMP_TABLE_SET"."COLOCN" AS "COLOCN"
		, "TEMP_TABLE_SET"."COLOTN" AS "COLOTN"
		, "TEMP_TABLE_SET"."COLEDG" AS "COLEDG"
		, "TEMP_TABLE_SET"."COLITM" AS "COLITM"
		, "TEMP_TABLE_SET"."COAITM" AS "COAITM"
		, "TEMP_TABLE_SET"."COLOTG" AS "COLOTG"
		, "TEMP_TABLE_SET"."COUNCS" AS "COUNCS"
		, "TEMP_TABLE_SET"."COCSPO" AS "COCSPO"
		, "TEMP_TABLE_SET"."COCSIN" AS "COCSIN"
		, "TEMP_TABLE_SET"."COURCD" AS "COURCD"
		, "TEMP_TABLE_SET"."COURDT" AS "COURDT"
		, "TEMP_TABLE_SET"."COURAT" AS "COURAT"
		, "TEMP_TABLE_SET"."COURAB" AS "COURAB"
		, "TEMP_TABLE_SET"."COURRF" AS "COURRF"
		, "TEMP_TABLE_SET"."COUSER" AS "COUSER"
		, "TEMP_TABLE_SET"."COPID" AS "COPID"
		, "TEMP_TABLE_SET"."COJOBN" AS "COJOBN"
		, "TEMP_TABLE_SET"."COUPMJ" AS "COUPMJ"
		, "TEMP_TABLE_SET"."COTDAY" AS "COTDAY"
		, "TEMP_TABLE_SET"."COCCFL" AS "COCCFL"
		, "TEMP_TABLE_SET"."COCRCS" AS "COCRCS"
		, "TEMP_TABLE_SET"."COOSTC" AS "COOSTC"
		, "TEMP_TABLE_SET"."COSTOC" AS "COSTOC"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'