{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_PHONE_TMP',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'SAT_JDE_PHONE_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."PHONE_HKEY" AS "PHONE_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM {{ ref('JDEDWARDS_STG_F0115') }} "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."PHONE_HKEY" AS "PHONE_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPPHTP"),'~'),'\#','\\' || '\#'))
				|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPAR1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPPH1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WPUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WPUPMT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WPCFNO1")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPGEN1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."WPFALGE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WPSYNCS")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WPCAAD")),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."WPAN8" AS "WPAN8"
			, "STG_TEMP_SRC"."WPIDLN" AS "WPIDLN"
			, "STG_TEMP_SRC"."WPRCK7" AS "WPRCK7"
			, "STG_TEMP_SRC"."WPCNLN" AS "WPCNLN"
			, "STG_TEMP_SRC"."WPPHTP" AS "WPPHTP"
			, "STG_TEMP_SRC"."WPAR1" AS "WPAR1"
			, "STG_TEMP_SRC"."WPPH1" AS "WPPH1"
			, "STG_TEMP_SRC"."WPUSER" AS "WPUSER"
			, "STG_TEMP_SRC"."WPPID" AS "WPPID"
			, "STG_TEMP_SRC"."WPUPMJ" AS "WPUPMJ"
			, "STG_TEMP_SRC"."WPJOBN" AS "WPJOBN"
			, "STG_TEMP_SRC"."WPUPMT" AS "WPUPMT"
			, "STG_TEMP_SRC"."WPCFNO1" AS "WPCFNO1"
			, "STG_TEMP_SRC"."WPGEN1" AS "WPGEN1"
			, "STG_TEMP_SRC"."WPFALGE" AS "WPFALGE"
			, "STG_TEMP_SRC"."WPSYNCS" AS "WPSYNCS"
			, "STG_TEMP_SRC"."WPCAAD" AS "WPCAAD"
		FROM {{ ref('JDEDWARDS_STG_F0115') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."PHONE_HKEY" AS "PHONE_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."WPAN8" AS "WPAN8"
			, "SAT_SRC"."WPIDLN" AS "WPIDLN"
			, "SAT_SRC"."WPRCK7" AS "WPRCK7"
			, "SAT_SRC"."WPCNLN" AS "WPCNLN"
			, "SAT_SRC"."WPPHTP" AS "WPPHTP"
			, "SAT_SRC"."WPAR1" AS "WPAR1"
			, "SAT_SRC"."WPPH1" AS "WPPH1"
			, "SAT_SRC"."WPUSER" AS "WPUSER"
			, "SAT_SRC"."WPPID" AS "WPPID"
			, "SAT_SRC"."WPUPMJ" AS "WPUPMJ"
			, "SAT_SRC"."WPJOBN" AS "WPJOBN"
			, "SAT_SRC"."WPUPMT" AS "WPUPMT"
			, "SAT_SRC"."WPCFNO1" AS "WPCFNO1"
			, "SAT_SRC"."WPGEN1" AS "WPGEN1"
			, "SAT_SRC"."WPFALGE" AS "WPFALGE"
			, "SAT_SRC"."WPSYNCS" AS "WPSYNCS"
			, "SAT_SRC"."WPCAAD" AS "WPCAAD"
		FROM {{ source('DEMO_FL', 'SAT_JDE_PHONE') }} "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."PHONE_HKEY" = "DIST_STG"."PHONE_HKEY"
		WHERE  "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
	)
	SELECT 
		  "TEMP_TABLE_SET"."PHONE_HKEY" AS "PHONE_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."PHONE_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."WPAN8" AS "WPAN8"
		, "TEMP_TABLE_SET"."WPIDLN" AS "WPIDLN"
		, "TEMP_TABLE_SET"."WPRCK7" AS "WPRCK7"
		, "TEMP_TABLE_SET"."WPCNLN" AS "WPCNLN"
		, "TEMP_TABLE_SET"."WPPHTP" AS "WPPHTP"
		, "TEMP_TABLE_SET"."WPAR1" AS "WPAR1"
		, "TEMP_TABLE_SET"."WPPH1" AS "WPPH1"
		, "TEMP_TABLE_SET"."WPUSER" AS "WPUSER"
		, "TEMP_TABLE_SET"."WPPID" AS "WPPID"
		, "TEMP_TABLE_SET"."WPUPMJ" AS "WPUPMJ"
		, "TEMP_TABLE_SET"."WPJOBN" AS "WPJOBN"
		, "TEMP_TABLE_SET"."WPUPMT" AS "WPUPMT"
		, "TEMP_TABLE_SET"."WPCFNO1" AS "WPCFNO1"
		, "TEMP_TABLE_SET"."WPGEN1" AS "WPGEN1"
		, "TEMP_TABLE_SET"."WPFALGE" AS "WPFALGE"
		, "TEMP_TABLE_SET"."WPSYNCS" AS "WPSYNCS"
		, "TEMP_TABLE_SET"."WPCAAD" AS "WPCAAD"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'