{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_ITEMCROSSREFERENCE_TMP',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'SAT_JDE_ITEMCROSSREFERENCE_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM {{ ref('JDEDWARDS_STG_F4104') }} "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVEFTJ")),'~'),'\#','\\' || 
				'\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVDSC1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVDSC2"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVALN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVLITM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVAITM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVURCD"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVURDT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVURAT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVURAB")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVURRF"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVTDAY")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVRATO")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."IVAPSP")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVIDEM"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVAPSS"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVADIND"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVBPIND"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."IVCARDNO"),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."IVAN8" AS "IVAN8"
			, "STG_TEMP_SRC"."IVXRT" AS "IVXRT"
			, "STG_TEMP_SRC"."IVITM" AS "IVITM"
			, "STG_TEMP_SRC"."IVEXDJ" AS "IVEXDJ"
			, "STG_TEMP_SRC"."IVCITM" AS "IVCITM"
			, "STG_TEMP_SRC"."IVCIRV" AS "IVCIRV"
			, "STG_TEMP_SRC"."IVMCU" AS "IVMCU"
			, "STG_TEMP_SRC"."IVEFTJ" AS "IVEFTJ"
			, "STG_TEMP_SRC"."IVDSC1" AS "IVDSC1"
			, "STG_TEMP_SRC"."IVDSC2" AS "IVDSC2"
			, "STG_TEMP_SRC"."IVALN" AS "IVALN"
			, "STG_TEMP_SRC"."IVLITM" AS "IVLITM"
			, "STG_TEMP_SRC"."IVAITM" AS "IVAITM"
			, "STG_TEMP_SRC"."IVURCD" AS "IVURCD"
			, "STG_TEMP_SRC"."IVURDT" AS "IVURDT"
			, "STG_TEMP_SRC"."IVURAT" AS "IVURAT"
			, "STG_TEMP_SRC"."IVURAB" AS "IVURAB"
			, "STG_TEMP_SRC"."IVURRF" AS "IVURRF"
			, "STG_TEMP_SRC"."IVUSER" AS "IVUSER"
			, "STG_TEMP_SRC"."IVPID" AS "IVPID"
			, "STG_TEMP_SRC"."IVJOBN" AS "IVJOBN"
			, "STG_TEMP_SRC"."IVUPMJ" AS "IVUPMJ"
			, "STG_TEMP_SRC"."IVTDAY" AS "IVTDAY"
			, "STG_TEMP_SRC"."IVRATO" AS "IVRATO"
			, "STG_TEMP_SRC"."IVAPSP" AS "IVAPSP"
			, "STG_TEMP_SRC"."IVIDEM" AS "IVIDEM"
			, "STG_TEMP_SRC"."IVAPSS" AS "IVAPSS"
			, "STG_TEMP_SRC"."IVADIND" AS "IVADIND"
			, "STG_TEMP_SRC"."IVBPIND" AS "IVBPIND"
			, "STG_TEMP_SRC"."IVCARDNO" AS "IVCARDNO"
		FROM {{ ref('JDEDWARDS_STG_F4104') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."IVAN8" AS "IVAN8"
			, "SAT_SRC"."IVXRT" AS "IVXRT"
			, "SAT_SRC"."IVITM" AS "IVITM"
			, "SAT_SRC"."IVEXDJ" AS "IVEXDJ"
			, "SAT_SRC"."IVCITM" AS "IVCITM"
			, "SAT_SRC"."IVCIRV" AS "IVCIRV"
			, "SAT_SRC"."IVMCU" AS "IVMCU"
			, "SAT_SRC"."IVEFTJ" AS "IVEFTJ"
			, "SAT_SRC"."IVDSC1" AS "IVDSC1"
			, "SAT_SRC"."IVDSC2" AS "IVDSC2"
			, "SAT_SRC"."IVALN" AS "IVALN"
			, "SAT_SRC"."IVLITM" AS "IVLITM"
			, "SAT_SRC"."IVAITM" AS "IVAITM"
			, "SAT_SRC"."IVURCD" AS "IVURCD"
			, "SAT_SRC"."IVURDT" AS "IVURDT"
			, "SAT_SRC"."IVURAT" AS "IVURAT"
			, "SAT_SRC"."IVURAB" AS "IVURAB"
			, "SAT_SRC"."IVURRF" AS "IVURRF"
			, "SAT_SRC"."IVUSER" AS "IVUSER"
			, "SAT_SRC"."IVPID" AS "IVPID"
			, "SAT_SRC"."IVJOBN" AS "IVJOBN"
			, "SAT_SRC"."IVUPMJ" AS "IVUPMJ"
			, "SAT_SRC"."IVTDAY" AS "IVTDAY"
			, "SAT_SRC"."IVRATO" AS "IVRATO"
			, "SAT_SRC"."IVAPSP" AS "IVAPSP"
			, "SAT_SRC"."IVIDEM" AS "IVIDEM"
			, "SAT_SRC"."IVAPSS" AS "IVAPSS"
			, "SAT_SRC"."IVADIND" AS "IVADIND"
			, "SAT_SRC"."IVBPIND" AS "IVBPIND"
			, "SAT_SRC"."IVCARDNO" AS "IVCARDNO"
		FROM {{ source('DEMO_FL', 'SAT_JDE_ITEMCROSSREFERENCE') }} "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."ITEMCROSSREFERENCE_HKEY" = "DIST_STG"."ITEMCROSSREFERENCE_HKEY"
		WHERE  "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
	)
	SELECT 
		  "TEMP_TABLE_SET"."ITEMCROSSREFERENCE_HKEY" AS "ITEMCROSSREFERENCE_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."ITEMCROSSREFERENCE_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."IVAN8" AS "IVAN8"
		, "TEMP_TABLE_SET"."IVXRT" AS "IVXRT"
		, "TEMP_TABLE_SET"."IVITM" AS "IVITM"
		, "TEMP_TABLE_SET"."IVEXDJ" AS "IVEXDJ"
		, "TEMP_TABLE_SET"."IVCITM" AS "IVCITM"
		, "TEMP_TABLE_SET"."IVCIRV" AS "IVCIRV"
		, "TEMP_TABLE_SET"."IVMCU" AS "IVMCU"
		, "TEMP_TABLE_SET"."IVEFTJ" AS "IVEFTJ"
		, "TEMP_TABLE_SET"."IVDSC1" AS "IVDSC1"
		, "TEMP_TABLE_SET"."IVDSC2" AS "IVDSC2"
		, "TEMP_TABLE_SET"."IVALN" AS "IVALN"
		, "TEMP_TABLE_SET"."IVLITM" AS "IVLITM"
		, "TEMP_TABLE_SET"."IVAITM" AS "IVAITM"
		, "TEMP_TABLE_SET"."IVURCD" AS "IVURCD"
		, "TEMP_TABLE_SET"."IVURDT" AS "IVURDT"
		, "TEMP_TABLE_SET"."IVURAT" AS "IVURAT"
		, "TEMP_TABLE_SET"."IVURAB" AS "IVURAB"
		, "TEMP_TABLE_SET"."IVURRF" AS "IVURRF"
		, "TEMP_TABLE_SET"."IVUSER" AS "IVUSER"
		, "TEMP_TABLE_SET"."IVPID" AS "IVPID"
		, "TEMP_TABLE_SET"."IVJOBN" AS "IVJOBN"
		, "TEMP_TABLE_SET"."IVUPMJ" AS "IVUPMJ"
		, "TEMP_TABLE_SET"."IVTDAY" AS "IVTDAY"
		, "TEMP_TABLE_SET"."IVRATO" AS "IVRATO"
		, "TEMP_TABLE_SET"."IVAPSP" AS "IVAPSP"
		, "TEMP_TABLE_SET"."IVIDEM" AS "IVIDEM"
		, "TEMP_TABLE_SET"."IVAPSS" AS "IVAPSS"
		, "TEMP_TABLE_SET"."IVADIND" AS "IVADIND"
		, "TEMP_TABLE_SET"."IVBPIND" AS "IVBPIND"
		, "TEMP_TABLE_SET"."IVCARDNO" AS "IVCARDNO"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'