{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='LKS_JDE_ITEMPRICE_PRODUCT_TMP',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'LKS_JDE_ITEMPRICE_PRODUCT_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT 
			  "STG_DIS_SRC"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MIN("STG_DIS_SRC"."LOAD_DATE") AS "MIN_LOAD_TIMESTAMP"
		FROM {{ ref('JDEDWARDS_STG_F4106') }} "STG_DIS_SRC"
		GROUP BY  "STG_DIS_SRC"."ITEMPRICE_HKEY",  "STG_DIS_SRC"."LOAD_CYCLE_ID"
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."LNK_ITEMPRICE_PRODUCT_HKEY" AS "LNK_ITEMPRICE_PRODUCT_HKEY"
			, "STG_TEMP_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "STG_TEMP_SRC"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."BPTDAY" AS "BPTDAY"
			, "STG_TEMP_SRC"."BPUPMJ" AS "BPUPMJ"
			, "STG_TEMP_SRC"."BPEXDJ" AS "BPEXDJ"
			, "STG_TEMP_SRC"."BPUOM" AS "BPUOM"
			, "STG_TEMP_SRC"."BPCRCD" AS "BPCRCD"
			, "STG_TEMP_SRC"."BPFRMP" AS "BPFRMP"
			, "STG_TEMP_SRC"."BPLOTG" AS "BPLOTG"
			, "STG_TEMP_SRC"."BPCGID" AS "BPCGID"
			, "STG_TEMP_SRC"."BPIGID" AS "BPIGID"
			, "STG_TEMP_SRC"."BPAN8" AS "BPAN8"
			, "STG_TEMP_SRC"."BPLOTN" AS "BPLOTN"
			, "STG_TEMP_SRC"."BPLOCN" AS "BPLOCN"
			, "STG_TEMP_SRC"."BPMCU" AS "BPMCU"
			, "STG_TEMP_SRC"."BPITM" AS "BPITM"
		FROM {{ ref('JDEDWARDS_STG_F4106') }} "STG_TEMP_SRC"
		UNION 
		SELECT 
			  "LKS_SRC"."LNK_ITEMPRICE_PRODUCT_HKEY" AS "LNK_ITEMPRICE_PRODUCT_HKEY"
			, "LNK_SRC"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
			, "LNK_SRC"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
			, "LKS_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LKS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "LKS_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'LKS' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "LKS_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "LKS_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "LKS_SRC"."BPTDAY" AS "BPTDAY"
			, "LKS_SRC"."BPUPMJ" AS "BPUPMJ"
			, "LKS_SRC"."BPEXDJ" AS "BPEXDJ"
			, "LKS_SRC"."BPUOM" AS "BPUOM"
			, "LKS_SRC"."BPCRCD" AS "BPCRCD"
			, "LKS_SRC"."BPFRMP" AS "BPFRMP"
			, "LKS_SRC"."BPLOTG" AS "BPLOTG"
			, "LKS_SRC"."BPCGID" AS "BPCGID"
			, "LKS_SRC"."BPIGID" AS "BPIGID"
			, "LKS_SRC"."BPAN8" AS "BPAN8"
			, "LKS_SRC"."BPLOTN" AS "BPLOTN"
			, "LKS_SRC"."BPLOCN" AS "BPLOCN"
			, "LKS_SRC"."BPMCU" AS "BPMCU"
			, "LKS_SRC"."BPITM" AS "BPITM"
		FROM {{ source('DEMO_FL', 'LKS_JDE_ITEMPRICE_PRODUCT') }} "LKS_SRC"
		INNER JOIN {{ source('DEMO_FL', 'LNK_ITEMPRICE_PRODUCT') }} "LNK_SRC" ON  "LKS_SRC"."LNK_ITEMPRICE_PRODUCT_HKEY" = "LNK_SRC"."LNK_ITEMPRICE_PRODUCT_HKEY"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "LNK_SRC"."ITEMPRICE_HKEY" = "DIST_STG"."ITEMPRICE_HKEY"
		WHERE  "LKS_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
	)
	SELECT 
		  "TEMP_TABLE_SET"."LNK_ITEMPRICE_PRODUCT_HKEY" AS "LNK_ITEMPRICE_PRODUCT_HKEY"
		, "TEMP_TABLE_SET"."PRODUCT_HKEY" AS "PRODUCT_HKEY"
		, "TEMP_TABLE_SET"."ITEMPRICE_HKEY" AS "ITEMPRICE_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."PRODUCT_HKEY")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."PRODUCT_HKEY"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."ITEMPRICE_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."BPTDAY" AS "BPTDAY"
		, "TEMP_TABLE_SET"."BPUPMJ" AS "BPUPMJ"
		, "TEMP_TABLE_SET"."BPEXDJ" AS "BPEXDJ"
		, "TEMP_TABLE_SET"."BPUOM" AS "BPUOM"
		, "TEMP_TABLE_SET"."BPCRCD" AS "BPCRCD"
		, "TEMP_TABLE_SET"."BPFRMP" AS "BPFRMP"
		, "TEMP_TABLE_SET"."BPLOTG" AS "BPLOTG"
		, "TEMP_TABLE_SET"."BPCGID" AS "BPCGID"
		, "TEMP_TABLE_SET"."BPIGID" AS "BPIGID"
		, "TEMP_TABLE_SET"."BPAN8" AS "BPAN8"
		, "TEMP_TABLE_SET"."BPLOTN" AS "BPLOTN"
		, "TEMP_TABLE_SET"."BPLOCN" AS "BPLOCN"
		, "TEMP_TABLE_SET"."BPMCU" AS "BPMCU"
		, "TEMP_TABLE_SET"."BPITM" AS "BPITM"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'