{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SAT_JDE_ADDRESS_TMP',
		schema='JDEDWARDS_STG',
		tags=['JDEDWARDS', 'SAT_JDE_ADDRESS_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM {{ ref('JDEDWARDS_STG_F0116') }} "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALEFTF"),'~'),'\#','\\' || '\#'))
				|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADD1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADD2"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADD3"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADD4"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADDZ"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALCTY1"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALCOUN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALADDS"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALCRTE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALBKML"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALCTR"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALUSER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALPID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."ALUPMJ")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."ALJOBN"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."ALUPMT")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."ALSYNCS")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."ALCAAD")),'~'),'\#','\\' || '\#'))|| '\#','\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."ALAN8" AS "ALAN8"
			, "STG_TEMP_SRC"."ALEFTB" AS "ALEFTB"
			, "STG_TEMP_SRC"."ALEFTF" AS "ALEFTF"
			, "STG_TEMP_SRC"."ALADD1" AS "ALADD1"
			, "STG_TEMP_SRC"."ALADD2" AS "ALADD2"
			, "STG_TEMP_SRC"."ALADD3" AS "ALADD3"
			, "STG_TEMP_SRC"."ALADD4" AS "ALADD4"
			, "STG_TEMP_SRC"."ALADDZ" AS "ALADDZ"
			, "STG_TEMP_SRC"."ALCTY1" AS "ALCTY1"
			, "STG_TEMP_SRC"."ALCOUN" AS "ALCOUN"
			, "STG_TEMP_SRC"."ALADDS" AS "ALADDS"
			, "STG_TEMP_SRC"."ALCRTE" AS "ALCRTE"
			, "STG_TEMP_SRC"."ALBKML" AS "ALBKML"
			, "STG_TEMP_SRC"."ALCTR" AS "ALCTR"
			, "STG_TEMP_SRC"."ALUSER" AS "ALUSER"
			, "STG_TEMP_SRC"."ALPID" AS "ALPID"
			, "STG_TEMP_SRC"."ALUPMJ" AS "ALUPMJ"
			, "STG_TEMP_SRC"."ALJOBN" AS "ALJOBN"
			, "STG_TEMP_SRC"."ALUPMT" AS "ALUPMT"
			, "STG_TEMP_SRC"."ALSYNCS" AS "ALSYNCS"
			, "STG_TEMP_SRC"."ALCAAD" AS "ALCAAD"
		FROM {{ ref('JDEDWARDS_STG_F0116') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."ALAN8" AS "ALAN8"
			, "SAT_SRC"."ALEFTB" AS "ALEFTB"
			, "SAT_SRC"."ALEFTF" AS "ALEFTF"
			, "SAT_SRC"."ALADD1" AS "ALADD1"
			, "SAT_SRC"."ALADD2" AS "ALADD2"
			, "SAT_SRC"."ALADD3" AS "ALADD3"
			, "SAT_SRC"."ALADD4" AS "ALADD4"
			, "SAT_SRC"."ALADDZ" AS "ALADDZ"
			, "SAT_SRC"."ALCTY1" AS "ALCTY1"
			, "SAT_SRC"."ALCOUN" AS "ALCOUN"
			, "SAT_SRC"."ALADDS" AS "ALADDS"
			, "SAT_SRC"."ALCRTE" AS "ALCRTE"
			, "SAT_SRC"."ALBKML" AS "ALBKML"
			, "SAT_SRC"."ALCTR" AS "ALCTR"
			, "SAT_SRC"."ALUSER" AS "ALUSER"
			, "SAT_SRC"."ALPID" AS "ALPID"
			, "SAT_SRC"."ALUPMJ" AS "ALUPMJ"
			, "SAT_SRC"."ALJOBN" AS "ALJOBN"
			, "SAT_SRC"."ALUPMT" AS "ALUPMT"
			, "SAT_SRC"."ALSYNCS" AS "ALSYNCS"
			, "SAT_SRC"."ALCAAD" AS "ALCAAD"
		FROM {{ source('DEMO_FL', 'SAT_JDE_ADDRESS') }} "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."ADDRESS_HKEY" = "DIST_STG"."ADDRESS_HKEY"
		WHERE  "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
	)
	SELECT 
		  "TEMP_TABLE_SET"."ADDRESS_HKEY" AS "ADDRESS_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."ADDRESS_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."ALAN8" AS "ALAN8"
		, "TEMP_TABLE_SET"."ALEFTB" AS "ALEFTB"
		, "TEMP_TABLE_SET"."ALEFTF" AS "ALEFTF"
		, "TEMP_TABLE_SET"."ALADD1" AS "ALADD1"
		, "TEMP_TABLE_SET"."ALADD2" AS "ALADD2"
		, "TEMP_TABLE_SET"."ALADD3" AS "ALADD3"
		, "TEMP_TABLE_SET"."ALADD4" AS "ALADD4"
		, "TEMP_TABLE_SET"."ALADDZ" AS "ALADDZ"
		, "TEMP_TABLE_SET"."ALCTY1" AS "ALCTY1"
		, "TEMP_TABLE_SET"."ALCOUN" AS "ALCOUN"
		, "TEMP_TABLE_SET"."ALADDS" AS "ALADDS"
		, "TEMP_TABLE_SET"."ALCRTE" AS "ALCRTE"
		, "TEMP_TABLE_SET"."ALBKML" AS "ALBKML"
		, "TEMP_TABLE_SET"."ALCTR" AS "ALCTR"
		, "TEMP_TABLE_SET"."ALUSER" AS "ALUSER"
		, "TEMP_TABLE_SET"."ALPID" AS "ALPID"
		, "TEMP_TABLE_SET"."ALUPMJ" AS "ALUPMJ"
		, "TEMP_TABLE_SET"."ALJOBN" AS "ALJOBN"
		, "TEMP_TABLE_SET"."ALUPMT" AS "ALUPMT"
		, "TEMP_TABLE_SET"."ALSYNCS" AS "ALSYNCS"
		, "TEMP_TABLE_SET"."ALCAAD" AS "ALCAAD"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'