{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F01151',
		schema='JDEDWARDS_EXT',
		tags=['JDEDWARDS', 'EXT_JDE_EMAIL_INCR', 'EXT_JDE_EMAIL_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, DATEADD(microsecond, 2*row_number() over (order by "TDFV_SRC"."CDC_TIMESTAMP"),
				TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()))   AS "LOAD_DATE"
			, "TDFV_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, COALESCE("TDFV_SRC"."JRN_FLAG","MEX_SRC"."ATTRIBUTE_VARCHAR") AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."EAAN8" AS "EAAN8"
			, "TDFV_SRC"."EAIDLN" AS "EAIDLN"
			, "TDFV_SRC"."EARCK7" AS "EARCK7"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."EAAN8")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EAAN8_BK"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."EAIDLN")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EAIDLN_BK"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."EARCK7")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EARCK7_BK"
			, UPPER( TO_CHAR("TDFV_SRC"."EAAN8")) AS "WWAN8_FK_EAIDLN_BK"
			, UPPER( TO_CHAR("TDFV_SRC"."EAIDLN")) AS "WWIDLN_FK_EAIDLN_BK"
			, UPPER( TO_CHAR("TDFV_SRC"."EAAN8")) AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
			, "TDFV_SRC"."EAETP" AS "EAETP"
			, "TDFV_SRC"."EAEMAL" AS "EAEMAL"
			, "TDFV_SRC"."EAUSER" AS "EAUSER"
			, "TDFV_SRC"."EAPID" AS "EAPID"
			, "TDFV_SRC"."EAUPMJ" AS "EAUPMJ"
			, "TDFV_SRC"."EAJOBN" AS "EAJOBN"
			, "TDFV_SRC"."EAUPMT" AS "EAUPMT"
			, "TDFV_SRC"."EAEHIER" AS "EAEHIER"
			, "TDFV_SRC"."EAEFOR" AS "EAEFOR"
			, "TDFV_SRC"."EAECLASS" AS "EAECLASS"
			, "TDFV_SRC"."EACFNO1" AS "EACFNO1"
			, "TDFV_SRC"."EAGEN1" AS "EAGEN1"
			, "TDFV_SRC"."EAFALGE" AS "EAFALGE"
			, "TDFV_SRC"."EASYNCS" AS "EASYNCS"
			, "TDFV_SRC"."EACAAD" AS "EACAAD"
		FROM {{ ref('JDEDWARDS_DFV_VW_F01151') }} "TDFV_SRC"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."EAAN8" AS "EAAN8"
			, "CALCULATE_BK"."EAIDLN" AS "EAIDLN"
			, "CALCULATE_BK"."EARCK7" AS "EARCK7"
			, "CALCULATE_BK"."EAAN8_BK" AS "EAAN8_BK"
			, "CALCULATE_BK"."EAIDLN_BK" AS "EAIDLN_BK"
			, "CALCULATE_BK"."EARCK7_BK" AS "EARCK7_BK"
			, "CALCULATE_BK"."WWAN8_FK_EAIDLN_BK" AS "WWAN8_FK_EAIDLN_BK"
			, "CALCULATE_BK"."WWIDLN_FK_EAIDLN_BK" AS "WWIDLN_FK_EAIDLN_BK"
			, "CALCULATE_BK"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
			, "CALCULATE_BK"."EAETP" AS "EAETP"
			, "CALCULATE_BK"."EAEMAL" AS "EAEMAL"
			, "CALCULATE_BK"."EAUSER" AS "EAUSER"
			, "CALCULATE_BK"."EAPID" AS "EAPID"
			, "CALCULATE_BK"."EAUPMJ" AS "EAUPMJ"
			, "CALCULATE_BK"."EAJOBN" AS "EAJOBN"
			, "CALCULATE_BK"."EAUPMT" AS "EAUPMT"
			, "CALCULATE_BK"."EAEHIER" AS "EAEHIER"
			, "CALCULATE_BK"."EAEFOR" AS "EAEFOR"
			, "CALCULATE_BK"."EAECLASS" AS "EAECLASS"
			, "CALCULATE_BK"."EACFNO1" AS "EACFNO1"
			, "CALCULATE_BK"."EAGEN1" AS "EAGEN1"
			, "CALCULATE_BK"."EAFALGE" AS "EAFALGE"
			, "CALCULATE_BK"."EASYNCS" AS "EASYNCS"
			, "CALCULATE_BK"."EACAAD" AS "EACAAD"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."EAAN8" AS "EAAN8"
		, "EXT_UNION"."EAIDLN" AS "EAIDLN"
		, "EXT_UNION"."EARCK7" AS "EARCK7"
		, "EXT_UNION"."EAAN8_BK" AS "EAAN8_BK"
		, "EXT_UNION"."EAIDLN_BK" AS "EAIDLN_BK"
		, "EXT_UNION"."EARCK7_BK" AS "EARCK7_BK"
		, "EXT_UNION"."WWAN8_FK_EAIDLN_BK" AS "WWAN8_FK_EAIDLN_BK"
		, "EXT_UNION"."WWIDLN_FK_EAIDLN_BK" AS "WWIDLN_FK_EAIDLN_BK"
		, "EXT_UNION"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
		, "EXT_UNION"."EAETP" AS "EAETP"
		, "EXT_UNION"."EAEMAL" AS "EAEMAL"
		, "EXT_UNION"."EAUSER" AS "EAUSER"
		, "EXT_UNION"."EAPID" AS "EAPID"
		, "EXT_UNION"."EAUPMJ" AS "EAUPMJ"
		, "EXT_UNION"."EAJOBN" AS "EAJOBN"
		, "EXT_UNION"."EAUPMT" AS "EAUPMT"
		, "EXT_UNION"."EAEHIER" AS "EAEHIER"
		, "EXT_UNION"."EAEFOR" AS "EAEFOR"
		, "EXT_UNION"."EAECLASS" AS "EAECLASS"
		, "EXT_UNION"."EACFNO1" AS "EACFNO1"
		, "EXT_UNION"."EAGEN1" AS "EAGEN1"
		, "EXT_UNION"."EAFALGE" AS "EAFALGE"
		, "EXT_UNION"."EASYNCS" AS "EASYNCS"
		, "EXT_UNION"."EACAAD" AS "EACAAD"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."EAAN8", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EAAN8"
			, COALESCE("INI_SRC"."EAIDLN", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EAIDLN"
			, COALESCE("INI_SRC"."EARCK7", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "EARCK7"
			, "INI_SRC"."EAETP" AS "EAETP"
			, "INI_SRC"."EAEMAL" AS "EAEMAL"
			, "INI_SRC"."EAUSER" AS "EAUSER"
			, "INI_SRC"."EAPID" AS "EAPID"
			, "INI_SRC"."EAUPMJ" AS "EAUPMJ"
			, "INI_SRC"."EAJOBN" AS "EAJOBN"
			, "INI_SRC"."EAUPMT" AS "EAUPMT"
			, "INI_SRC"."EAEHIER" AS "EAEHIER"
			, "INI_SRC"."EAEFOR" AS "EAEFOR"
			, "INI_SRC"."EAECLASS" AS "EAECLASS"
			, "INI_SRC"."EACFNO1" AS "EACFNO1"
			, "INI_SRC"."EAGEN1" AS "EAGEN1"
			, "INI_SRC"."EAFALGE" AS "EAFALGE"
			, "INI_SRC"."EASYNCS" AS "EASYNCS"
			, "INI_SRC"."EACAAD" AS "EACAAD"
		FROM {{ source('JDEDWARDS_INI', 'F01151') }} "INI_SRC"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."EAAN8" AS "EAAN8"
			, "LOAD_INIT_DATA"."EAIDLN" AS "EAIDLN"
			, "LOAD_INIT_DATA"."EARCK7" AS "EARCK7"
			, "LOAD_INIT_DATA"."EAETP" AS "EAETP"
			, "LOAD_INIT_DATA"."EAEMAL" AS "EAEMAL"
			, "LOAD_INIT_DATA"."EAUSER" AS "EAUSER"
			, "LOAD_INIT_DATA"."EAPID" AS "EAPID"
			, "LOAD_INIT_DATA"."EAUPMJ" AS "EAUPMJ"
			, "LOAD_INIT_DATA"."EAJOBN" AS "EAJOBN"
			, "LOAD_INIT_DATA"."EAUPMT" AS "EAUPMT"
			, "LOAD_INIT_DATA"."EAEHIER" AS "EAEHIER"
			, "LOAD_INIT_DATA"."EAEFOR" AS "EAEFOR"
			, "LOAD_INIT_DATA"."EAECLASS" AS "EAECLASS"
			, "LOAD_INIT_DATA"."EACFNO1" AS "EACFNO1"
			, "LOAD_INIT_DATA"."EAGEN1" AS "EAGEN1"
			, "LOAD_INIT_DATA"."EAFALGE" AS "EAFALGE"
			, "LOAD_INIT_DATA"."EASYNCS" AS "EASYNCS"
			, "LOAD_INIT_DATA"."EACAAD" AS "EACAAD"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT) AS "EAAN8"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT) AS "EAIDLN"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT) AS "EARCK7"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAETP"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAEMAL"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAUSER"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAPID"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "EAUPMJ"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAJOBN"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "EAUPMT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "EAEHIER"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAEFOR"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAECLASS"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "EACFNO1"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAGEN1"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "EAFALGE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "EASYNCS"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "EACAAD"
		FROM {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_DATE" AS "CDC_TIMESTAMP"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."EAAN8" AS "EAAN8"
			, "PREP_EXCEP"."EAIDLN" AS "EAIDLN"
			, "PREP_EXCEP"."EARCK7" AS "EARCK7"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."EAAN8")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EAAN8_BK"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."EAIDLN")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EAIDLN_BK"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."EARCK7")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "EARCK7_BK"
			, UPPER( TO_CHAR("PREP_EXCEP"."EAAN8")) AS "WWAN8_FK_EAIDLN_BK"
			, UPPER( TO_CHAR("PREP_EXCEP"."EAIDLN")) AS "WWIDLN_FK_EAIDLN_BK"
			, UPPER( TO_CHAR("PREP_EXCEP"."EAAN8")) AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
			, "PREP_EXCEP"."EAETP" AS "EAETP"
			, "PREP_EXCEP"."EAEMAL" AS "EAEMAL"
			, "PREP_EXCEP"."EAUSER" AS "EAUSER"
			, "PREP_EXCEP"."EAPID" AS "EAPID"
			, "PREP_EXCEP"."EAUPMJ" AS "EAUPMJ"
			, "PREP_EXCEP"."EAJOBN" AS "EAJOBN"
			, "PREP_EXCEP"."EAUPMT" AS "EAUPMT"
			, "PREP_EXCEP"."EAEHIER" AS "EAEHIER"
			, "PREP_EXCEP"."EAEFOR" AS "EAEFOR"
			, "PREP_EXCEP"."EAECLASS" AS "EAECLASS"
			, "PREP_EXCEP"."EACFNO1" AS "EACFNO1"
			, "PREP_EXCEP"."EAGEN1" AS "EAGEN1"
			, "PREP_EXCEP"."EAFALGE" AS "EAFALGE"
			, "PREP_EXCEP"."EASYNCS" AS "EASYNCS"
			, "PREP_EXCEP"."EACAAD" AS "EACAAD"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."EAAN8" AS "EAAN8"
		, "CALCULATE_BK"."EAIDLN" AS "EAIDLN"
		, "CALCULATE_BK"."EARCK7" AS "EARCK7"
		, "CALCULATE_BK"."EAAN8_BK" AS "EAAN8_BK"
		, "CALCULATE_BK"."EAIDLN_BK" AS "EAIDLN_BK"
		, "CALCULATE_BK"."EARCK7_BK" AS "EARCK7_BK"
		, "CALCULATE_BK"."WWAN8_FK_EAIDLN_BK" AS "WWAN8_FK_EAIDLN_BK"
		, "CALCULATE_BK"."WWIDLN_FK_EAIDLN_BK" AS "WWIDLN_FK_EAIDLN_BK"
		, "CALCULATE_BK"."ABAN8_FK_ADDRESSBOOK_EAAN8_BK" AS "ABAN8_FK_ADDRESSBOOK_EAAN8_BK"
		, "CALCULATE_BK"."EAETP" AS "EAETP"
		, "CALCULATE_BK"."EAEMAL" AS "EAEMAL"
		, "CALCULATE_BK"."EAUSER" AS "EAUSER"
		, "CALCULATE_BK"."EAPID" AS "EAPID"
		, "CALCULATE_BK"."EAUPMJ" AS "EAUPMJ"
		, "CALCULATE_BK"."EAJOBN" AS "EAJOBN"
		, "CALCULATE_BK"."EAUPMT" AS "EAUPMT"
		, "CALCULATE_BK"."EAEHIER" AS "EAEHIER"
		, "CALCULATE_BK"."EAEFOR" AS "EAEFOR"
		, "CALCULATE_BK"."EAECLASS" AS "EAECLASS"
		, "CALCULATE_BK"."EACFNO1" AS "EACFNO1"
		, "CALCULATE_BK"."EAGEN1" AS "EAGEN1"
		, "CALCULATE_BK"."EAFALGE" AS "EAFALGE"
		, "CALCULATE_BK"."EASYNCS" AS "EASYNCS"
		, "CALCULATE_BK"."EACAAD" AS "EACAAD"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'