{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "JDEDWARDS" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='F0116',
		schema='JDEDWARDS_EXT',
		tags=['JDEDWARDS', 'EXT_JDE_ADDRESS_INCR', 'EXT_JDE_ADDRESS_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, DATEADD(microsecond, 2*row_number() over (order by "TDFV_SRC"."CDC_TIMESTAMP"),
				TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()))   AS "LOAD_DATE"
			, "TDFV_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, COALESCE("TDFV_SRC"."JRN_FLAG","MEX_SRC"."ATTRIBUTE_VARCHAR") AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."ALAN8" AS "ALAN8"
			, "TDFV_SRC"."ALEFTB" AS "ALEFTB"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."ALAN8")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "ALAN8_BK"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."ALEFTB")),"MEX_SRC"."KEY_ATTRIBUTE_NUMBER") AS "ALEFTB_BK"
			, UPPER( TO_CHAR("TDFV_SRC"."ALAN8")) AS "ABAN8_FK_ALAN8_BK"
			, "TDFV_SRC"."ALEFTF" AS "ALEFTF"
			, "TDFV_SRC"."ALADD1" AS "ALADD1"
			, "TDFV_SRC"."ALADD2" AS "ALADD2"
			, "TDFV_SRC"."ALADD3" AS "ALADD3"
			, "TDFV_SRC"."ALADD4" AS "ALADD4"
			, "TDFV_SRC"."ALADDZ" AS "ALADDZ"
			, "TDFV_SRC"."ALCTY1" AS "ALCTY1"
			, "TDFV_SRC"."ALCOUN" AS "ALCOUN"
			, "TDFV_SRC"."ALADDS" AS "ALADDS"
			, "TDFV_SRC"."ALCRTE" AS "ALCRTE"
			, "TDFV_SRC"."ALBKML" AS "ALBKML"
			, "TDFV_SRC"."ALCTR" AS "ALCTR"
			, "TDFV_SRC"."ALUSER" AS "ALUSER"
			, "TDFV_SRC"."ALPID" AS "ALPID"
			, "TDFV_SRC"."ALUPMJ" AS "ALUPMJ"
			, "TDFV_SRC"."ALJOBN" AS "ALJOBN"
			, "TDFV_SRC"."ALUPMT" AS "ALUPMT"
			, "TDFV_SRC"."ALSYNCS" AS "ALSYNCS"
			, "TDFV_SRC"."ALCAAD" AS "ALCAAD"
		FROM {{ ref('JDEDWARDS_DFV_VW_F0116') }} "TDFV_SRC"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."ALAN8" AS "ALAN8"
			, "CALCULATE_BK"."ALEFTB" AS "ALEFTB"
			, "CALCULATE_BK"."ALAN8_BK" AS "ALAN8_BK"
			, "CALCULATE_BK"."ALEFTB_BK" AS "ALEFTB_BK"
			, "CALCULATE_BK"."ABAN8_FK_ALAN8_BK" AS "ABAN8_FK_ALAN8_BK"
			, "CALCULATE_BK"."ALEFTF" AS "ALEFTF"
			, "CALCULATE_BK"."ALADD1" AS "ALADD1"
			, "CALCULATE_BK"."ALADD2" AS "ALADD2"
			, "CALCULATE_BK"."ALADD3" AS "ALADD3"
			, "CALCULATE_BK"."ALADD4" AS "ALADD4"
			, "CALCULATE_BK"."ALADDZ" AS "ALADDZ"
			, "CALCULATE_BK"."ALCTY1" AS "ALCTY1"
			, "CALCULATE_BK"."ALCOUN" AS "ALCOUN"
			, "CALCULATE_BK"."ALADDS" AS "ALADDS"
			, "CALCULATE_BK"."ALCRTE" AS "ALCRTE"
			, "CALCULATE_BK"."ALBKML" AS "ALBKML"
			, "CALCULATE_BK"."ALCTR" AS "ALCTR"
			, "CALCULATE_BK"."ALUSER" AS "ALUSER"
			, "CALCULATE_BK"."ALPID" AS "ALPID"
			, "CALCULATE_BK"."ALUPMJ" AS "ALUPMJ"
			, "CALCULATE_BK"."ALJOBN" AS "ALJOBN"
			, "CALCULATE_BK"."ALUPMT" AS "ALUPMT"
			, "CALCULATE_BK"."ALSYNCS" AS "ALSYNCS"
			, "CALCULATE_BK"."ALCAAD" AS "ALCAAD"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."ALAN8" AS "ALAN8"
		, "EXT_UNION"."ALEFTB" AS "ALEFTB"
		, "EXT_UNION"."ALAN8_BK" AS "ALAN8_BK"
		, "EXT_UNION"."ALEFTB_BK" AS "ALEFTB_BK"
		, "EXT_UNION"."ABAN8_FK_ALAN8_BK" AS "ABAN8_FK_ALAN8_BK"
		, "EXT_UNION"."ALEFTF" AS "ALEFTF"
		, "EXT_UNION"."ALADD1" AS "ALADD1"
		, "EXT_UNION"."ALADD2" AS "ALADD2"
		, "EXT_UNION"."ALADD3" AS "ALADD3"
		, "EXT_UNION"."ALADD4" AS "ALADD4"
		, "EXT_UNION"."ALADDZ" AS "ALADDZ"
		, "EXT_UNION"."ALCTY1" AS "ALCTY1"
		, "EXT_UNION"."ALCOUN" AS "ALCOUN"
		, "EXT_UNION"."ALADDS" AS "ALADDS"
		, "EXT_UNION"."ALCRTE" AS "ALCRTE"
		, "EXT_UNION"."ALBKML" AS "ALBKML"
		, "EXT_UNION"."ALCTR" AS "ALCTR"
		, "EXT_UNION"."ALUSER" AS "ALUSER"
		, "EXT_UNION"."ALPID" AS "ALPID"
		, "EXT_UNION"."ALUPMJ" AS "ALUPMJ"
		, "EXT_UNION"."ALJOBN" AS "ALJOBN"
		, "EXT_UNION"."ALUPMT" AS "ALUPMT"
		, "EXT_UNION"."ALSYNCS" AS "ALSYNCS"
		, "EXT_UNION"."ALCAAD" AS "ALCAAD"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'JDEDWARDS'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."ALAN8", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT)) AS "ALAN8"
			, COALESCE("INI_SRC"."ALEFTB", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "ALEFTB"
			, "INI_SRC"."ALEFTF" AS "ALEFTF"
			, "INI_SRC"."ALADD1" AS "ALADD1"
			, "INI_SRC"."ALADD2" AS "ALADD2"
			, "INI_SRC"."ALADD3" AS "ALADD3"
			, "INI_SRC"."ALADD4" AS "ALADD4"
			, "INI_SRC"."ALADDZ" AS "ALADDZ"
			, "INI_SRC"."ALCTY1" AS "ALCTY1"
			, "INI_SRC"."ALCOUN" AS "ALCOUN"
			, "INI_SRC"."ALADDS" AS "ALADDS"
			, "INI_SRC"."ALCRTE" AS "ALCRTE"
			, "INI_SRC"."ALBKML" AS "ALBKML"
			, "INI_SRC"."ALCTR" AS "ALCTR"
			, "INI_SRC"."ALUSER" AS "ALUSER"
			, "INI_SRC"."ALPID" AS "ALPID"
			, "INI_SRC"."ALUPMJ" AS "ALUPMJ"
			, "INI_SRC"."ALJOBN" AS "ALJOBN"
			, "INI_SRC"."ALUPMT" AS "ALUPMT"
			, "INI_SRC"."ALSYNCS" AS "ALSYNCS"
			, "INI_SRC"."ALCAAD" AS "ALCAAD"
		FROM {{ source('JDEDWARDS_INI', 'F0116') }} "INI_SRC"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."ALAN8" AS "ALAN8"
			, "LOAD_INIT_DATA"."ALEFTB" AS "ALEFTB"
			, "LOAD_INIT_DATA"."ALEFTF" AS "ALEFTF"
			, "LOAD_INIT_DATA"."ALADD1" AS "ALADD1"
			, "LOAD_INIT_DATA"."ALADD2" AS "ALADD2"
			, "LOAD_INIT_DATA"."ALADD3" AS "ALADD3"
			, "LOAD_INIT_DATA"."ALADD4" AS "ALADD4"
			, "LOAD_INIT_DATA"."ALADDZ" AS "ALADDZ"
			, "LOAD_INIT_DATA"."ALCTY1" AS "ALCTY1"
			, "LOAD_INIT_DATA"."ALCOUN" AS "ALCOUN"
			, "LOAD_INIT_DATA"."ALADDS" AS "ALADDS"
			, "LOAD_INIT_DATA"."ALCRTE" AS "ALCRTE"
			, "LOAD_INIT_DATA"."ALBKML" AS "ALBKML"
			, "LOAD_INIT_DATA"."ALCTR" AS "ALCTR"
			, "LOAD_INIT_DATA"."ALUSER" AS "ALUSER"
			, "LOAD_INIT_DATA"."ALPID" AS "ALPID"
			, "LOAD_INIT_DATA"."ALUPMJ" AS "ALUPMJ"
			, "LOAD_INIT_DATA"."ALJOBN" AS "ALJOBN"
			, "LOAD_INIT_DATA"."ALUPMT" AS "ALUPMT"
			, "LOAD_INIT_DATA"."ALSYNCS" AS "ALSYNCS"
			, "LOAD_INIT_DATA"."ALCAAD" AS "ALCAAD"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_FLOAT" AS FLOAT) AS "ALAN8"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "ALEFTB"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALEFTF"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADD1"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADD2"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADD3"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADD4"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADDZ"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALCTY1"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALCOUN"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALADDS"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALCRTE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALBKML"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALCTR"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALUSER"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALPID"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "ALUPMJ"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ALJOBN"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "ALUPMT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "ALSYNCS"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_FLOAT" AS FLOAT) AS "ALCAAD"
		FROM {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_DATE" AS "CDC_TIMESTAMP"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."ALAN8" AS "ALAN8"
			, "PREP_EXCEP"."ALEFTB" AS "ALEFTB"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."ALAN8")),"MEX_SRC"."KEY_ATTRIBUTE_FLOAT") AS "ALAN8_BK"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."ALEFTB")),"MEX_SRC"."KEY_ATTRIBUTE_NUMBER") AS "ALEFTB_BK"
			, UPPER( TO_CHAR("PREP_EXCEP"."ALAN8")) AS "ABAN8_FK_ALAN8_BK"
			, "PREP_EXCEP"."ALEFTF" AS "ALEFTF"
			, "PREP_EXCEP"."ALADD1" AS "ALADD1"
			, "PREP_EXCEP"."ALADD2" AS "ALADD2"
			, "PREP_EXCEP"."ALADD3" AS "ALADD3"
			, "PREP_EXCEP"."ALADD4" AS "ALADD4"
			, "PREP_EXCEP"."ALADDZ" AS "ALADDZ"
			, "PREP_EXCEP"."ALCTY1" AS "ALCTY1"
			, "PREP_EXCEP"."ALCOUN" AS "ALCOUN"
			, "PREP_EXCEP"."ALADDS" AS "ALADDS"
			, "PREP_EXCEP"."ALCRTE" AS "ALCRTE"
			, "PREP_EXCEP"."ALBKML" AS "ALBKML"
			, "PREP_EXCEP"."ALCTR" AS "ALCTR"
			, "PREP_EXCEP"."ALUSER" AS "ALUSER"
			, "PREP_EXCEP"."ALPID" AS "ALPID"
			, "PREP_EXCEP"."ALUPMJ" AS "ALUPMJ"
			, "PREP_EXCEP"."ALJOBN" AS "ALJOBN"
			, "PREP_EXCEP"."ALUPMT" AS "ALUPMT"
			, "PREP_EXCEP"."ALSYNCS" AS "ALSYNCS"
			, "PREP_EXCEP"."ALCAAD" AS "ALCAAD"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('JDEDWARDS_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('JDEDWARDS_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."ALAN8" AS "ALAN8"
		, "CALCULATE_BK"."ALEFTB" AS "ALEFTB"
		, "CALCULATE_BK"."ALAN8_BK" AS "ALAN8_BK"
		, "CALCULATE_BK"."ALEFTB_BK" AS "ALEFTB_BK"
		, "CALCULATE_BK"."ABAN8_FK_ALAN8_BK" AS "ABAN8_FK_ALAN8_BK"
		, "CALCULATE_BK"."ALEFTF" AS "ALEFTF"
		, "CALCULATE_BK"."ALADD1" AS "ALADD1"
		, "CALCULATE_BK"."ALADD2" AS "ALADD2"
		, "CALCULATE_BK"."ALADD3" AS "ALADD3"
		, "CALCULATE_BK"."ALADD4" AS "ALADD4"
		, "CALCULATE_BK"."ALADDZ" AS "ALADDZ"
		, "CALCULATE_BK"."ALCTY1" AS "ALCTY1"
		, "CALCULATE_BK"."ALCOUN" AS "ALCOUN"
		, "CALCULATE_BK"."ALADDS" AS "ALADDS"
		, "CALCULATE_BK"."ALCRTE" AS "ALCRTE"
		, "CALCULATE_BK"."ALBKML" AS "ALBKML"
		, "CALCULATE_BK"."ALCTR" AS "ALCTR"
		, "CALCULATE_BK"."ALUSER" AS "ALUSER"
		, "CALCULATE_BK"."ALPID" AS "ALPID"
		, "CALCULATE_BK"."ALUPMJ" AS "ALUPMJ"
		, "CALCULATE_BK"."ALJOBN" AS "ALJOBN"
		, "CALCULATE_BK"."ALUPMT" AS "ALUPMT"
		, "CALCULATE_BK"."ALSYNCS" AS "ALSYNCS"
		, "CALCULATE_BK"."ALCAAD" AS "ALCAAD"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'JDEDWARDS'