{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "SALESFORCE" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='ORDERITEM',
		schema='SALESFORCE_EXT',
		tags=['SALESFORCE', 'EXT_SALESFORCE_ORDERITEM_INCR', 'EXT_SALESFORCE_ORDERITEM_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, DATEADD(microsecond, 2*row_number() over (order by "TDFV_SRC"."CDC_TIMESTAMP"),
				TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()))   AS "LOAD_DATE"
			, "TDFV_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, COALESCE("TDFV_SRC"."JRN_FLAG","MEX_SRC"."ATTRIBUTE_VARCHAR") AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."ID" AS "ID"
			, "TDFV_SRC"."ORDERID" AS "ORDERID"
			, "TDFV_SRC"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
			, "TDFV_SRC"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
			, "TDFV_SRC"."CREATEDBYID" AS "CREATEDBYID"
			, "TDFV_SRC"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, COALESCE(REPLACE(TRIM( "TDFV_SRC"."ID"),'\#','\\' || '\#'),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ID_BK"
			, REPLACE(TRIM( "TDFV_SRC"."PRICEBOOKENTRYID"),'\#','\\' || '\#') AS "ID_FK_PRICEBOOKENTRYID_BK"
			, REPLACE(TRIM( "TDFV_SRC"."ORDERID"),'\#','\\' || '\#') AS "ID_FK_ORDERID_BK"
			, REPLACE(TRIM( "TDFV_SRC"."ORIGINALORDERITEMID"),'\#','\\' || '\#') AS "ID_FK_ORIGINALORDERITEMID_BK"
			, REPLACE(TRIM( "TDFV_SRC"."CREATEDBYID"),'\#','\\' || '\#') AS "ID_FK_CREATEDBYID_BK"
			, REPLACE(TRIM( "TDFV_SRC"."LASTMODIFIEDBYID"),'\#','\\' || '\#') AS "ID_FK_LASTMODIFIEDBYID_BK"
			, "TDFV_SRC"."ISDELETED" AS "ISDELETED"
			, "TDFV_SRC"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
			, "TDFV_SRC"."QUANTITY" AS "QUANTITY"
			, "TDFV_SRC"."UNITPRICE" AS "UNITPRICE"
			, "TDFV_SRC"."LISTPRICE" AS "LISTPRICE"
			, "TDFV_SRC"."SERVICEDATE" AS "SERVICEDATE"
			, "TDFV_SRC"."ENDDATE" AS "ENDDATE"
			, "TDFV_SRC"."DESCRIPTION" AS "DESCRIPTION"
			, "TDFV_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "TDFV_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "TDFV_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "TDFV_SRC"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
		FROM {{ ref('SALESFORCE_DFV_VW_ORDERITEM') }} "TDFV_SRC"
		INNER JOIN {{ source('SALESFORCE_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."ID" AS "ID"
			, "CALCULATE_BK"."ORDERID" AS "ORDERID"
			, "CALCULATE_BK"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
			, "CALCULATE_BK"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
			, "CALCULATE_BK"."CREATEDBYID" AS "CREATEDBYID"
			, "CALCULATE_BK"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "CALCULATE_BK"."ID_BK" AS "ID_BK"
			, "CALCULATE_BK"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
			, "CALCULATE_BK"."ID_FK_ORDERID_BK" AS "ID_FK_ORDERID_BK"
			, "CALCULATE_BK"."ID_FK_ORIGINALORDERITEMID_BK" AS "ID_FK_ORIGINALORDERITEMID_BK"
			, "CALCULATE_BK"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
			, "CALCULATE_BK"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
			, "CALCULATE_BK"."ISDELETED" AS "ISDELETED"
			, "CALCULATE_BK"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
			, "CALCULATE_BK"."QUANTITY" AS "QUANTITY"
			, "CALCULATE_BK"."UNITPRICE" AS "UNITPRICE"
			, "CALCULATE_BK"."LISTPRICE" AS "LISTPRICE"
			, "CALCULATE_BK"."SERVICEDATE" AS "SERVICEDATE"
			, "CALCULATE_BK"."ENDDATE" AS "ENDDATE"
			, "CALCULATE_BK"."DESCRIPTION" AS "DESCRIPTION"
			, "CALCULATE_BK"."CREATEDDATE" AS "CREATEDDATE"
			, "CALCULATE_BK"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "CALCULATE_BK"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "CALCULATE_BK"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."ID" AS "ID"
		, "EXT_UNION"."ORDERID" AS "ORDERID"
		, "EXT_UNION"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "EXT_UNION"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
		, "EXT_UNION"."CREATEDBYID" AS "CREATEDBYID"
		, "EXT_UNION"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "EXT_UNION"."ID_BK" AS "ID_BK"
		, "EXT_UNION"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "EXT_UNION"."ID_FK_ORDERID_BK" AS "ID_FK_ORDERID_BK"
		, "EXT_UNION"."ID_FK_ORIGINALORDERITEMID_BK" AS "ID_FK_ORIGINALORDERITEMID_BK"
		, "EXT_UNION"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "EXT_UNION"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "EXT_UNION"."ISDELETED" AS "ISDELETED"
		, "EXT_UNION"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
		, "EXT_UNION"."QUANTITY" AS "QUANTITY"
		, "EXT_UNION"."UNITPRICE" AS "UNITPRICE"
		, "EXT_UNION"."LISTPRICE" AS "LISTPRICE"
		, "EXT_UNION"."SERVICEDATE" AS "SERVICEDATE"
		, "EXT_UNION"."ENDDATE" AS "ENDDATE"
		, "EXT_UNION"."DESCRIPTION" AS "DESCRIPTION"
		, "EXT_UNION"."CREATEDDATE" AS "CREATEDDATE"
		, "EXT_UNION"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "EXT_UNION"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "EXT_UNION"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'SALESFORCE'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."ID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "ID"
			, COALESCE("INI_SRC"."PRICEBOOKENTRYID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "PRICEBOOKENTRYID"
			, COALESCE("INI_SRC"."ORDERID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "ORDERID"
			, COALESCE("INI_SRC"."ORIGINALORDERITEMID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "ORIGINALORDERITEMID"
			, COALESCE("INI_SRC"."CREATEDBYID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "CREATEDBYID"
			, COALESCE("INI_SRC"."LASTMODIFIEDBYID", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR)) AS "LASTMODIFIEDBYID"
			, "INI_SRC"."ISDELETED" AS "ISDELETED"
			, "INI_SRC"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
			, "INI_SRC"."QUANTITY" AS "QUANTITY"
			, "INI_SRC"."UNITPRICE" AS "UNITPRICE"
			, "INI_SRC"."LISTPRICE" AS "LISTPRICE"
			, "INI_SRC"."SERVICEDATE" AS "SERVICEDATE"
			, "INI_SRC"."ENDDATE" AS "ENDDATE"
			, "INI_SRC"."DESCRIPTION" AS "DESCRIPTION"
			, "INI_SRC"."CREATEDDATE" AS "CREATEDDATE"
			, "INI_SRC"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "INI_SRC"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "INI_SRC"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
		FROM {{ source('SALESFORCE_INI', 'ORDERITEM') }} "INI_SRC"
		INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."ID" AS "ID"
			, "LOAD_INIT_DATA"."ORDERID" AS "ORDERID"
			, "LOAD_INIT_DATA"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
			, "LOAD_INIT_DATA"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
			, "LOAD_INIT_DATA"."CREATEDBYID" AS "CREATEDBYID"
			, "LOAD_INIT_DATA"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, "LOAD_INIT_DATA"."ISDELETED" AS "ISDELETED"
			, "LOAD_INIT_DATA"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
			, "LOAD_INIT_DATA"."QUANTITY" AS "QUANTITY"
			, "LOAD_INIT_DATA"."UNITPRICE" AS "UNITPRICE"
			, "LOAD_INIT_DATA"."LISTPRICE" AS "LISTPRICE"
			, "LOAD_INIT_DATA"."SERVICEDATE" AS "SERVICEDATE"
			, "LOAD_INIT_DATA"."ENDDATE" AS "ENDDATE"
			, "LOAD_INIT_DATA"."DESCRIPTION" AS "DESCRIPTION"
			, "LOAD_INIT_DATA"."CREATEDDATE" AS "CREATEDDATE"
			, "LOAD_INIT_DATA"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "LOAD_INIT_DATA"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "LOAD_INIT_DATA"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ORDERID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "PRICEBOOKENTRYID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ORIGINALORDERITEMID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "CREATEDBYID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "LASTMODIFIEDBYID"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ISDELETED"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "AVAILABLEQUANTITY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "QUANTITY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "UNITPRICE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "LISTPRICE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "SERVICEDATE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ENDDATE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "DESCRIPTION"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "CREATEDDATE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "LASTMODIFIEDDATE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "SYSTEMMODSTAMP"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "ORDERITEMNUMBER"
		FROM {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_DATE" AS "CDC_TIMESTAMP"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."ID" AS "ID"
			, "PREP_EXCEP"."ORDERID" AS "ORDERID"
			, "PREP_EXCEP"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
			, "PREP_EXCEP"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
			, "PREP_EXCEP"."CREATEDBYID" AS "CREATEDBYID"
			, "PREP_EXCEP"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
			, COALESCE(REPLACE(TRIM("PREP_EXCEP"."ID"),'\#','\\' || '\#'),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "ID_BK"
			, REPLACE(TRIM("PREP_EXCEP"."PRICEBOOKENTRYID"),'\#','\\' || '\#') AS "ID_FK_PRICEBOOKENTRYID_BK"
			, REPLACE(TRIM("PREP_EXCEP"."ORDERID"),'\#','\\' || '\#') AS "ID_FK_ORDERID_BK"
			, REPLACE(TRIM("PREP_EXCEP"."ORIGINALORDERITEMID"),'\#','\\' || '\#') AS "ID_FK_ORIGINALORDERITEMID_BK"
			, REPLACE(TRIM("PREP_EXCEP"."CREATEDBYID"),'\#','\\' || '\#') AS "ID_FK_CREATEDBYID_BK"
			, REPLACE(TRIM("PREP_EXCEP"."LASTMODIFIEDBYID"),'\#','\\' || '\#') AS "ID_FK_LASTMODIFIEDBYID_BK"
			, "PREP_EXCEP"."ISDELETED" AS "ISDELETED"
			, "PREP_EXCEP"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
			, "PREP_EXCEP"."QUANTITY" AS "QUANTITY"
			, "PREP_EXCEP"."UNITPRICE" AS "UNITPRICE"
			, "PREP_EXCEP"."LISTPRICE" AS "LISTPRICE"
			, "PREP_EXCEP"."SERVICEDATE" AS "SERVICEDATE"
			, "PREP_EXCEP"."ENDDATE" AS "ENDDATE"
			, "PREP_EXCEP"."DESCRIPTION" AS "DESCRIPTION"
			, "PREP_EXCEP"."CREATEDDATE" AS "CREATEDDATE"
			, "PREP_EXCEP"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
			, "PREP_EXCEP"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
			, "PREP_EXCEP"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('SALESFORCE_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('SALESFORCE_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."ID" AS "ID"
		, "CALCULATE_BK"."ORDERID" AS "ORDERID"
		, "CALCULATE_BK"."PRICEBOOKENTRYID" AS "PRICEBOOKENTRYID"
		, "CALCULATE_BK"."ORIGINALORDERITEMID" AS "ORIGINALORDERITEMID"
		, "CALCULATE_BK"."CREATEDBYID" AS "CREATEDBYID"
		, "CALCULATE_BK"."LASTMODIFIEDBYID" AS "LASTMODIFIEDBYID"
		, "CALCULATE_BK"."ID_BK" AS "ID_BK"
		, "CALCULATE_BK"."ID_FK_PRICEBOOKENTRYID_BK" AS "ID_FK_PRICEBOOKENTRYID_BK"
		, "CALCULATE_BK"."ID_FK_ORDERID_BK" AS "ID_FK_ORDERID_BK"
		, "CALCULATE_BK"."ID_FK_ORIGINALORDERITEMID_BK" AS "ID_FK_ORIGINALORDERITEMID_BK"
		, "CALCULATE_BK"."ID_FK_CREATEDBYID_BK" AS "ID_FK_CREATEDBYID_BK"
		, "CALCULATE_BK"."ID_FK_LASTMODIFIEDBYID_BK" AS "ID_FK_LASTMODIFIEDBYID_BK"
		, "CALCULATE_BK"."ISDELETED" AS "ISDELETED"
		, "CALCULATE_BK"."AVAILABLEQUANTITY" AS "AVAILABLEQUANTITY"
		, "CALCULATE_BK"."QUANTITY" AS "QUANTITY"
		, "CALCULATE_BK"."UNITPRICE" AS "UNITPRICE"
		, "CALCULATE_BK"."LISTPRICE" AS "LISTPRICE"
		, "CALCULATE_BK"."SERVICEDATE" AS "SERVICEDATE"
		, "CALCULATE_BK"."ENDDATE" AS "ENDDATE"
		, "CALCULATE_BK"."DESCRIPTION" AS "DESCRIPTION"
		, "CALCULATE_BK"."CREATEDDATE" AS "CREATEDDATE"
		, "CALCULATE_BK"."LASTMODIFIEDDATE" AS "LASTMODIFIEDDATE"
		, "CALCULATE_BK"."SYSTEMMODSTAMP" AS "SYSTEMMODSTAMP"
		, "CALCULATE_BK"."ORDERITEMNUMBER" AS "ORDERITEMNUMBER"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'SALESFORCE'